/* ===============================================================
Copyright 2026, Infineon Technologies AG or an 
affiliate of Infineon Technologies AG.  All rights reserved.
 
This software, associated documentation and materials ("Software") is owned by
Infineon Technologies AG or one of its affiliates ("Infineon") and is 
protected by and subject to worldwide patent protection (United States and 
foreign), United States copyright laws and international treaty provisions. 
Therefore, you may use this Software only as provided in the license agreement
accompanying the software package from which you obtained this 
Software ("EULA"). If no EULA applies, then any reproduction, modification, 
translation, compilation, or representation of this Software is prohibited 
without the express written permission of Infineon.
 
Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF 
ANY KIND, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, 
NONINFRINGEMENT, IMPLIED WARRANTIES OF  MERCHANTABILITY AND
FITNESS FOR A PARTICULAR PURPOSE.  Infineon reserves the right to make
changes to the Software without notice. Infineon does not assume any liability
arising out of the application or use of the Software or any product or 
circuit described in the Software. Infineon does not authorize its products 
for use in any products where a malfunction or failure of the Infineon product 
may reasonably be expected to result in significant property damage, injury or
death ("High Risk Product").  By including Infineon 's product in a High Risk 
Product, the manufacturer of such system or application assumes all risk of 
such use and in doing so agrees to indemnify Infineon against all liability.

 ===============================================================
*/ 
// File : tc_soc_timer_Reg_IF_Top_CSC.sv 
// Author : tahiraga 
// Date : 15:07:02    25/09/2026 
// Revision :  
// =============================================================== 
// Description : 
/*
---- Auto Generated by MetaRTL , a MetaGen application
---- Contact: ParitoshKumar.Sinha@infineon.com
---- Contact: Yash.Ranjan@infineon.com
===============================================================
*/


module tc_soc_timer_Reg_IF_Top_CSC (
    input logic  [31:0] default_interface_data_in,
    input logic  default_interface_wr_en,
    input logic  [31:0] default_interface_addr,
    output logic  default_interface_error,
    input logic  [1:0] default_interface_AccessSize,
    output logic  [31:0] default_interface_data_out,
    input logic  default_interface_rd_en,
    output logic  default_interface_ready,
    output logic  TimerCSC_BF_bf_OvfIntEn_CH0_out,
    output logic  [2:0] TimerCSC_BF_bf_CntIM_CH0_out,
    output logic  [2:0] TimerCSC_BF_bf_ResIM_CH0_out,
    output logic  TimerCSC_BF_bf_TimEn_CH0_out,
    output logic  [31:0] TimerCSC_BF_bf_ACTVAL_CH0_flipflop_in,
    output logic  TimerCSC_BF_bf_ACTVAL_CH0_flipflop_en,
    input logic  [31:0] TimerCSC_BF_bf_ACTVAL_CH0_flipflop_out,
    input logic  [31:0] TimerCSC_BF_bf_ACTVAL_CH0_in,
    input logic  TimerCSC_BF_bf_ACTVAL_CH0_peripheral_wr_en,
    output logic  [31:0] TimerCSC_BF_bf_ACTVAL_CH0_out,
    output logic  [31:0] TimerCSC_BF_bf_MAXVAL_CH0_flipflop_in,
    output logic  TimerCSC_BF_bf_MAXVAL_CH0_flipflop_en,
    input logic  [31:0] TimerCSC_BF_bf_MAXVAL_CH0_flipflop_out,
    output logic  [31:0] TimerCSC_BF_bf_MAXVAL_CH0_out,
    output logic  [2:0] TimerCSC_BF_bf_CapIM0_CH0_out,
    output logic  [2:0] TimerCSC_BF_bf_CCM0_CH0_out,
    output logic  [31:0] TimerCSC_BF_bf_CCUVAL0_CH0_flipflop_in,
    output logic  TimerCSC_BF_bf_CCUVAL0_CH0_flipflop_en,
    input logic  [31:0] TimerCSC_BF_bf_CCUVAL0_CH0_flipflop_out,
    input logic  [31:0] TimerCSC_BF_bf_CCUVAL0_CH0_in,
    input logic  TimerCSC_BF_bf_CCUVAL0_CH0_peripheral_wr_en,
    output logic  [31:0] TimerCSC_BF_bf_CCUVAL0_CH0_out,
    output logic  TimerCSC_BF_bf_OvfIntEn_CH1_out,
    output logic  [2:0] TimerCSC_BF_bf_CntIM_CH1_out,
    output logic  [2:0] TimerCSC_BF_bf_ResIM_CH1_out,
    output logic  TimerCSC_BF_bf_TimEn_CH1_out,
    output logic  [31:0] TimerCSC_BF_bf_ACTVAL_CH1_flipflop_in,
    output logic  TimerCSC_BF_bf_ACTVAL_CH1_flipflop_en,
    input logic  [31:0] TimerCSC_BF_bf_ACTVAL_CH1_flipflop_out,
    input logic  [31:0] TimerCSC_BF_bf_ACTVAL_CH1_in,
    input logic  TimerCSC_BF_bf_ACTVAL_CH1_peripheral_wr_en,
    output logic  [31:0] TimerCSC_BF_bf_ACTVAL_CH1_out,
    output logic  [31:0] TimerCSC_BF_bf_MAXVAL_CH1_flipflop_in,
    output logic  TimerCSC_BF_bf_MAXVAL_CH1_flipflop_en,
    input logic  [31:0] TimerCSC_BF_bf_MAXVAL_CH1_flipflop_out,
    output logic  [31:0] TimerCSC_BF_bf_MAXVAL_CH1_out,
    output logic  [2:0] TimerCSC_BF_bf_CapIM0_CH1_out,
    output logic  [2:0] TimerCSC_BF_bf_CCM0_CH1_out,
    output logic  [31:0] TimerCSC_BF_bf_CCUVAL0_CH1_flipflop_in,
    output logic  TimerCSC_BF_bf_CCUVAL0_CH1_flipflop_en,
    input logic  [31:0] TimerCSC_BF_bf_CCUVAL0_CH1_flipflop_out,
    input logic  [31:0] TimerCSC_BF_bf_CCUVAL0_CH1_in,
    input logic  TimerCSC_BF_bf_CCUVAL0_CH1_peripheral_wr_en,
    output logic  [31:0] TimerCSC_BF_bf_CCUVAL0_CH1_out,
    output logic  [2:0] TimerCSC_BF_bf_CapIM1_CH1_out,
    output logic  [2:0] TimerCSC_BF_bf_CCM1_CH1_out,
    output logic  [31:0] TimerCSC_BF_bf_CCUVAL1_CH1_flipflop_in,
    output logic  TimerCSC_BF_bf_CCUVAL1_CH1_flipflop_en,
    input logic  [31:0] TimerCSC_BF_bf_CCUVAL1_CH1_flipflop_out,
    input logic  [31:0] TimerCSC_BF_bf_CCUVAL1_CH1_in,
    input logic  TimerCSC_BF_bf_CCUVAL1_CH1_peripheral_wr_en,
    output logic  [31:0] TimerCSC_BF_bf_CCUVAL1_CH1_out,
    output logic  [2:0] TimerCSC_BF_bf_CapIM2_CH1_out,
    output logic  [2:0] TimerCSC_BF_bf_CCM2_CH1_out,
    output logic  [31:0] TimerCSC_BF_bf_CCUVAL2_CH1_flipflop_in,
    output logic  TimerCSC_BF_bf_CCUVAL2_CH1_flipflop_en,
    input logic  [31:0] TimerCSC_BF_bf_CCUVAL2_CH1_flipflop_out,
    input logic  [31:0] TimerCSC_BF_bf_CCUVAL2_CH1_in,
    input logic  TimerCSC_BF_bf_CCUVAL2_CH1_peripheral_wr_en,
    output logic  [31:0] TimerCSC_BF_bf_CCUVAL2_CH1_out,
    output logic  [2:0] TimerCSC_BF_bf_CapIM3_CH1_out,
    output logic  [2:0] TimerCSC_BF_bf_CCM3_CH1_out,
    output logic  [31:0] TimerCSC_BF_bf_CCUVAL3_CH1_flipflop_in,
    output logic  TimerCSC_BF_bf_CCUVAL3_CH1_flipflop_en,
    input logic  [31:0] TimerCSC_BF_bf_CCUVAL3_CH1_flipflop_out,
    input logic  [31:0] TimerCSC_BF_bf_CCUVAL3_CH1_in,
    input logic  TimerCSC_BF_bf_CCUVAL3_CH1_peripheral_wr_en,
    output logic  [31:0] TimerCSC_BF_bf_CCUVAL3_CH1_out,
    output logic  [2:0] TimerCSC_BF_bf_CapIM4_CH1_out,
    output logic  [2:0] TimerCSC_BF_bf_CCM4_CH1_out,
    output logic  [31:0] TimerCSC_BF_bf_CCUVAL4_CH1_flipflop_in,
    output logic  TimerCSC_BF_bf_CCUVAL4_CH1_flipflop_en,
    input logic  [31:0] TimerCSC_BF_bf_CCUVAL4_CH1_flipflop_out,
    input logic  [31:0] TimerCSC_BF_bf_CCUVAL4_CH1_in,
    input logic  TimerCSC_BF_bf_CCUVAL4_CH1_peripheral_wr_en,
    output logic  [31:0] TimerCSC_BF_bf_CCUVAL4_CH1_out,
    output logic  [2:0] TimerCSC_BF_bf_CapIM5_CH1_out,
    output logic  [2:0] TimerCSC_BF_bf_CCM5_CH1_out,
    output logic  [31:0] TimerCSC_BF_bf_CCUVAL5_CH1_flipflop_in,
    output logic  TimerCSC_BF_bf_CCUVAL5_CH1_flipflop_en,
    input logic  [31:0] TimerCSC_BF_bf_CCUVAL5_CH1_flipflop_out,
    input logic  [31:0] TimerCSC_BF_bf_CCUVAL5_CH1_in,
    input logic  TimerCSC_BF_bf_CCUVAL5_CH1_peripheral_wr_en,
    output logic  [31:0] TimerCSC_BF_bf_CCUVAL5_CH1_out,
    input logic  HCLK_i,
    input logic  HRESET_n_i
);

logic   Top_CSC_default_interface_default_interface_BF_bf_OvfIntEn_CH0_input_s;
logic   Top_CSC_default_interface_default_interface_BF_bf_OvfIntEn_CH0_enable_s;
logic   [2:0] Top_CSC_default_interface_default_interface_BF_bf_CntIM_CH0_input_s;
logic   Top_CSC_default_interface_default_interface_BF_bf_CntIM_CH0_enable_s;
logic   [2:0] Top_CSC_default_interface_default_interface_BF_bf_ResIM_CH0_input_s;
logic   Top_CSC_default_interface_default_interface_BF_bf_ResIM_CH0_enable_s;
logic   Top_CSC_default_interface_default_interface_BF_bf_TimEn_CH0_input_s;
logic   Top_CSC_default_interface_default_interface_BF_bf_TimEn_CH0_enable_s;
logic   [2:0] Top_CSC_default_interface_default_interface_BF_bf_CapIM0_CH0_input_s;
logic   Top_CSC_default_interface_default_interface_BF_bf_CapIM0_CH0_enable_s;
logic   [2:0] Top_CSC_default_interface_default_interface_BF_bf_CCM0_CH0_input_s;
logic   Top_CSC_default_interface_default_interface_BF_bf_CCM0_CH0_enable_s;
logic   Top_CSC_default_interface_default_interface_BF_bf_OvfIntEn_CH1_input_s;
logic   Top_CSC_default_interface_default_interface_BF_bf_OvfIntEn_CH1_enable_s;
logic   [2:0] Top_CSC_default_interface_default_interface_BF_bf_CntIM_CH1_input_s;
logic   Top_CSC_default_interface_default_interface_BF_bf_CntIM_CH1_enable_s;
logic   [2:0] Top_CSC_default_interface_default_interface_BF_bf_ResIM_CH1_input_s;
logic   Top_CSC_default_interface_default_interface_BF_bf_ResIM_CH1_enable_s;
logic   Top_CSC_default_interface_default_interface_BF_bf_TimEn_CH1_input_s;
logic   Top_CSC_default_interface_default_interface_BF_bf_TimEn_CH1_enable_s;
logic   [2:0] Top_CSC_default_interface_default_interface_BF_bf_CapIM0_CH1_input_s;
logic   Top_CSC_default_interface_default_interface_BF_bf_CapIM0_CH1_enable_s;
logic   [2:0] Top_CSC_default_interface_default_interface_BF_bf_CCM0_CH1_input_s;
logic   Top_CSC_default_interface_default_interface_BF_bf_CCM0_CH1_enable_s;
logic   [2:0] Top_CSC_default_interface_default_interface_BF_bf_CapIM1_CH1_input_s;
logic   Top_CSC_default_interface_default_interface_BF_bf_CapIM1_CH1_enable_s;
logic   [2:0] Top_CSC_default_interface_default_interface_BF_bf_CCM1_CH1_input_s;
logic   Top_CSC_default_interface_default_interface_BF_bf_CCM1_CH1_enable_s;
logic   [2:0] Top_CSC_default_interface_default_interface_BF_bf_CapIM2_CH1_input_s;
logic   Top_CSC_default_interface_default_interface_BF_bf_CapIM2_CH1_enable_s;
logic   [2:0] Top_CSC_default_interface_default_interface_BF_bf_CCM2_CH1_input_s;
logic   Top_CSC_default_interface_default_interface_BF_bf_CCM2_CH1_enable_s;
logic   [2:0] Top_CSC_default_interface_default_interface_BF_bf_CapIM3_CH1_input_s;
logic   Top_CSC_default_interface_default_interface_BF_bf_CapIM3_CH1_enable_s;
logic   [2:0] Top_CSC_default_interface_default_interface_BF_bf_CCM3_CH1_input_s;
logic   Top_CSC_default_interface_default_interface_BF_bf_CCM3_CH1_enable_s;
logic   [2:0] Top_CSC_default_interface_default_interface_BF_bf_CapIM4_CH1_input_s;
logic   Top_CSC_default_interface_default_interface_BF_bf_CapIM4_CH1_enable_s;
logic   [2:0] Top_CSC_default_interface_default_interface_BF_bf_CCM4_CH1_input_s;
logic   Top_CSC_default_interface_default_interface_BF_bf_CCM4_CH1_enable_s;
logic   [2:0] Top_CSC_default_interface_default_interface_BF_bf_CapIM5_CH1_input_s;
logic   Top_CSC_default_interface_default_interface_BF_bf_CapIM5_CH1_enable_s;
logic   [2:0] Top_CSC_default_interface_default_interface_BF_bf_CCM5_CH1_input_s;
logic   Top_CSC_default_interface_default_interface_BF_bf_CCM5_CH1_enable_s;

logic   [2:0] BF_bf_CCM5_CH1_Outp_s;
logic   [2:0] BF_bf_CapIM5_CH1_Outp_s;
logic   [2:0] BF_bf_CCM4_CH1_Outp_s;
logic   [2:0] BF_bf_CapIM4_CH1_Outp_s;
logic   [2:0] BF_bf_CCM3_CH1_Outp_s;
logic   [2:0] BF_bf_CapIM3_CH1_Outp_s;
logic   [2:0] BF_bf_CCM2_CH1_Outp_s;
logic   [2:0] BF_bf_CapIM2_CH1_Outp_s;
logic   [2:0] BF_bf_CCM1_CH1_Outp_s;
logic   [2:0] BF_bf_CapIM1_CH1_Outp_s;
logic   [2:0] BF_bf_CCM0_CH1_Outp_s;
logic   [2:0] BF_bf_CapIM0_CH1_Outp_s;
logic   BF_bf_TimEn_CH1_Outp_s;
logic   [2:0] BF_bf_ResIM_CH1_Outp_s;
logic   [2:0] BF_bf_CntIM_CH1_Outp_s;
logic   BF_bf_OvfIntEn_CH1_Outp_s;
logic   [2:0] BF_bf_CCM0_CH0_Outp_s;
logic   [2:0] BF_bf_CapIM0_CH0_Outp_s;
logic   BF_bf_TimEn_CH0_Outp_s;
logic   [2:0] BF_bf_ResIM_CH0_Outp_s;
logic   [2:0] BF_bf_CntIM_CH0_Outp_s;
logic   BF_bf_OvfIntEn_CH0_Outp_s;

always_ff @(negedge HRESET_n_i, posedge HCLK_i)
begin
    if (HRESET_n_i == 1'b0) begin
        BF_bf_CCM5_CH1_Outp_s <= 3'b0;
    end else begin
        if (Top_CSC_default_interface_default_interface_BF_bf_CCM5_CH1_enable_s == 1'b1) begin
            BF_bf_CCM5_CH1_Outp_s <= Top_CSC_default_interface_default_interface_BF_bf_CCM5_CH1_input_s;
        end
    end

end

always_ff @(negedge HRESET_n_i, posedge HCLK_i)
begin
    if (HRESET_n_i == 1'b0) begin
        BF_bf_CapIM5_CH1_Outp_s <= 3'b0;
    end else begin
        if (Top_CSC_default_interface_default_interface_BF_bf_CapIM5_CH1_enable_s == 1'b1) begin
            BF_bf_CapIM5_CH1_Outp_s <= Top_CSC_default_interface_default_interface_BF_bf_CapIM5_CH1_input_s;
        end
    end

end

always_ff @(negedge HRESET_n_i, posedge HCLK_i)
begin
    if (HRESET_n_i == 1'b0) begin
        BF_bf_CCM4_CH1_Outp_s <= 3'b0;
    end else begin
        if (Top_CSC_default_interface_default_interface_BF_bf_CCM4_CH1_enable_s == 1'b1) begin
            BF_bf_CCM4_CH1_Outp_s <= Top_CSC_default_interface_default_interface_BF_bf_CCM4_CH1_input_s;
        end
    end

end

always_ff @(negedge HRESET_n_i, posedge HCLK_i)
begin
    if (HRESET_n_i == 1'b0) begin
        BF_bf_CapIM4_CH1_Outp_s <= 3'b0;
    end else begin
        if (Top_CSC_default_interface_default_interface_BF_bf_CapIM4_CH1_enable_s == 1'b1) begin
            BF_bf_CapIM4_CH1_Outp_s <= Top_CSC_default_interface_default_interface_BF_bf_CapIM4_CH1_input_s;
        end
    end

end

always_ff @(negedge HRESET_n_i, posedge HCLK_i)
begin
    if (HRESET_n_i == 1'b0) begin
        BF_bf_CCM3_CH1_Outp_s <= 3'b0;
    end else begin
        if (Top_CSC_default_interface_default_interface_BF_bf_CCM3_CH1_enable_s == 1'b1) begin
            BF_bf_CCM3_CH1_Outp_s <= Top_CSC_default_interface_default_interface_BF_bf_CCM3_CH1_input_s;
        end
    end

end

always_ff @(negedge HRESET_n_i, posedge HCLK_i)
begin
    if (HRESET_n_i == 1'b0) begin
        BF_bf_CapIM3_CH1_Outp_s <= 3'b0;
    end else begin
        if (Top_CSC_default_interface_default_interface_BF_bf_CapIM3_CH1_enable_s == 1'b1) begin
            BF_bf_CapIM3_CH1_Outp_s <= Top_CSC_default_interface_default_interface_BF_bf_CapIM3_CH1_input_s;
        end
    end

end

always_ff @(negedge HRESET_n_i, posedge HCLK_i)
begin
    if (HRESET_n_i == 1'b0) begin
        BF_bf_CCM2_CH1_Outp_s <= 3'b0;
    end else begin
        if (Top_CSC_default_interface_default_interface_BF_bf_CCM2_CH1_enable_s == 1'b1) begin
            BF_bf_CCM2_CH1_Outp_s <= Top_CSC_default_interface_default_interface_BF_bf_CCM2_CH1_input_s;
        end
    end

end

always_ff @(negedge HRESET_n_i, posedge HCLK_i)
begin
    if (HRESET_n_i == 1'b0) begin
        BF_bf_CapIM2_CH1_Outp_s <= 3'b0;
    end else begin
        if (Top_CSC_default_interface_default_interface_BF_bf_CapIM2_CH1_enable_s == 1'b1) begin
            BF_bf_CapIM2_CH1_Outp_s <= Top_CSC_default_interface_default_interface_BF_bf_CapIM2_CH1_input_s;
        end
    end

end

always_ff @(negedge HRESET_n_i, posedge HCLK_i)
begin
    if (HRESET_n_i == 1'b0) begin
        BF_bf_CCM1_CH1_Outp_s <= 3'b0;
    end else begin
        if (Top_CSC_default_interface_default_interface_BF_bf_CCM1_CH1_enable_s == 1'b1) begin
            BF_bf_CCM1_CH1_Outp_s <= Top_CSC_default_interface_default_interface_BF_bf_CCM1_CH1_input_s;
        end
    end

end

always_ff @(negedge HRESET_n_i, posedge HCLK_i)
begin
    if (HRESET_n_i == 1'b0) begin
        BF_bf_CapIM1_CH1_Outp_s <= 3'b0;
    end else begin
        if (Top_CSC_default_interface_default_interface_BF_bf_CapIM1_CH1_enable_s == 1'b1) begin
            BF_bf_CapIM1_CH1_Outp_s <= Top_CSC_default_interface_default_interface_BF_bf_CapIM1_CH1_input_s;
        end
    end

end

always_ff @(negedge HRESET_n_i, posedge HCLK_i)
begin
    if (HRESET_n_i == 1'b0) begin
        BF_bf_CCM0_CH1_Outp_s <= 3'b0;
    end else begin
        if (Top_CSC_default_interface_default_interface_BF_bf_CCM0_CH1_enable_s == 1'b1) begin
            BF_bf_CCM0_CH1_Outp_s <= Top_CSC_default_interface_default_interface_BF_bf_CCM0_CH1_input_s;
        end
    end

end

always_ff @(negedge HRESET_n_i, posedge HCLK_i)
begin
    if (HRESET_n_i == 1'b0) begin
        BF_bf_CapIM0_CH1_Outp_s <= 3'b0;
    end else begin
        if (Top_CSC_default_interface_default_interface_BF_bf_CapIM0_CH1_enable_s == 1'b1) begin
            BF_bf_CapIM0_CH1_Outp_s <= Top_CSC_default_interface_default_interface_BF_bf_CapIM0_CH1_input_s;
        end
    end

end

always_ff @(negedge HRESET_n_i, posedge HCLK_i)
begin
    if (HRESET_n_i == 1'b0) begin
        BF_bf_TimEn_CH1_Outp_s <= 1'b0;
    end else begin
        if (Top_CSC_default_interface_default_interface_BF_bf_TimEn_CH1_enable_s == 1'b1) begin
            BF_bf_TimEn_CH1_Outp_s <= Top_CSC_default_interface_default_interface_BF_bf_TimEn_CH1_input_s;
        end
    end

end

always_ff @(negedge HRESET_n_i, posedge HCLK_i)
begin
    if (HRESET_n_i == 1'b0) begin
        BF_bf_ResIM_CH1_Outp_s <= 3'b0;
    end else begin
        if (Top_CSC_default_interface_default_interface_BF_bf_ResIM_CH1_enable_s == 1'b1) begin
            BF_bf_ResIM_CH1_Outp_s <= Top_CSC_default_interface_default_interface_BF_bf_ResIM_CH1_input_s;
        end
    end

end

always_ff @(negedge HRESET_n_i, posedge HCLK_i)
begin
    if (HRESET_n_i == 1'b0) begin
        BF_bf_CntIM_CH1_Outp_s <= 3'b0;
    end else begin
        if (Top_CSC_default_interface_default_interface_BF_bf_CntIM_CH1_enable_s == 1'b1) begin
            BF_bf_CntIM_CH1_Outp_s <= Top_CSC_default_interface_default_interface_BF_bf_CntIM_CH1_input_s;
        end
    end

end

always_ff @(negedge HRESET_n_i, posedge HCLK_i)
begin
    if (HRESET_n_i == 1'b0) begin
        BF_bf_OvfIntEn_CH1_Outp_s <= 1'b0;
    end else begin
        if (Top_CSC_default_interface_default_interface_BF_bf_OvfIntEn_CH1_enable_s == 1'b1) begin
            BF_bf_OvfIntEn_CH1_Outp_s <= Top_CSC_default_interface_default_interface_BF_bf_OvfIntEn_CH1_input_s;
        end
    end

end

always_ff @(negedge HRESET_n_i, posedge HCLK_i)
begin
    if (HRESET_n_i == 1'b0) begin
        BF_bf_CCM0_CH0_Outp_s <= 3'b0;
    end else begin
        if (Top_CSC_default_interface_default_interface_BF_bf_CCM0_CH0_enable_s == 1'b1) begin
            BF_bf_CCM0_CH0_Outp_s <= Top_CSC_default_interface_default_interface_BF_bf_CCM0_CH0_input_s;
        end
    end

end

always_ff @(negedge HRESET_n_i, posedge HCLK_i)
begin
    if (HRESET_n_i == 1'b0) begin
        BF_bf_CapIM0_CH0_Outp_s <= 3'b0;
    end else begin
        if (Top_CSC_default_interface_default_interface_BF_bf_CapIM0_CH0_enable_s == 1'b1) begin
            BF_bf_CapIM0_CH0_Outp_s <= Top_CSC_default_interface_default_interface_BF_bf_CapIM0_CH0_input_s;
        end
    end

end

always_ff @(negedge HRESET_n_i, posedge HCLK_i)
begin
    if (HRESET_n_i == 1'b0) begin
        BF_bf_TimEn_CH0_Outp_s <= 1'b0;
    end else begin
        if (Top_CSC_default_interface_default_interface_BF_bf_TimEn_CH0_enable_s == 1'b1) begin
            BF_bf_TimEn_CH0_Outp_s <= Top_CSC_default_interface_default_interface_BF_bf_TimEn_CH0_input_s;
        end
    end

end

always_ff @(negedge HRESET_n_i, posedge HCLK_i)
begin
    if (HRESET_n_i == 1'b0) begin
        BF_bf_ResIM_CH0_Outp_s <= 3'b0;
    end else begin
        if (Top_CSC_default_interface_default_interface_BF_bf_ResIM_CH0_enable_s == 1'b1) begin
            BF_bf_ResIM_CH0_Outp_s <= Top_CSC_default_interface_default_interface_BF_bf_ResIM_CH0_input_s;
        end
    end

end

always_ff @(negedge HRESET_n_i, posedge HCLK_i)
begin
    if (HRESET_n_i == 1'b0) begin
        BF_bf_CntIM_CH0_Outp_s <= 3'b0;
    end else begin
        if (Top_CSC_default_interface_default_interface_BF_bf_CntIM_CH0_enable_s == 1'b1) begin
            BF_bf_CntIM_CH0_Outp_s <= Top_CSC_default_interface_default_interface_BF_bf_CntIM_CH0_input_s;
        end
    end

end

always_ff @(negedge HRESET_n_i, posedge HCLK_i)
begin
    if (HRESET_n_i == 1'b0) begin
        BF_bf_OvfIntEn_CH0_Outp_s <= 1'b0;
    end else begin
        if (Top_CSC_default_interface_default_interface_BF_bf_OvfIntEn_CH0_enable_s == 1'b1) begin
            BF_bf_OvfIntEn_CH0_Outp_s <= Top_CSC_default_interface_default_interface_BF_bf_OvfIntEn_CH0_input_s;
        end
    end

end

tc_soc_timer_Reg_IF_Top_CSC_Top_CSC_default_interface comp_Top_CSC_default_interface(
    .default_interface_addr                               ( default_interface_addr                                                  ),
    .default_interface_AccessSize                         ( default_interface_AccessSize                                            ),
    .default_interface_data_in                            ( default_interface_data_in                                               ),
    .default_interface_wr_en                              ( default_interface_wr_en                                                 ),
    .default_interface_rd_en                              ( default_interface_rd_en                                                 ),
    .default_interface_BF_bf_OvfIntEn_CH0_output          ( BF_bf_OvfIntEn_CH0_Outp_s                                               ),
    .default_interface_BF_bf_CntIM_CH0_output             ( BF_bf_CntIM_CH0_Outp_s                                                  ),
    .default_interface_BF_bf_ResIM_CH0_output             ( BF_bf_ResIM_CH0_Outp_s                                                  ),
    .default_interface_BF_bf_TimEn_CH0_output             ( BF_bf_TimEn_CH0_Outp_s                                                  ),
    .default_interface_BF_bf_ACTVAL_CH0_flipflop_out      ( TimerCSC_BF_bf_ACTVAL_CH0_flipflop_out                                  ),
    .default_interface_BF_bf_ACTVAL_CH0_in                ( TimerCSC_BF_bf_ACTVAL_CH0_in                                            ),
    .default_interface_BF_bf_ACTVAL_CH0_peripheral_wr_en  ( TimerCSC_BF_bf_ACTVAL_CH0_peripheral_wr_en                              ),
    .default_interface_BF_bf_MAXVAL_CH0_flipflop_out      ( TimerCSC_BF_bf_MAXVAL_CH0_flipflop_out                                  ),
    .default_interface_BF_bf_CapIM0_CH0_output            ( BF_bf_CapIM0_CH0_Outp_s                                                 ),
    .default_interface_BF_bf_CCM0_CH0_output              ( BF_bf_CCM0_CH0_Outp_s                                                   ),
    .default_interface_BF_bf_CCUVAL0_CH0_flipflop_out     ( TimerCSC_BF_bf_CCUVAL0_CH0_flipflop_out                                 ),
    .default_interface_BF_bf_CCUVAL0_CH0_in               ( TimerCSC_BF_bf_CCUVAL0_CH0_in                                           ),
    .default_interface_BF_bf_CCUVAL0_CH0_peripheral_wr_en ( TimerCSC_BF_bf_CCUVAL0_CH0_peripheral_wr_en                             ),
    .default_interface_BF_bf_OvfIntEn_CH1_output          ( BF_bf_OvfIntEn_CH1_Outp_s                                               ),
    .default_interface_BF_bf_CntIM_CH1_output             ( BF_bf_CntIM_CH1_Outp_s                                                  ),
    .default_interface_BF_bf_ResIM_CH1_output             ( BF_bf_ResIM_CH1_Outp_s                                                  ),
    .default_interface_BF_bf_TimEn_CH1_output             ( BF_bf_TimEn_CH1_Outp_s                                                  ),
    .default_interface_BF_bf_ACTVAL_CH1_flipflop_out      ( TimerCSC_BF_bf_ACTVAL_CH1_flipflop_out                                  ),
    .default_interface_BF_bf_ACTVAL_CH1_in                ( TimerCSC_BF_bf_ACTVAL_CH1_in                                            ),
    .default_interface_BF_bf_ACTVAL_CH1_peripheral_wr_en  ( TimerCSC_BF_bf_ACTVAL_CH1_peripheral_wr_en                              ),
    .default_interface_BF_bf_MAXVAL_CH1_flipflop_out      ( TimerCSC_BF_bf_MAXVAL_CH1_flipflop_out                                  ),
    .default_interface_BF_bf_CapIM0_CH1_output            ( BF_bf_CapIM0_CH1_Outp_s                                                 ),
    .default_interface_BF_bf_CCM0_CH1_output              ( BF_bf_CCM0_CH1_Outp_s                                                   ),
    .default_interface_BF_bf_CCUVAL0_CH1_flipflop_out     ( TimerCSC_BF_bf_CCUVAL0_CH1_flipflop_out                                 ),
    .default_interface_BF_bf_CCUVAL0_CH1_in               ( TimerCSC_BF_bf_CCUVAL0_CH1_in                                           ),
    .default_interface_BF_bf_CCUVAL0_CH1_peripheral_wr_en ( TimerCSC_BF_bf_CCUVAL0_CH1_peripheral_wr_en                             ),
    .default_interface_BF_bf_CapIM1_CH1_output            ( BF_bf_CapIM1_CH1_Outp_s                                                 ),
    .default_interface_BF_bf_CCM1_CH1_output              ( BF_bf_CCM1_CH1_Outp_s                                                   ),
    .default_interface_BF_bf_CCUVAL1_CH1_flipflop_out     ( TimerCSC_BF_bf_CCUVAL1_CH1_flipflop_out                                 ),
    .default_interface_BF_bf_CCUVAL1_CH1_in               ( TimerCSC_BF_bf_CCUVAL1_CH1_in                                           ),
    .default_interface_BF_bf_CCUVAL1_CH1_peripheral_wr_en ( TimerCSC_BF_bf_CCUVAL1_CH1_peripheral_wr_en                             ),
    .default_interface_BF_bf_CapIM2_CH1_output            ( BF_bf_CapIM2_CH1_Outp_s                                                 ),
    .default_interface_BF_bf_CCM2_CH1_output              ( BF_bf_CCM2_CH1_Outp_s                                                   ),
    .default_interface_BF_bf_CCUVAL2_CH1_flipflop_out     ( TimerCSC_BF_bf_CCUVAL2_CH1_flipflop_out                                 ),
    .default_interface_BF_bf_CCUVAL2_CH1_in               ( TimerCSC_BF_bf_CCUVAL2_CH1_in                                           ),
    .default_interface_BF_bf_CCUVAL2_CH1_peripheral_wr_en ( TimerCSC_BF_bf_CCUVAL2_CH1_peripheral_wr_en                             ),
    .default_interface_BF_bf_CapIM3_CH1_output            ( BF_bf_CapIM3_CH1_Outp_s                                                 ),
    .default_interface_BF_bf_CCM3_CH1_output              ( BF_bf_CCM3_CH1_Outp_s                                                   ),
    .default_interface_BF_bf_CCUVAL3_CH1_flipflop_out     ( TimerCSC_BF_bf_CCUVAL3_CH1_flipflop_out                                 ),
    .default_interface_BF_bf_CCUVAL3_CH1_in               ( TimerCSC_BF_bf_CCUVAL3_CH1_in                                           ),
    .default_interface_BF_bf_CCUVAL3_CH1_peripheral_wr_en ( TimerCSC_BF_bf_CCUVAL3_CH1_peripheral_wr_en                             ),
    .default_interface_BF_bf_CapIM4_CH1_output            ( BF_bf_CapIM4_CH1_Outp_s                                                 ),
    .default_interface_BF_bf_CCM4_CH1_output              ( BF_bf_CCM4_CH1_Outp_s                                                   ),
    .default_interface_BF_bf_CCUVAL4_CH1_flipflop_out     ( TimerCSC_BF_bf_CCUVAL4_CH1_flipflop_out                                 ),
    .default_interface_BF_bf_CCUVAL4_CH1_in               ( TimerCSC_BF_bf_CCUVAL4_CH1_in                                           ),
    .default_interface_BF_bf_CCUVAL4_CH1_peripheral_wr_en ( TimerCSC_BF_bf_CCUVAL4_CH1_peripheral_wr_en                             ),
    .default_interface_BF_bf_CapIM5_CH1_output            ( BF_bf_CapIM5_CH1_Outp_s                                                 ),
    .default_interface_BF_bf_CCM5_CH1_output              ( BF_bf_CCM5_CH1_Outp_s                                                   ),
    .default_interface_BF_bf_CCUVAL5_CH1_flipflop_out     ( TimerCSC_BF_bf_CCUVAL5_CH1_flipflop_out                                 ),
    .default_interface_BF_bf_CCUVAL5_CH1_in               ( TimerCSC_BF_bf_CCUVAL5_CH1_in                                           ),
    .default_interface_BF_bf_CCUVAL5_CH1_peripheral_wr_en ( TimerCSC_BF_bf_CCUVAL5_CH1_peripheral_wr_en                             ),
    .default_interface_Address_Error_Port                 ( default_interface_error                                                 ),
    .default_interface_data_out                           ( default_interface_data_out                                              ),
    .default_interface_ready                              ( default_interface_ready                                                 ),
    .default_interface_BF_bf_OvfIntEn_CH0_input           ( Top_CSC_default_interface_default_interface_BF_bf_OvfIntEn_CH0_input_s  ),
    .default_interface_BF_bf_OvfIntEn_CH0_enable          ( Top_CSC_default_interface_default_interface_BF_bf_OvfIntEn_CH0_enable_s ),
    .default_interface_BF_bf_OvfIntEn_CH0_out             ( TimerCSC_BF_bf_OvfIntEn_CH0_out                                         ),
    .default_interface_BF_bf_CntIM_CH0_input              ( Top_CSC_default_interface_default_interface_BF_bf_CntIM_CH0_input_s     ),
    .default_interface_BF_bf_CntIM_CH0_enable             ( Top_CSC_default_interface_default_interface_BF_bf_CntIM_CH0_enable_s    ),
    .default_interface_BF_bf_CntIM_CH0_out                ( TimerCSC_BF_bf_CntIM_CH0_out                                            ),
    .default_interface_BF_bf_ResIM_CH0_input              ( Top_CSC_default_interface_default_interface_BF_bf_ResIM_CH0_input_s     ),
    .default_interface_BF_bf_ResIM_CH0_enable             ( Top_CSC_default_interface_default_interface_BF_bf_ResIM_CH0_enable_s    ),
    .default_interface_BF_bf_ResIM_CH0_out                ( TimerCSC_BF_bf_ResIM_CH0_out                                            ),
    .default_interface_BF_bf_TimEn_CH0_input              ( Top_CSC_default_interface_default_interface_BF_bf_TimEn_CH0_input_s     ),
    .default_interface_BF_bf_TimEn_CH0_enable             ( Top_CSC_default_interface_default_interface_BF_bf_TimEn_CH0_enable_s    ),
    .default_interface_BF_bf_TimEn_CH0_out                ( TimerCSC_BF_bf_TimEn_CH0_out                                            ),
    .default_interface_BF_bf_ACTVAL_CH0_flipflop_in       ( TimerCSC_BF_bf_ACTVAL_CH0_flipflop_in                                   ),
    .default_interface_BF_bf_ACTVAL_CH0_flipflop_en       ( TimerCSC_BF_bf_ACTVAL_CH0_flipflop_en                                   ),
    .default_interface_BF_bf_ACTVAL_CH0_out               ( TimerCSC_BF_bf_ACTVAL_CH0_out                                           ),
    .default_interface_BF_bf_MAXVAL_CH0_flipflop_in       ( TimerCSC_BF_bf_MAXVAL_CH0_flipflop_in                                   ),
    .default_interface_BF_bf_MAXVAL_CH0_flipflop_en       ( TimerCSC_BF_bf_MAXVAL_CH0_flipflop_en                                   ),
    .default_interface_BF_bf_MAXVAL_CH0_out               ( TimerCSC_BF_bf_MAXVAL_CH0_out                                           ),
    .default_interface_BF_bf_CapIM0_CH0_input             ( Top_CSC_default_interface_default_interface_BF_bf_CapIM0_CH0_input_s    ),
    .default_interface_BF_bf_CapIM0_CH0_enable            ( Top_CSC_default_interface_default_interface_BF_bf_CapIM0_CH0_enable_s   ),
    .default_interface_BF_bf_CapIM0_CH0_out               ( TimerCSC_BF_bf_CapIM0_CH0_out                                           ),
    .default_interface_BF_bf_CCM0_CH0_input               ( Top_CSC_default_interface_default_interface_BF_bf_CCM0_CH0_input_s      ),
    .default_interface_BF_bf_CCM0_CH0_enable              ( Top_CSC_default_interface_default_interface_BF_bf_CCM0_CH0_enable_s     ),
    .default_interface_BF_bf_CCM0_CH0_out                 ( TimerCSC_BF_bf_CCM0_CH0_out                                             ),
    .default_interface_BF_bf_CCUVAL0_CH0_flipflop_in      ( TimerCSC_BF_bf_CCUVAL0_CH0_flipflop_in                                  ),
    .default_interface_BF_bf_CCUVAL0_CH0_flipflop_en      ( TimerCSC_BF_bf_CCUVAL0_CH0_flipflop_en                                  ),
    .default_interface_BF_bf_CCUVAL0_CH0_out              ( TimerCSC_BF_bf_CCUVAL0_CH0_out                                          ),
    .default_interface_BF_bf_OvfIntEn_CH1_input           ( Top_CSC_default_interface_default_interface_BF_bf_OvfIntEn_CH1_input_s  ),
    .default_interface_BF_bf_OvfIntEn_CH1_enable          ( Top_CSC_default_interface_default_interface_BF_bf_OvfIntEn_CH1_enable_s ),
    .default_interface_BF_bf_OvfIntEn_CH1_out             ( TimerCSC_BF_bf_OvfIntEn_CH1_out                                         ),
    .default_interface_BF_bf_CntIM_CH1_input              ( Top_CSC_default_interface_default_interface_BF_bf_CntIM_CH1_input_s     ),
    .default_interface_BF_bf_CntIM_CH1_enable             ( Top_CSC_default_interface_default_interface_BF_bf_CntIM_CH1_enable_s    ),
    .default_interface_BF_bf_CntIM_CH1_out                ( TimerCSC_BF_bf_CntIM_CH1_out                                            ),
    .default_interface_BF_bf_ResIM_CH1_input              ( Top_CSC_default_interface_default_interface_BF_bf_ResIM_CH1_input_s     ),
    .default_interface_BF_bf_ResIM_CH1_enable             ( Top_CSC_default_interface_default_interface_BF_bf_ResIM_CH1_enable_s    ),
    .default_interface_BF_bf_ResIM_CH1_out                ( TimerCSC_BF_bf_ResIM_CH1_out                                            ),
    .default_interface_BF_bf_TimEn_CH1_input              ( Top_CSC_default_interface_default_interface_BF_bf_TimEn_CH1_input_s     ),
    .default_interface_BF_bf_TimEn_CH1_enable             ( Top_CSC_default_interface_default_interface_BF_bf_TimEn_CH1_enable_s    ),
    .default_interface_BF_bf_TimEn_CH1_out                ( TimerCSC_BF_bf_TimEn_CH1_out                                            ),
    .default_interface_BF_bf_ACTVAL_CH1_flipflop_in       ( TimerCSC_BF_bf_ACTVAL_CH1_flipflop_in                                   ),
    .default_interface_BF_bf_ACTVAL_CH1_flipflop_en       ( TimerCSC_BF_bf_ACTVAL_CH1_flipflop_en                                   ),
    .default_interface_BF_bf_ACTVAL_CH1_out               ( TimerCSC_BF_bf_ACTVAL_CH1_out                                           ),
    .default_interface_BF_bf_MAXVAL_CH1_flipflop_in       ( TimerCSC_BF_bf_MAXVAL_CH1_flipflop_in                                   ),
    .default_interface_BF_bf_MAXVAL_CH1_flipflop_en       ( TimerCSC_BF_bf_MAXVAL_CH1_flipflop_en                                   ),
    .default_interface_BF_bf_MAXVAL_CH1_out               ( TimerCSC_BF_bf_MAXVAL_CH1_out                                           ),
    .default_interface_BF_bf_CapIM0_CH1_input             ( Top_CSC_default_interface_default_interface_BF_bf_CapIM0_CH1_input_s    ),
    .default_interface_BF_bf_CapIM0_CH1_enable            ( Top_CSC_default_interface_default_interface_BF_bf_CapIM0_CH1_enable_s   ),
    .default_interface_BF_bf_CapIM0_CH1_out               ( TimerCSC_BF_bf_CapIM0_CH1_out                                           ),
    .default_interface_BF_bf_CCM0_CH1_input               ( Top_CSC_default_interface_default_interface_BF_bf_CCM0_CH1_input_s      ),
    .default_interface_BF_bf_CCM0_CH1_enable              ( Top_CSC_default_interface_default_interface_BF_bf_CCM0_CH1_enable_s     ),
    .default_interface_BF_bf_CCM0_CH1_out                 ( TimerCSC_BF_bf_CCM0_CH1_out                                             ),
    .default_interface_BF_bf_CCUVAL0_CH1_flipflop_in      ( TimerCSC_BF_bf_CCUVAL0_CH1_flipflop_in                                  ),
    .default_interface_BF_bf_CCUVAL0_CH1_flipflop_en      ( TimerCSC_BF_bf_CCUVAL0_CH1_flipflop_en                                  ),
    .default_interface_BF_bf_CCUVAL0_CH1_out              ( TimerCSC_BF_bf_CCUVAL0_CH1_out                                          ),
    .default_interface_BF_bf_CapIM1_CH1_input             ( Top_CSC_default_interface_default_interface_BF_bf_CapIM1_CH1_input_s    ),
    .default_interface_BF_bf_CapIM1_CH1_enable            ( Top_CSC_default_interface_default_interface_BF_bf_CapIM1_CH1_enable_s   ),
    .default_interface_BF_bf_CapIM1_CH1_out               ( TimerCSC_BF_bf_CapIM1_CH1_out                                           ),
    .default_interface_BF_bf_CCM1_CH1_input               ( Top_CSC_default_interface_default_interface_BF_bf_CCM1_CH1_input_s      ),
    .default_interface_BF_bf_CCM1_CH1_enable              ( Top_CSC_default_interface_default_interface_BF_bf_CCM1_CH1_enable_s     ),
    .default_interface_BF_bf_CCM1_CH1_out                 ( TimerCSC_BF_bf_CCM1_CH1_out                                             ),
    .default_interface_BF_bf_CCUVAL1_CH1_flipflop_in      ( TimerCSC_BF_bf_CCUVAL1_CH1_flipflop_in                                  ),
    .default_interface_BF_bf_CCUVAL1_CH1_flipflop_en      ( TimerCSC_BF_bf_CCUVAL1_CH1_flipflop_en                                  ),
    .default_interface_BF_bf_CCUVAL1_CH1_out              ( TimerCSC_BF_bf_CCUVAL1_CH1_out                                          ),
    .default_interface_BF_bf_CapIM2_CH1_input             ( Top_CSC_default_interface_default_interface_BF_bf_CapIM2_CH1_input_s    ),
    .default_interface_BF_bf_CapIM2_CH1_enable            ( Top_CSC_default_interface_default_interface_BF_bf_CapIM2_CH1_enable_s   ),
    .default_interface_BF_bf_CapIM2_CH1_out               ( TimerCSC_BF_bf_CapIM2_CH1_out                                           ),
    .default_interface_BF_bf_CCM2_CH1_input               ( Top_CSC_default_interface_default_interface_BF_bf_CCM2_CH1_input_s      ),
    .default_interface_BF_bf_CCM2_CH1_enable              ( Top_CSC_default_interface_default_interface_BF_bf_CCM2_CH1_enable_s     ),
    .default_interface_BF_bf_CCM2_CH1_out                 ( TimerCSC_BF_bf_CCM2_CH1_out                                             ),
    .default_interface_BF_bf_CCUVAL2_CH1_flipflop_in      ( TimerCSC_BF_bf_CCUVAL2_CH1_flipflop_in                                  ),
    .default_interface_BF_bf_CCUVAL2_CH1_flipflop_en      ( TimerCSC_BF_bf_CCUVAL2_CH1_flipflop_en                                  ),
    .default_interface_BF_bf_CCUVAL2_CH1_out              ( TimerCSC_BF_bf_CCUVAL2_CH1_out                                          ),
    .default_interface_BF_bf_CapIM3_CH1_input             ( Top_CSC_default_interface_default_interface_BF_bf_CapIM3_CH1_input_s    ),
    .default_interface_BF_bf_CapIM3_CH1_enable            ( Top_CSC_default_interface_default_interface_BF_bf_CapIM3_CH1_enable_s   ),
    .default_interface_BF_bf_CapIM3_CH1_out               ( TimerCSC_BF_bf_CapIM3_CH1_out                                           ),
    .default_interface_BF_bf_CCM3_CH1_input               ( Top_CSC_default_interface_default_interface_BF_bf_CCM3_CH1_input_s      ),
    .default_interface_BF_bf_CCM3_CH1_enable              ( Top_CSC_default_interface_default_interface_BF_bf_CCM3_CH1_enable_s     ),
    .default_interface_BF_bf_CCM3_CH1_out                 ( TimerCSC_BF_bf_CCM3_CH1_out                                             ),
    .default_interface_BF_bf_CCUVAL3_CH1_flipflop_in      ( TimerCSC_BF_bf_CCUVAL3_CH1_flipflop_in                                  ),
    .default_interface_BF_bf_CCUVAL3_CH1_flipflop_en      ( TimerCSC_BF_bf_CCUVAL3_CH1_flipflop_en                                  ),
    .default_interface_BF_bf_CCUVAL3_CH1_out              ( TimerCSC_BF_bf_CCUVAL3_CH1_out                                          ),
    .default_interface_BF_bf_CapIM4_CH1_input             ( Top_CSC_default_interface_default_interface_BF_bf_CapIM4_CH1_input_s    ),
    .default_interface_BF_bf_CapIM4_CH1_enable            ( Top_CSC_default_interface_default_interface_BF_bf_CapIM4_CH1_enable_s   ),
    .default_interface_BF_bf_CapIM4_CH1_out               ( TimerCSC_BF_bf_CapIM4_CH1_out                                           ),
    .default_interface_BF_bf_CCM4_CH1_input               ( Top_CSC_default_interface_default_interface_BF_bf_CCM4_CH1_input_s      ),
    .default_interface_BF_bf_CCM4_CH1_enable              ( Top_CSC_default_interface_default_interface_BF_bf_CCM4_CH1_enable_s     ),
    .default_interface_BF_bf_CCM4_CH1_out                 ( TimerCSC_BF_bf_CCM4_CH1_out                                             ),
    .default_interface_BF_bf_CCUVAL4_CH1_flipflop_in      ( TimerCSC_BF_bf_CCUVAL4_CH1_flipflop_in                                  ),
    .default_interface_BF_bf_CCUVAL4_CH1_flipflop_en      ( TimerCSC_BF_bf_CCUVAL4_CH1_flipflop_en                                  ),
    .default_interface_BF_bf_CCUVAL4_CH1_out              ( TimerCSC_BF_bf_CCUVAL4_CH1_out                                          ),
    .default_interface_BF_bf_CapIM5_CH1_input             ( Top_CSC_default_interface_default_interface_BF_bf_CapIM5_CH1_input_s    ),
    .default_interface_BF_bf_CapIM5_CH1_enable            ( Top_CSC_default_interface_default_interface_BF_bf_CapIM5_CH1_enable_s   ),
    .default_interface_BF_bf_CapIM5_CH1_out               ( TimerCSC_BF_bf_CapIM5_CH1_out                                           ),
    .default_interface_BF_bf_CCM5_CH1_input               ( Top_CSC_default_interface_default_interface_BF_bf_CCM5_CH1_input_s      ),
    .default_interface_BF_bf_CCM5_CH1_enable              ( Top_CSC_default_interface_default_interface_BF_bf_CCM5_CH1_enable_s     ),
    .default_interface_BF_bf_CCM5_CH1_out                 ( TimerCSC_BF_bf_CCM5_CH1_out                                             ),
    .default_interface_BF_bf_CCUVAL5_CH1_flipflop_in      ( TimerCSC_BF_bf_CCUVAL5_CH1_flipflop_in                                  ),
    .default_interface_BF_bf_CCUVAL5_CH1_flipflop_en      ( TimerCSC_BF_bf_CCUVAL5_CH1_flipflop_en                                  ),
    .default_interface_BF_bf_CCUVAL5_CH1_out              ( TimerCSC_BF_bf_CCUVAL5_CH1_out                                          )
);


endmodule

