/* ===============================================================
Copyright 2026, Infineon Technologies AG or an 
affiliate of Infineon Technologies AG.  All rights reserved.
 
This software, associated documentation and materials ("Software") is owned by
Infineon Technologies AG or one of its affiliates ("Infineon") and is 
protected by and subject to worldwide patent protection (United States and 
foreign), United States copyright laws and international treaty provisions. 
Therefore, you may use this Software only as provided in the license agreement
accompanying the software package from which you obtained this 
Software ("EULA"). If no EULA applies, then any reproduction, modification, 
translation, compilation, or representation of this Software is prohibited 
without the express written permission of Infineon.
 
Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF 
ANY KIND, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, 
NONINFRINGEMENT, IMPLIED WARRANTIES OF  MERCHANTABILITY AND
FITNESS FOR A PARTICULAR PURPOSE.  Infineon reserves the right to make
changes to the Software without notice. Infineon does not assume any liability
arising out of the application or use of the Software or any product or 
circuit described in the Software. Infineon does not authorize its products 
for use in any products where a malfunction or failure of the Infineon product 
may reasonably be expected to result in significant property damage, injury or
death ("High Risk Product").  By including Infineon 's product in a High Risk 
Product, the manufacturer of such system or application assumes all risk of 
such use and in doing so agrees to indemnify Infineon against all liability.

 ===============================================================
*/ 
// File : tc_soc_timer_timer_TimerChannel_0.sv 
// Author : tahiraga 
// Date : 15:07:02    25/09/2026 
// Revision :  
// =============================================================== 
// Description : 
/*
---- Auto Generated by MetaRTL , a MetaGen application
---- Contact: ParitoshKumar.Sinha@infineon.com
---- Contact: Yash.Ranjan@infineon.com
===============================================================
tc_soc_timer_timer_TimerChannel_0: Channel 0 of the Timer. Each channel is responsible for counting and signaling a particular event independently from other channels 
 */


module tc_soc_timer_timer_TimerChannel_0 (
    input logic  MAXVAL_flipflop_en,
    input logic  [31:0] MAXVAL_flipflop_in,
    output logic  [31:0] MAXVAL_flipflop_out,
    input logic  [31:0] MAXVAL_in,
    input logic  [2:0] ResIM,
    input logic  ExtRes,
    input logic  ExtCnt,
    input logic  [2:0] CntIM,
    input logic  ExtCap0,
    input logic  [2:0] CapIM0,
    input logic  ACTVAL_flipflop_en,
    input logic  [31:0] ACTVAL_flipflop_in,
    output logic  [31:0] ACTVAL_flipflop_out,
    input logic  [31:0] ACTVAL_in,
    output logic  [31:0] ACTVAL_out,
    output logic  ACTVAL_wr,
    input logic  TimEn,
    output logic  OvfInt,
    input logic  OvfIntRes,
    input logic  OvfIntEn,
    input logic  [2:0] CCM0,
    input logic  CCUVAL0_flipflop_en,
    input logic  [31:0] CCUVAL0_flipflop_in,
    output logic  [31:0] CCUVAL0_flipflop_out,
    input logic  [31:0] CCUVAL0_in,
    output logic  [31:0] CCUVAL0_out,
    output logic  CCUVAL0_wr,
    output logic  ExtComp0,
    input logic  HCLK_i,
    input logic  HRESET_n_i
);

logic   CapSync_0_Sync_s;
logic   CntSync_Sync_s;
logic   ResSync_Sync_s;
logic   [31:0] decrementer_Outp_s;
logic   ACTVALCU_AutoResCondition_s;
logic   ACTVALCU_MuxACTVAL_sel_s;


tc_soc_timer_cBitSynchronizer comp_CapSync_0(
    .Async      ( ExtCap0          ),
    .IM         ( CapIM0           ),
    .HCLK_i     ( HCLK_i           ),
    .HRESET_n_i ( HRESET_n_i       ),
    .Sync       ( CapSync_0_Sync_s )
);

tc_soc_timer_cCCUnit comp_CCU_0(
    .CCM                 ( CCM0                 ),
    .ACTVAL_in           ( ACTVAL_in            ),
    .ExtCap_trig         ( CapSync_0_Sync_s     ),
    .CCUVAL_flipflop_en  ( CCUVAL0_flipflop_en  ),
    .CCUVAL_flipflop_in  ( CCUVAL0_flipflop_in  ),
    .CCUVAL_in           ( CCUVAL0_in           ),
    .HCLK_i              ( HCLK_i               ),
    .HRESET_n_i          ( HRESET_n_i           ),
    .CCUVAL_flipflop_out ( CCUVAL0_flipflop_out ),
    .CCUVAL_out          ( CCUVAL0_out          ),
    .CCUVAL_wr           ( CCUVAL0_wr           ),
    .ExtComp             ( ExtComp0             )
);

tc_soc_timer_cInterruptControlUnit comp_InterruptCU(
    .OvfIntRes        ( OvfIntRes                   ),
    .OvfIntEn         ( OvfIntEn                    ),
    .AutoResCondition ( ACTVALCU_AutoResCondition_s ),
    .HCLK_i           ( HCLK_i                      ),
    .HRESET_n_i       ( HRESET_n_i                  ),
    .OvfInt           ( OvfInt                      )
);

tc_soc_timer_cBitSynchronizer comp_CntSync(
    .Async      ( ExtCnt         ),
    .IM         ( CntIM          ),
    .HCLK_i     ( HCLK_i         ),
    .HRESET_n_i ( HRESET_n_i     ),
    .Sync       ( CntSync_Sync_s )
);

tc_soc_timer_cBitSynchronizer comp_ResSync(
    .Async      ( ExtRes         ),
    .IM         ( ResIM          ),
    .HCLK_i     ( HCLK_i         ),
    .HRESET_n_i ( HRESET_n_i     ),
    .Sync       ( ResSync_Sync_s )
);

assign decrementer_Outp_s = ACTVAL_in - 32'b1;

tc_soc_timer_cACTVALControlUnit comp_ACTVALCU(
    .TimEn            ( TimEn                       ),
    .ResIM            ( ResIM                       ),
    .CntIM            ( CntIM                       ),
    .ExtRes_sync      ( ResSync_Sync_s              ),
    .ExtCnt_sync      ( CntSync_Sync_s              ),
    .ACTVAL           ( ACTVAL_in                   ),
    .AutoResCondition ( ACTVALCU_AutoResCondition_s ),
    .MuxACTVAL_sel    ( ACTVALCU_MuxACTVAL_sel_s    ),
    .ACTVAL_wr        ( ACTVAL_wr                   )
);

always_comb
begin
    ACTVAL_out = (ACTVALCU_MuxACTVAL_sel_s) ? MAXVAL_in : decrementer_Outp_s;
end

always_ff @(negedge HRESET_n_i, posedge HCLK_i)
begin
    if (HRESET_n_i == 1'b0) begin
        ACTVAL_flipflop_out <= 32'b0;
    end else begin
        if (ACTVAL_flipflop_en == 1'b1) begin
            ACTVAL_flipflop_out <= ACTVAL_flipflop_in;
        end
    end

end

always_ff @(negedge HRESET_n_i, posedge HCLK_i)
begin
    if (HRESET_n_i == 1'b0) begin
        MAXVAL_flipflop_out <= 32'b0;
    end else begin
        if (MAXVAL_flipflop_en == 1'b1) begin
            MAXVAL_flipflop_out <= MAXVAL_flipflop_in;
        end
    end

end


endmodule

