/* ===============================================================
Copyright 2026, Infineon Technologies AG or an 
affiliate of Infineon Technologies AG.  All rights reserved.
 
This software, associated documentation and materials ("Software") is owned by
Infineon Technologies AG or one of its affiliates ("Infineon") and is 
protected by and subject to worldwide patent protection (United States and 
foreign), United States copyright laws and international treaty provisions. 
Therefore, you may use this Software only as provided in the license agreement
accompanying the software package from which you obtained this 
Software ("EULA"). If no EULA applies, then any reproduction, modification, 
translation, compilation, or representation of this Software is prohibited 
without the express written permission of Infineon.
 
Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF 
ANY KIND, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, 
NONINFRINGEMENT, IMPLIED WARRANTIES OF  MERCHANTABILITY AND
FITNESS FOR A PARTICULAR PURPOSE.  Infineon reserves the right to make
changes to the Software without notice. Infineon does not assume any liability
arising out of the application or use of the Software or any product or 
circuit described in the Software. Infineon does not authorize its products 
for use in any products where a malfunction or failure of the Infineon product 
may reasonably be expected to result in significant property damage, injury or
death ("High Risk Product").  By including Infineon 's product in a High Risk 
Product, the manufacturer of such system or application assumes all risk of 
such use and in doing so agrees to indemnify Infineon against all liability.

 ===============================================================
*/ 
// File : tc_soc_timer_timer_TimerChannel_1_InterruptCU.sv 
// Author : tahiraga 
// Date : 15:07:02    25/09/2026 
// Revision :  
// =============================================================== 
// Description : 
/*
---- Auto Generated by MetaRTL , a MetaGen application
---- Contact: ParitoshKumar.Sinha@infineon.com
---- Contact: Yash.Ranjan@infineon.com
===============================================================
tc_soc_timer_timer_TimerChannel_1_InterruptCU: The interrupt control logic defines what happens if the counter is zero. 
 */


module tc_soc_timer_cInterruptControlUnit (
    output logic  OvfInt,
    input logic  OvfIntRes,
    input logic  OvfIntEn,
    input logic  AutoResCondition,
    input logic  HCLK_i,
    input logic  HRESET_n_i
);

logic   Ovf_TRIGGER_Outp_s;


assign Ovf_TRIGGER_Outp_s = AutoResCondition & OvfIntEn;

always_ff @(negedge HRESET_n_i, posedge HCLK_i)
begin
    if (HRESET_n_i == 1'b0) begin
        OvfInt <= 1'b0;
    end else begin
        if (OvfIntRes == 1'b1) begin
            OvfInt <= 1'b0;
        end else begin
            OvfInt <= Ovf_TRIGGER_Outp_s;
        end
    end

end


endmodule

