/* ===============================================================
Copyright 2026, Infineon Technologies AG or an 
affiliate of Infineon Technologies AG.  All rights reserved.
 
This software, associated documentation and materials ("Software") is owned by
Infineon Technologies AG or one of its affiliates ("Infineon") and is 
protected by and subject to worldwide patent protection (United States and 
foreign), United States copyright laws and international treaty provisions. 
Therefore, you may use this Software only as provided in the license agreement
accompanying the software package from which you obtained this 
Software ("EULA"). If no EULA applies, then any reproduction, modification, 
translation, compilation, or representation of this Software is prohibited 
without the express written permission of Infineon.
 
Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF 
ANY KIND, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, 
NONINFRINGEMENT, IMPLIED WARRANTIES OF  MERCHANTABILITY AND
FITNESS FOR A PARTICULAR PURPOSE.  Infineon reserves the right to make
changes to the Software without notice. Infineon does not assume any liability
arising out of the application or use of the Software or any product or 
circuit described in the Software. Infineon does not authorize its products 
for use in any products where a malfunction or failure of the Infineon product 
may reasonably be expected to result in significant property damage, injury or
death ("High Risk Product").  By including Infineon 's product in a High Risk 
Product, the manufacturer of such system or application assumes all risk of 
such use and in doing so agrees to indemnify Infineon against all liability.

 ===============================================================
*/ 
// File : tc_soc_timer_Reg_IF_Top_CSC_Top_CSC_default_interface_Top_CSC_default_interface_ReadCircuit.sv 
// Author : tahiraga 
// Date : 15:07:01    25/09/2026 
// Revision :  
// =============================================================== 
// Description : 
/*
---- Auto Generated by MetaRTL , a MetaGen application
---- Contact: ParitoshKumar.Sinha@infineon.com
---- Contact: Yash.Ranjan@infineon.com
===============================================================
*/


module tc_soc_timer_Reg_IF_Top_CSC_Top_CSC_default_interface_Top_CSC_default_interface_ReadCircuit (
    output logic  [31:0] default_interface_RC_data_out,
    input logic  default_interface_RC_rd_en,
    input logic  [4:0] default_interface_RC_Shifting_Value_Mux_out,
    input logic  [31:0] default_interface_RC_Masking_Mux_out,
    input logic  Port_of_Reg_bf_OvfIntEn_CH0,
    output logic  default_interface_RC_bf_OvfIntEn_CH0_out,
    input logic  [2:0] Port_of_Reg_bf_CntIM_CH0,
    output logic  [2:0] default_interface_RC_bf_CntIM_CH0_out,
    input logic  [2:0] Port_of_Reg_bf_ResIM_CH0,
    output logic  [2:0] default_interface_RC_bf_ResIM_CH0_out,
    input logic  Port_of_Reg_bf_TimEn_CH0,
    output logic  default_interface_RC_bf_TimEn_CH0_out,
    input logic  Address_EQ_Port_CH0_CTRLSTAT,
    input logic  [31:0] Port_of_BF_bf_ACTVAL_CH0_flipflop_out,
    output logic  [31:0] default_interface_RC_bf_ACTVAL_CH0_out,
    input logic  Address_EQ_Port_CH0_ACTVAL,
    input logic  [31:0] Port_of_BF_bf_MAXVAL_CH0_flipflop_out,
    output logic  [31:0] default_interface_RC_bf_MAXVAL_CH0_out,
    input logic  Address_EQ_Port_CH0_MAXVAL,
    input logic  [2:0] Port_of_Reg_bf_CapIM0_CH0,
    output logic  [2:0] default_interface_RC_bf_CapIM0_CH0_out,
    input logic  [2:0] Port_of_Reg_bf_CCM0_CH0,
    output logic  [2:0] default_interface_RC_bf_CCM0_CH0_out,
    input logic  Address_EQ_Port_CH0_CCUCTRL0,
    input logic  [31:0] Port_of_BF_bf_CCUVAL0_CH0_flipflop_out,
    output logic  [31:0] default_interface_RC_bf_CCUVAL0_CH0_out,
    input logic  Address_EQ_Port_CH0_CCUVAL0,
    input logic  Port_of_Reg_bf_OvfIntEn_CH1,
    output logic  default_interface_RC_bf_OvfIntEn_CH1_out,
    input logic  [2:0] Port_of_Reg_bf_CntIM_CH1,
    output logic  [2:0] default_interface_RC_bf_CntIM_CH1_out,
    input logic  [2:0] Port_of_Reg_bf_ResIM_CH1,
    output logic  [2:0] default_interface_RC_bf_ResIM_CH1_out,
    input logic  Port_of_Reg_bf_TimEn_CH1,
    output logic  default_interface_RC_bf_TimEn_CH1_out,
    input logic  Address_EQ_Port_CH1_CTRLSTAT,
    input logic  [31:0] Port_of_BF_bf_ACTVAL_CH1_flipflop_out,
    output logic  [31:0] default_interface_RC_bf_ACTVAL_CH1_out,
    input logic  Address_EQ_Port_CH1_ACTVAL,
    input logic  [31:0] Port_of_BF_bf_MAXVAL_CH1_flipflop_out,
    output logic  [31:0] default_interface_RC_bf_MAXVAL_CH1_out,
    input logic  Address_EQ_Port_CH1_MAXVAL,
    input logic  [2:0] Port_of_Reg_bf_CapIM0_CH1,
    output logic  [2:0] default_interface_RC_bf_CapIM0_CH1_out,
    input logic  [2:0] Port_of_Reg_bf_CCM0_CH1,
    output logic  [2:0] default_interface_RC_bf_CCM0_CH1_out,
    input logic  Address_EQ_Port_CH1_CCUCTRL0,
    input logic  [31:0] Port_of_BF_bf_CCUVAL0_CH1_flipflop_out,
    output logic  [31:0] default_interface_RC_bf_CCUVAL0_CH1_out,
    input logic  Address_EQ_Port_CH1_CCUVAL0,
    input logic  [2:0] Port_of_Reg_bf_CapIM1_CH1,
    output logic  [2:0] default_interface_RC_bf_CapIM1_CH1_out,
    input logic  [2:0] Port_of_Reg_bf_CCM1_CH1,
    output logic  [2:0] default_interface_RC_bf_CCM1_CH1_out,
    input logic  Address_EQ_Port_CH1_CCUCTRL1,
    input logic  [31:0] Port_of_BF_bf_CCUVAL1_CH1_flipflop_out,
    output logic  [31:0] default_interface_RC_bf_CCUVAL1_CH1_out,
    input logic  Address_EQ_Port_CH1_CCUVAL1,
    input logic  [2:0] Port_of_Reg_bf_CapIM2_CH1,
    output logic  [2:0] default_interface_RC_bf_CapIM2_CH1_out,
    input logic  [2:0] Port_of_Reg_bf_CCM2_CH1,
    output logic  [2:0] default_interface_RC_bf_CCM2_CH1_out,
    input logic  Address_EQ_Port_CH1_CCUCTRL2,
    input logic  [31:0] Port_of_BF_bf_CCUVAL2_CH1_flipflop_out,
    output logic  [31:0] default_interface_RC_bf_CCUVAL2_CH1_out,
    input logic  Address_EQ_Port_CH1_CCUVAL2,
    input logic  [2:0] Port_of_Reg_bf_CapIM3_CH1,
    output logic  [2:0] default_interface_RC_bf_CapIM3_CH1_out,
    input logic  [2:0] Port_of_Reg_bf_CCM3_CH1,
    output logic  [2:0] default_interface_RC_bf_CCM3_CH1_out,
    input logic  Address_EQ_Port_CH1_CCUCTRL3,
    input logic  [31:0] Port_of_BF_bf_CCUVAL3_CH1_flipflop_out,
    output logic  [31:0] default_interface_RC_bf_CCUVAL3_CH1_out,
    input logic  Address_EQ_Port_CH1_CCUVAL3,
    input logic  [2:0] Port_of_Reg_bf_CapIM4_CH1,
    output logic  [2:0] default_interface_RC_bf_CapIM4_CH1_out,
    input logic  [2:0] Port_of_Reg_bf_CCM4_CH1,
    output logic  [2:0] default_interface_RC_bf_CCM4_CH1_out,
    input logic  Address_EQ_Port_CH1_CCUCTRL4,
    input logic  [31:0] Port_of_BF_bf_CCUVAL4_CH1_flipflop_out,
    output logic  [31:0] default_interface_RC_bf_CCUVAL4_CH1_out,
    input logic  Address_EQ_Port_CH1_CCUVAL4,
    input logic  [2:0] Port_of_Reg_bf_CapIM5_CH1,
    output logic  [2:0] default_interface_RC_bf_CapIM5_CH1_out,
    input logic  [2:0] Port_of_Reg_bf_CCM5_CH1,
    output logic  [2:0] default_interface_RC_bf_CCM5_CH1_out,
    input logic  Address_EQ_Port_CH1_CCUCTRL5,
    input logic  [31:0] Port_of_BF_bf_CCUVAL5_CH1_flipflop_out,
    output logic  [31:0] default_interface_RC_bf_CCUVAL5_CH1_out,
    input logic  Address_EQ_Port_CH1_CCUVAL5
);

logic   [31:0] CH1_CCUVAL5_Outp_s;
logic   [31:0] CH1_CCUCTRL5_Outp_s;
logic   [31:0] CH1_CCUVAL4_Outp_s;
logic   [31:0] CH1_CCUCTRL4_Outp_s;
logic   [31:0] CH1_CCUVAL3_Outp_s;
logic   [31:0] CH1_CCUCTRL3_Outp_s;
logic   [31:0] CH1_CCUVAL2_Outp_s;
logic   [31:0] CH1_CCUCTRL2_Outp_s;
logic   [31:0] CH1_CCUVAL1_Outp_s;
logic   [31:0] CH1_CCUCTRL1_Outp_s;
logic   [31:0] CH1_CCUVAL0_Outp_s;
logic   [31:0] CH1_CCUCTRL0_Outp_s;
logic   [31:0] CH1_MAXVAL_Outp_s;
logic   [31:0] CH1_ACTVAL_Outp_s;
logic   [31:0] CH1_CTRLSTAT_Outp_s;
logic   [31:0] CH0_CCUVAL0_Outp_s;
logic   [31:0] CH0_CCUCTRL0_Outp_s;
logic   [31:0] CH0_MAXVAL_Outp_s;
logic   [31:0] CH0_ACTVAL_Outp_s;
logic   [31:0] CH0_CTRLSTAT_Outp_s;
logic  signed  [31:0] default_interface_Shifting_Outp_s;

logic   [31:0] Mux19_Outp_s;
logic   [31:0] Mux18_Outp_s;
logic   [31:0] Mux17_Outp_s;
logic   [31:0] Mux16_Outp_s;
logic   [31:0] Mux15_Outp_s;
logic   [31:0] Mux14_Outp_s;
logic   [31:0] Mux13_Outp_s;
logic   [31:0] Mux12_Outp_s;
logic   [31:0] Mux11_Outp_s;
logic   [31:0] Mux10_Outp_s;
logic   [31:0] Mux09_Outp_s;
logic   [31:0] Mux08_Outp_s;
logic   [31:0] Mux07_Outp_s;
logic   [31:0] Mux06_Outp_s;
logic   [31:0] Mux05_Outp_s;
logic   [31:0] Mux04_Outp_s;
logic   [31:0] Mux03_Outp_s;
logic   [31:0] Mux02_Outp_s;
logic   [31:0] Mux01_Outp_s;
logic   [31:0] Mux00_Outp_s;
logic   [31:0] default_interface_Reading_MUX_Outp_s;

assign CH1_CCUVAL5_Outp_s = {Port_of_BF_bf_CCUVAL5_CH1_flipflop_out};

assign CH1_CCUCTRL5_Outp_s = {26'b0,Port_of_Reg_bf_CapIM5_CH1,Port_of_Reg_bf_CCM5_CH1};

assign CH1_CCUVAL4_Outp_s = {Port_of_BF_bf_CCUVAL4_CH1_flipflop_out};

assign CH1_CCUCTRL4_Outp_s = {26'b0,Port_of_Reg_bf_CapIM4_CH1,Port_of_Reg_bf_CCM4_CH1};

assign CH1_CCUVAL3_Outp_s = {Port_of_BF_bf_CCUVAL3_CH1_flipflop_out};

assign CH1_CCUCTRL3_Outp_s = {26'b0,Port_of_Reg_bf_CapIM3_CH1,Port_of_Reg_bf_CCM3_CH1};

assign CH1_CCUVAL2_Outp_s = {Port_of_BF_bf_CCUVAL2_CH1_flipflop_out};

assign CH1_CCUCTRL2_Outp_s = {26'b0,Port_of_Reg_bf_CapIM2_CH1,Port_of_Reg_bf_CCM2_CH1};

assign CH1_CCUVAL1_Outp_s = {Port_of_BF_bf_CCUVAL1_CH1_flipflop_out};

assign CH1_CCUCTRL1_Outp_s = {26'b0,Port_of_Reg_bf_CapIM1_CH1,Port_of_Reg_bf_CCM1_CH1};

assign CH1_CCUVAL0_Outp_s = {Port_of_BF_bf_CCUVAL0_CH1_flipflop_out};

assign CH1_CCUCTRL0_Outp_s = {26'b0,Port_of_Reg_bf_CapIM0_CH1,Port_of_Reg_bf_CCM0_CH1};

assign CH1_MAXVAL_Outp_s = {Port_of_BF_bf_MAXVAL_CH1_flipflop_out};

assign CH1_ACTVAL_Outp_s = {Port_of_BF_bf_ACTVAL_CH1_flipflop_out};

assign CH1_CTRLSTAT_Outp_s = {24'b0,Port_of_Reg_bf_OvfIntEn_CH1,Port_of_Reg_bf_CntIM_CH1,Port_of_Reg_bf_ResIM_CH1,Port_of_Reg_bf_TimEn_CH1};

assign CH0_CCUVAL0_Outp_s = {Port_of_BF_bf_CCUVAL0_CH0_flipflop_out};

assign CH0_CCUCTRL0_Outp_s = {26'b0,Port_of_Reg_bf_CapIM0_CH0,Port_of_Reg_bf_CCM0_CH0};

assign CH0_MAXVAL_Outp_s = {Port_of_BF_bf_MAXVAL_CH0_flipflop_out};

assign CH0_ACTVAL_Outp_s = {Port_of_BF_bf_ACTVAL_CH0_flipflop_out};

assign CH0_CTRLSTAT_Outp_s = {24'b0,Port_of_Reg_bf_OvfIntEn_CH0,Port_of_Reg_bf_CntIM_CH0,Port_of_Reg_bf_ResIM_CH0,Port_of_Reg_bf_TimEn_CH0};

always_comb
begin
    case (Address_EQ_Port_CH1_CCUVAL5)
        1'b1 : Mux19_Outp_s = CH1_CCUVAL5_Outp_s;
        default : Mux19_Outp_s = 32'b0;
    endcase

end

always_comb
begin
    case (Address_EQ_Port_CH1_CCUCTRL5)
        1'b1 : Mux18_Outp_s = CH1_CCUCTRL5_Outp_s;
        default : Mux18_Outp_s = 32'b0;
    endcase

end

always_comb
begin
    case (Address_EQ_Port_CH1_CCUVAL4)
        1'b1 : Mux17_Outp_s = CH1_CCUVAL4_Outp_s;
        default : Mux17_Outp_s = 32'b0;
    endcase

end

always_comb
begin
    case (Address_EQ_Port_CH1_CCUCTRL4)
        1'b1 : Mux16_Outp_s = CH1_CCUCTRL4_Outp_s;
        default : Mux16_Outp_s = 32'b0;
    endcase

end

always_comb
begin
    case (Address_EQ_Port_CH1_CCUVAL3)
        1'b1 : Mux15_Outp_s = CH1_CCUVAL3_Outp_s;
        default : Mux15_Outp_s = 32'b0;
    endcase

end

always_comb
begin
    case (Address_EQ_Port_CH1_CCUCTRL3)
        1'b1 : Mux14_Outp_s = CH1_CCUCTRL3_Outp_s;
        default : Mux14_Outp_s = 32'b0;
    endcase

end

always_comb
begin
    case (Address_EQ_Port_CH1_CCUVAL2)
        1'b1 : Mux13_Outp_s = CH1_CCUVAL2_Outp_s;
        default : Mux13_Outp_s = 32'b0;
    endcase

end

always_comb
begin
    case (Address_EQ_Port_CH1_CCUCTRL2)
        1'b1 : Mux12_Outp_s = CH1_CCUCTRL2_Outp_s;
        default : Mux12_Outp_s = 32'b0;
    endcase

end

always_comb
begin
    case (Address_EQ_Port_CH1_CCUVAL1)
        1'b1 : Mux11_Outp_s = CH1_CCUVAL1_Outp_s;
        default : Mux11_Outp_s = 32'b0;
    endcase

end

always_comb
begin
    case (Address_EQ_Port_CH1_CCUCTRL1)
        1'b1 : Mux10_Outp_s = CH1_CCUCTRL1_Outp_s;
        default : Mux10_Outp_s = 32'b0;
    endcase

end

always_comb
begin
    case (Address_EQ_Port_CH1_CCUVAL0)
        1'b1 : Mux09_Outp_s = CH1_CCUVAL0_Outp_s;
        default : Mux09_Outp_s = 32'b0;
    endcase

end

always_comb
begin
    case (Address_EQ_Port_CH1_CCUCTRL0)
        1'b1 : Mux08_Outp_s = CH1_CCUCTRL0_Outp_s;
        default : Mux08_Outp_s = 32'b0;
    endcase

end

always_comb
begin
    case (Address_EQ_Port_CH1_MAXVAL)
        1'b1 : Mux07_Outp_s = CH1_MAXVAL_Outp_s;
        default : Mux07_Outp_s = 32'b0;
    endcase

end

always_comb
begin
    case (Address_EQ_Port_CH1_ACTVAL)
        1'b1 : Mux06_Outp_s = CH1_ACTVAL_Outp_s;
        default : Mux06_Outp_s = 32'b0;
    endcase

end

always_comb
begin
    case (Address_EQ_Port_CH1_CTRLSTAT)
        1'b1 : Mux05_Outp_s = CH1_CTRLSTAT_Outp_s;
        default : Mux05_Outp_s = 32'b0;
    endcase

end

always_comb
begin
    case (Address_EQ_Port_CH0_CCUVAL0)
        1'b1 : Mux04_Outp_s = CH0_CCUVAL0_Outp_s;
        default : Mux04_Outp_s = 32'b0;
    endcase

end

always_comb
begin
    case (Address_EQ_Port_CH0_CCUCTRL0)
        1'b1 : Mux03_Outp_s = CH0_CCUCTRL0_Outp_s;
        default : Mux03_Outp_s = 32'b0;
    endcase

end

always_comb
begin
    case (Address_EQ_Port_CH0_MAXVAL)
        1'b1 : Mux02_Outp_s = CH0_MAXVAL_Outp_s;
        default : Mux02_Outp_s = 32'b0;
    endcase

end

always_comb
begin
    case (Address_EQ_Port_CH0_ACTVAL)
        1'b1 : Mux01_Outp_s = CH0_ACTVAL_Outp_s;
        default : Mux01_Outp_s = 32'b0;
    endcase

end

always_comb
begin
    case (Address_EQ_Port_CH0_CTRLSTAT)
        1'b1 : Mux00_Outp_s = CH0_CTRLSTAT_Outp_s;
        default : Mux00_Outp_s = 32'b0;
    endcase

end

always_comb
begin
    case (default_interface_RC_rd_en)
        1'b1 : default_interface_Reading_MUX_Outp_s = (Mux00_Outp_s | Mux01_Outp_s | Mux02_Outp_s | Mux03_Outp_s | Mux04_Outp_s | Mux05_Outp_s | Mux06_Outp_s | Mux07_Outp_s | Mux08_Outp_s | Mux09_Outp_s | Mux10_Outp_s | Mux11_Outp_s | Mux12_Outp_s | Mux13_Outp_s | Mux14_Outp_s | Mux15_Outp_s | Mux16_Outp_s | Mux17_Outp_s | Mux18_Outp_s | Mux19_Outp_s);
        default : default_interface_Reading_MUX_Outp_s = 32'b0;
    endcase

end

assign default_interface_Shifting_Outp_s = $signed(default_interface_Reading_MUX_Outp_s) >>> default_interface_RC_Shifting_Value_Mux_out;

assign default_interface_RC_data_out = default_interface_Shifting_Outp_s & default_interface_RC_Masking_Mux_out;

assign default_interface_RC_bf_OvfIntEn_CH0_out = Port_of_Reg_bf_OvfIntEn_CH0;
assign default_interface_RC_bf_CntIM_CH0_out = Port_of_Reg_bf_CntIM_CH0;
assign default_interface_RC_bf_ResIM_CH0_out = Port_of_Reg_bf_ResIM_CH0;
assign default_interface_RC_bf_TimEn_CH0_out = Port_of_Reg_bf_TimEn_CH0;
assign default_interface_RC_bf_ACTVAL_CH0_out = Port_of_BF_bf_ACTVAL_CH0_flipflop_out;
assign default_interface_RC_bf_MAXVAL_CH0_out = Port_of_BF_bf_MAXVAL_CH0_flipflop_out;
assign default_interface_RC_bf_CapIM0_CH0_out = Port_of_Reg_bf_CapIM0_CH0;
assign default_interface_RC_bf_CCM0_CH0_out = Port_of_Reg_bf_CCM0_CH0;
assign default_interface_RC_bf_CCUVAL0_CH0_out = Port_of_BF_bf_CCUVAL0_CH0_flipflop_out;
assign default_interface_RC_bf_OvfIntEn_CH1_out = Port_of_Reg_bf_OvfIntEn_CH1;
assign default_interface_RC_bf_CntIM_CH1_out = Port_of_Reg_bf_CntIM_CH1;
assign default_interface_RC_bf_ResIM_CH1_out = Port_of_Reg_bf_ResIM_CH1;
assign default_interface_RC_bf_TimEn_CH1_out = Port_of_Reg_bf_TimEn_CH1;
assign default_interface_RC_bf_ACTVAL_CH1_out = Port_of_BF_bf_ACTVAL_CH1_flipflop_out;
assign default_interface_RC_bf_MAXVAL_CH1_out = Port_of_BF_bf_MAXVAL_CH1_flipflop_out;
assign default_interface_RC_bf_CapIM0_CH1_out = Port_of_Reg_bf_CapIM0_CH1;
assign default_interface_RC_bf_CCM0_CH1_out = Port_of_Reg_bf_CCM0_CH1;
assign default_interface_RC_bf_CCUVAL0_CH1_out = Port_of_BF_bf_CCUVAL0_CH1_flipflop_out;
assign default_interface_RC_bf_CapIM1_CH1_out = Port_of_Reg_bf_CapIM1_CH1;
assign default_interface_RC_bf_CCM1_CH1_out = Port_of_Reg_bf_CCM1_CH1;
assign default_interface_RC_bf_CCUVAL1_CH1_out = Port_of_BF_bf_CCUVAL1_CH1_flipflop_out;
assign default_interface_RC_bf_CapIM2_CH1_out = Port_of_Reg_bf_CapIM2_CH1;
assign default_interface_RC_bf_CCM2_CH1_out = Port_of_Reg_bf_CCM2_CH1;
assign default_interface_RC_bf_CCUVAL2_CH1_out = Port_of_BF_bf_CCUVAL2_CH1_flipflop_out;
assign default_interface_RC_bf_CapIM3_CH1_out = Port_of_Reg_bf_CapIM3_CH1;
assign default_interface_RC_bf_CCM3_CH1_out = Port_of_Reg_bf_CCM3_CH1;
assign default_interface_RC_bf_CCUVAL3_CH1_out = Port_of_BF_bf_CCUVAL3_CH1_flipflop_out;
assign default_interface_RC_bf_CapIM4_CH1_out = Port_of_Reg_bf_CapIM4_CH1;
assign default_interface_RC_bf_CCM4_CH1_out = Port_of_Reg_bf_CCM4_CH1;
assign default_interface_RC_bf_CCUVAL4_CH1_out = Port_of_BF_bf_CCUVAL4_CH1_flipflop_out;
assign default_interface_RC_bf_CapIM5_CH1_out = Port_of_Reg_bf_CapIM5_CH1;
assign default_interface_RC_bf_CCM5_CH1_out = Port_of_Reg_bf_CCM5_CH1;
assign default_interface_RC_bf_CCUVAL5_CH1_out = Port_of_BF_bf_CCUVAL5_CH1_flipflop_out;

endmodule

