/* ===============================================================
Copyright 2026, Infineon Technologies AG or an 
affiliate of Infineon Technologies AG.  All rights reserved.
 
This software, associated documentation and materials ("Software") is owned by
Infineon Technologies AG or one of its affiliates ("Infineon") and is 
protected by and subject to worldwide patent protection (United States and 
foreign), United States copyright laws and international treaty provisions. 
Therefore, you may use this Software only as provided in the license agreement
accompanying the software package from which you obtained this 
Software ("EULA"). If no EULA applies, then any reproduction, modification, 
translation, compilation, or representation of this Software is prohibited 
without the express written permission of Infineon.
 
Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF 
ANY KIND, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, 
NONINFRINGEMENT, IMPLIED WARRANTIES OF  MERCHANTABILITY AND
FITNESS FOR A PARTICULAR PURPOSE.  Infineon reserves the right to make
changes to the Software without notice. Infineon does not assume any liability
arising out of the application or use of the Software or any product or 
circuit described in the Software. Infineon does not authorize its products 
for use in any products where a malfunction or failure of the Infineon product 
may reasonably be expected to result in significant property damage, injury or
death ("High Risk Product").  By including Infineon 's product in a High Risk 
Product, the manufacturer of such system or application assumes all risk of 
such use and in doing so agrees to indemnify Infineon against all liability.

 ===============================================================
*/ 
// File : tc_soc_timer_Reg_IF.sv 
// Author : tahiraga 
// Date : 15:07:02    25/09/2026 
// Revision :  
// =============================================================== 
// Description : 
/*
---- Auto Generated by MetaRTL , a MetaGen application
---- Contact: ParitoshKumar.Sinha@infineon.com
---- Contact: Yash.Ranjan@infineon.com
===============================================================
*/


module tc_soc_timer_Reg_IF (
    input logic  [31:0] SX_AHB_HADDR,
    input logic  [31:0] SX_AHB_HWDATA,
    input logic  [2:0] SX_AHB_HBURST,
    input logic  SX_AHB_HMASTLOCK,
    input logic  [3:0] SX_AHB_HPROT,
    input logic  [2:0] SX_AHB_HSIZE,
    input logic  [1:0] SX_AHB_HTRANS,
    input logic  SX_AHB_HWRITE,
    input logic  SX_AHB_HSEL,
    input logic  SX_AHB_HREADY,
    output logic  [31:0] SX_AHB_HRDATA,
    output logic  SX_AHB_HREADYOUT,
    output logic  SX_AHB_HRESP,
    output logic  TimerCSC_BF_bf_TimEn_CH0_out,
    output logic  [2:0] TimerCSC_BF_bf_ResIM_CH0_out,
    output logic  [2:0] TimerCSC_BF_bf_CntIM_CH0_out,
    output logic  TimerCSC_BF_bf_OvfIntEn_CH0_out,
    input logic  [31:0] TimerCSC_BF_bf_ACTVAL_CH0_in,
    input logic  TimerCSC_BF_bf_ACTVAL_CH0_peripheral_wr_en,
    output logic  [31:0] TimerCSC_BF_bf_ACTVAL_CH0_out,
    input logic  [31:0] TimerCSC_BF_bf_ACTVAL_CH0_flipflop_out,
    output logic  [31:0] TimerCSC_BF_bf_ACTVAL_CH0_flipflop_in,
    output logic  TimerCSC_BF_bf_ACTVAL_CH0_flipflop_en,
    output logic  [31:0] TimerCSC_BF_bf_MAXVAL_CH0_out,
    input logic  [31:0] TimerCSC_BF_bf_MAXVAL_CH0_flipflop_out,
    output logic  [31:0] TimerCSC_BF_bf_MAXVAL_CH0_flipflop_in,
    output logic  TimerCSC_BF_bf_MAXVAL_CH0_flipflop_en,
    output logic  [2:0] TimerCSC_BF_bf_CCM0_CH0_out,
    output logic  [2:0] TimerCSC_BF_bf_CapIM0_CH0_out,
    input logic  [31:0] TimerCSC_BF_bf_CCUVAL0_CH0_in,
    input logic  TimerCSC_BF_bf_CCUVAL0_CH0_peripheral_wr_en,
    output logic  [31:0] TimerCSC_BF_bf_CCUVAL0_CH0_out,
    input logic  [31:0] TimerCSC_BF_bf_CCUVAL0_CH0_flipflop_out,
    output logic  [31:0] TimerCSC_BF_bf_CCUVAL0_CH0_flipflop_in,
    output logic  TimerCSC_BF_bf_CCUVAL0_CH0_flipflop_en,
    output logic  TimerCSC_BF_bf_TimEn_CH1_out,
    output logic  [2:0] TimerCSC_BF_bf_ResIM_CH1_out,
    output logic  [2:0] TimerCSC_BF_bf_CntIM_CH1_out,
    output logic  TimerCSC_BF_bf_OvfIntEn_CH1_out,
    input logic  [31:0] TimerCSC_BF_bf_ACTVAL_CH1_in,
    input logic  TimerCSC_BF_bf_ACTVAL_CH1_peripheral_wr_en,
    output logic  [31:0] TimerCSC_BF_bf_ACTVAL_CH1_out,
    input logic  [31:0] TimerCSC_BF_bf_ACTVAL_CH1_flipflop_out,
    output logic  [31:0] TimerCSC_BF_bf_ACTVAL_CH1_flipflop_in,
    output logic  TimerCSC_BF_bf_ACTVAL_CH1_flipflop_en,
    output logic  [31:0] TimerCSC_BF_bf_MAXVAL_CH1_out,
    input logic  [31:0] TimerCSC_BF_bf_MAXVAL_CH1_flipflop_out,
    output logic  [31:0] TimerCSC_BF_bf_MAXVAL_CH1_flipflop_in,
    output logic  TimerCSC_BF_bf_MAXVAL_CH1_flipflop_en,
    output logic  [2:0] TimerCSC_BF_bf_CCM0_CH1_out,
    output logic  [2:0] TimerCSC_BF_bf_CapIM0_CH1_out,
    input logic  [31:0] TimerCSC_BF_bf_CCUVAL0_CH1_in,
    input logic  TimerCSC_BF_bf_CCUVAL0_CH1_peripheral_wr_en,
    output logic  [31:0] TimerCSC_BF_bf_CCUVAL0_CH1_out,
    input logic  [31:0] TimerCSC_BF_bf_CCUVAL0_CH1_flipflop_out,
    output logic  [31:0] TimerCSC_BF_bf_CCUVAL0_CH1_flipflop_in,
    output logic  TimerCSC_BF_bf_CCUVAL0_CH1_flipflop_en,
    output logic  [2:0] TimerCSC_BF_bf_CCM1_CH1_out,
    output logic  [2:0] TimerCSC_BF_bf_CapIM1_CH1_out,
    input logic  [31:0] TimerCSC_BF_bf_CCUVAL1_CH1_in,
    input logic  TimerCSC_BF_bf_CCUVAL1_CH1_peripheral_wr_en,
    output logic  [31:0] TimerCSC_BF_bf_CCUVAL1_CH1_out,
    input logic  [31:0] TimerCSC_BF_bf_CCUVAL1_CH1_flipflop_out,
    output logic  [31:0] TimerCSC_BF_bf_CCUVAL1_CH1_flipflop_in,
    output logic  TimerCSC_BF_bf_CCUVAL1_CH1_flipflop_en,
    output logic  [2:0] TimerCSC_BF_bf_CCM2_CH1_out,
    output logic  [2:0] TimerCSC_BF_bf_CapIM2_CH1_out,
    input logic  [31:0] TimerCSC_BF_bf_CCUVAL2_CH1_in,
    input logic  TimerCSC_BF_bf_CCUVAL2_CH1_peripheral_wr_en,
    output logic  [31:0] TimerCSC_BF_bf_CCUVAL2_CH1_out,
    input logic  [31:0] TimerCSC_BF_bf_CCUVAL2_CH1_flipflop_out,
    output logic  [31:0] TimerCSC_BF_bf_CCUVAL2_CH1_flipflop_in,
    output logic  TimerCSC_BF_bf_CCUVAL2_CH1_flipflop_en,
    output logic  [2:0] TimerCSC_BF_bf_CCM3_CH1_out,
    output logic  [2:0] TimerCSC_BF_bf_CapIM3_CH1_out,
    input logic  [31:0] TimerCSC_BF_bf_CCUVAL3_CH1_in,
    input logic  TimerCSC_BF_bf_CCUVAL3_CH1_peripheral_wr_en,
    output logic  [31:0] TimerCSC_BF_bf_CCUVAL3_CH1_out,
    input logic  [31:0] TimerCSC_BF_bf_CCUVAL3_CH1_flipflop_out,
    output logic  [31:0] TimerCSC_BF_bf_CCUVAL3_CH1_flipflop_in,
    output logic  TimerCSC_BF_bf_CCUVAL3_CH1_flipflop_en,
    output logic  [2:0] TimerCSC_BF_bf_CCM4_CH1_out,
    output logic  [2:0] TimerCSC_BF_bf_CapIM4_CH1_out,
    input logic  [31:0] TimerCSC_BF_bf_CCUVAL4_CH1_in,
    input logic  TimerCSC_BF_bf_CCUVAL4_CH1_peripheral_wr_en,
    output logic  [31:0] TimerCSC_BF_bf_CCUVAL4_CH1_out,
    input logic  [31:0] TimerCSC_BF_bf_CCUVAL4_CH1_flipflop_out,
    output logic  [31:0] TimerCSC_BF_bf_CCUVAL4_CH1_flipflop_in,
    output logic  TimerCSC_BF_bf_CCUVAL4_CH1_flipflop_en,
    output logic  [2:0] TimerCSC_BF_bf_CCM5_CH1_out,
    output logic  [2:0] TimerCSC_BF_bf_CapIM5_CH1_out,
    input logic  [31:0] TimerCSC_BF_bf_CCUVAL5_CH1_in,
    input logic  TimerCSC_BF_bf_CCUVAL5_CH1_peripheral_wr_en,
    output logic  [31:0] TimerCSC_BF_bf_CCUVAL5_CH1_out,
    input logic  [31:0] TimerCSC_BF_bf_CCUVAL5_CH1_flipflop_out,
    output logic  [31:0] TimerCSC_BF_bf_CCUVAL5_CH1_flipflop_in,
    output logic  TimerCSC_BF_bf_CCUVAL5_CH1_flipflop_en,
    input logic  HCLK_i,
    input logic  HRESET_n_i
);

logic   Top_CSC_default_interface_error_s;
logic   [31:0] Top_CSC_default_interface_data_out_s;
logic   AHB_RAI_Bridge_rai_per_acc_en_o_s;
logic   AHB_RAI_Bridge_rai_per_wr_en_o_s;
logic   [1:0] AHB_RAI_Bridge_csc_access_size_o_s;
logic   [31:0] AHB_RAI_Bridge_rai_per_wdata_o_s;
logic   [31:0] AHB_RAI_Bridge_bridge_fsm_haddr_reg_Outp_out_out_s;

tc_soc_timer_Reg_IF_Top_CSC comp_Top_CSC(
    .default_interface_data_in                   ( AHB_RAI_Bridge_rai_per_wdata_o_s                                          ),
    .default_interface_wr_en                     ( (AHB_RAI_Bridge_rai_per_acc_en_o_s & AHB_RAI_Bridge_rai_per_wr_en_o_s)    ),
    .default_interface_addr                      ( AHB_RAI_Bridge_bridge_fsm_haddr_reg_Outp_out_out_s                        ),
    .default_interface_AccessSize                ( AHB_RAI_Bridge_csc_access_size_o_s                                        ),
    .default_interface_rd_en                     ( (AHB_RAI_Bridge_rai_per_acc_en_o_s & (~AHB_RAI_Bridge_rai_per_wr_en_o_s)) ),
    .TimerCSC_BF_bf_ACTVAL_CH0_flipflop_out      ( TimerCSC_BF_bf_ACTVAL_CH0_flipflop_out                                    ),
    .TimerCSC_BF_bf_ACTVAL_CH0_in                ( TimerCSC_BF_bf_ACTVAL_CH0_in                                              ),
    .TimerCSC_BF_bf_ACTVAL_CH0_peripheral_wr_en  ( TimerCSC_BF_bf_ACTVAL_CH0_peripheral_wr_en                                ),
    .TimerCSC_BF_bf_MAXVAL_CH0_flipflop_out      ( TimerCSC_BF_bf_MAXVAL_CH0_flipflop_out                                    ),
    .TimerCSC_BF_bf_CCUVAL0_CH0_flipflop_out     ( TimerCSC_BF_bf_CCUVAL0_CH0_flipflop_out                                   ),
    .TimerCSC_BF_bf_CCUVAL0_CH0_in               ( TimerCSC_BF_bf_CCUVAL0_CH0_in                                             ),
    .TimerCSC_BF_bf_CCUVAL0_CH0_peripheral_wr_en ( TimerCSC_BF_bf_CCUVAL0_CH0_peripheral_wr_en                               ),
    .TimerCSC_BF_bf_ACTVAL_CH1_flipflop_out      ( TimerCSC_BF_bf_ACTVAL_CH1_flipflop_out                                    ),
    .TimerCSC_BF_bf_ACTVAL_CH1_in                ( TimerCSC_BF_bf_ACTVAL_CH1_in                                              ),
    .TimerCSC_BF_bf_ACTVAL_CH1_peripheral_wr_en  ( TimerCSC_BF_bf_ACTVAL_CH1_peripheral_wr_en                                ),
    .TimerCSC_BF_bf_MAXVAL_CH1_flipflop_out      ( TimerCSC_BF_bf_MAXVAL_CH1_flipflop_out                                    ),
    .TimerCSC_BF_bf_CCUVAL0_CH1_flipflop_out     ( TimerCSC_BF_bf_CCUVAL0_CH1_flipflop_out                                   ),
    .TimerCSC_BF_bf_CCUVAL0_CH1_in               ( TimerCSC_BF_bf_CCUVAL0_CH1_in                                             ),
    .TimerCSC_BF_bf_CCUVAL0_CH1_peripheral_wr_en ( TimerCSC_BF_bf_CCUVAL0_CH1_peripheral_wr_en                               ),
    .TimerCSC_BF_bf_CCUVAL1_CH1_flipflop_out     ( TimerCSC_BF_bf_CCUVAL1_CH1_flipflop_out                                   ),
    .TimerCSC_BF_bf_CCUVAL1_CH1_in               ( TimerCSC_BF_bf_CCUVAL1_CH1_in                                             ),
    .TimerCSC_BF_bf_CCUVAL1_CH1_peripheral_wr_en ( TimerCSC_BF_bf_CCUVAL1_CH1_peripheral_wr_en                               ),
    .TimerCSC_BF_bf_CCUVAL2_CH1_flipflop_out     ( TimerCSC_BF_bf_CCUVAL2_CH1_flipflop_out                                   ),
    .TimerCSC_BF_bf_CCUVAL2_CH1_in               ( TimerCSC_BF_bf_CCUVAL2_CH1_in                                             ),
    .TimerCSC_BF_bf_CCUVAL2_CH1_peripheral_wr_en ( TimerCSC_BF_bf_CCUVAL2_CH1_peripheral_wr_en                               ),
    .TimerCSC_BF_bf_CCUVAL3_CH1_flipflop_out     ( TimerCSC_BF_bf_CCUVAL3_CH1_flipflop_out                                   ),
    .TimerCSC_BF_bf_CCUVAL3_CH1_in               ( TimerCSC_BF_bf_CCUVAL3_CH1_in                                             ),
    .TimerCSC_BF_bf_CCUVAL3_CH1_peripheral_wr_en ( TimerCSC_BF_bf_CCUVAL3_CH1_peripheral_wr_en                               ),
    .TimerCSC_BF_bf_CCUVAL4_CH1_flipflop_out     ( TimerCSC_BF_bf_CCUVAL4_CH1_flipflop_out                                   ),
    .TimerCSC_BF_bf_CCUVAL4_CH1_in               ( TimerCSC_BF_bf_CCUVAL4_CH1_in                                             ),
    .TimerCSC_BF_bf_CCUVAL4_CH1_peripheral_wr_en ( TimerCSC_BF_bf_CCUVAL4_CH1_peripheral_wr_en                               ),
    .TimerCSC_BF_bf_CCUVAL5_CH1_flipflop_out     ( TimerCSC_BF_bf_CCUVAL5_CH1_flipflop_out                                   ),
    .TimerCSC_BF_bf_CCUVAL5_CH1_in               ( TimerCSC_BF_bf_CCUVAL5_CH1_in                                             ),
    .TimerCSC_BF_bf_CCUVAL5_CH1_peripheral_wr_en ( TimerCSC_BF_bf_CCUVAL5_CH1_peripheral_wr_en                               ),
    .HCLK_i                                      ( HCLK_i                                                                    ),
    .HRESET_n_i                                  ( HRESET_n_i                                                                ),
    .default_interface_error                     ( Top_CSC_default_interface_error_s                                         ),
    .default_interface_data_out                  ( Top_CSC_default_interface_data_out_s                                      ),
    .default_interface_ready                     (                                                                           ),
    .TimerCSC_BF_bf_OvfIntEn_CH0_out             ( TimerCSC_BF_bf_OvfIntEn_CH0_out                                           ),
    .TimerCSC_BF_bf_CntIM_CH0_out                ( TimerCSC_BF_bf_CntIM_CH0_out                                              ),
    .TimerCSC_BF_bf_ResIM_CH0_out                ( TimerCSC_BF_bf_ResIM_CH0_out                                              ),
    .TimerCSC_BF_bf_TimEn_CH0_out                ( TimerCSC_BF_bf_TimEn_CH0_out                                              ),
    .TimerCSC_BF_bf_ACTVAL_CH0_flipflop_in       ( TimerCSC_BF_bf_ACTVAL_CH0_flipflop_in                                     ),
    .TimerCSC_BF_bf_ACTVAL_CH0_flipflop_en       ( TimerCSC_BF_bf_ACTVAL_CH0_flipflop_en                                     ),
    .TimerCSC_BF_bf_ACTVAL_CH0_out               ( TimerCSC_BF_bf_ACTVAL_CH0_out                                             ),
    .TimerCSC_BF_bf_MAXVAL_CH0_flipflop_in       ( TimerCSC_BF_bf_MAXVAL_CH0_flipflop_in                                     ),
    .TimerCSC_BF_bf_MAXVAL_CH0_flipflop_en       ( TimerCSC_BF_bf_MAXVAL_CH0_flipflop_en                                     ),
    .TimerCSC_BF_bf_MAXVAL_CH0_out               ( TimerCSC_BF_bf_MAXVAL_CH0_out                                             ),
    .TimerCSC_BF_bf_CapIM0_CH0_out               ( TimerCSC_BF_bf_CapIM0_CH0_out                                             ),
    .TimerCSC_BF_bf_CCM0_CH0_out                 ( TimerCSC_BF_bf_CCM0_CH0_out                                               ),
    .TimerCSC_BF_bf_CCUVAL0_CH0_flipflop_in      ( TimerCSC_BF_bf_CCUVAL0_CH0_flipflop_in                                    ),
    .TimerCSC_BF_bf_CCUVAL0_CH0_flipflop_en      ( TimerCSC_BF_bf_CCUVAL0_CH0_flipflop_en                                    ),
    .TimerCSC_BF_bf_CCUVAL0_CH0_out              ( TimerCSC_BF_bf_CCUVAL0_CH0_out                                            ),
    .TimerCSC_BF_bf_OvfIntEn_CH1_out             ( TimerCSC_BF_bf_OvfIntEn_CH1_out                                           ),
    .TimerCSC_BF_bf_CntIM_CH1_out                ( TimerCSC_BF_bf_CntIM_CH1_out                                              ),
    .TimerCSC_BF_bf_ResIM_CH1_out                ( TimerCSC_BF_bf_ResIM_CH1_out                                              ),
    .TimerCSC_BF_bf_TimEn_CH1_out                ( TimerCSC_BF_bf_TimEn_CH1_out                                              ),
    .TimerCSC_BF_bf_ACTVAL_CH1_flipflop_in       ( TimerCSC_BF_bf_ACTVAL_CH1_flipflop_in                                     ),
    .TimerCSC_BF_bf_ACTVAL_CH1_flipflop_en       ( TimerCSC_BF_bf_ACTVAL_CH1_flipflop_en                                     ),
    .TimerCSC_BF_bf_ACTVAL_CH1_out               ( TimerCSC_BF_bf_ACTVAL_CH1_out                                             ),
    .TimerCSC_BF_bf_MAXVAL_CH1_flipflop_in       ( TimerCSC_BF_bf_MAXVAL_CH1_flipflop_in                                     ),
    .TimerCSC_BF_bf_MAXVAL_CH1_flipflop_en       ( TimerCSC_BF_bf_MAXVAL_CH1_flipflop_en                                     ),
    .TimerCSC_BF_bf_MAXVAL_CH1_out               ( TimerCSC_BF_bf_MAXVAL_CH1_out                                             ),
    .TimerCSC_BF_bf_CapIM0_CH1_out               ( TimerCSC_BF_bf_CapIM0_CH1_out                                             ),
    .TimerCSC_BF_bf_CCM0_CH1_out                 ( TimerCSC_BF_bf_CCM0_CH1_out                                               ),
    .TimerCSC_BF_bf_CCUVAL0_CH1_flipflop_in      ( TimerCSC_BF_bf_CCUVAL0_CH1_flipflop_in                                    ),
    .TimerCSC_BF_bf_CCUVAL0_CH1_flipflop_en      ( TimerCSC_BF_bf_CCUVAL0_CH1_flipflop_en                                    ),
    .TimerCSC_BF_bf_CCUVAL0_CH1_out              ( TimerCSC_BF_bf_CCUVAL0_CH1_out                                            ),
    .TimerCSC_BF_bf_CapIM1_CH1_out               ( TimerCSC_BF_bf_CapIM1_CH1_out                                             ),
    .TimerCSC_BF_bf_CCM1_CH1_out                 ( TimerCSC_BF_bf_CCM1_CH1_out                                               ),
    .TimerCSC_BF_bf_CCUVAL1_CH1_flipflop_in      ( TimerCSC_BF_bf_CCUVAL1_CH1_flipflop_in                                    ),
    .TimerCSC_BF_bf_CCUVAL1_CH1_flipflop_en      ( TimerCSC_BF_bf_CCUVAL1_CH1_flipflop_en                                    ),
    .TimerCSC_BF_bf_CCUVAL1_CH1_out              ( TimerCSC_BF_bf_CCUVAL1_CH1_out                                            ),
    .TimerCSC_BF_bf_CapIM2_CH1_out               ( TimerCSC_BF_bf_CapIM2_CH1_out                                             ),
    .TimerCSC_BF_bf_CCM2_CH1_out                 ( TimerCSC_BF_bf_CCM2_CH1_out                                               ),
    .TimerCSC_BF_bf_CCUVAL2_CH1_flipflop_in      ( TimerCSC_BF_bf_CCUVAL2_CH1_flipflop_in                                    ),
    .TimerCSC_BF_bf_CCUVAL2_CH1_flipflop_en      ( TimerCSC_BF_bf_CCUVAL2_CH1_flipflop_en                                    ),
    .TimerCSC_BF_bf_CCUVAL2_CH1_out              ( TimerCSC_BF_bf_CCUVAL2_CH1_out                                            ),
    .TimerCSC_BF_bf_CapIM3_CH1_out               ( TimerCSC_BF_bf_CapIM3_CH1_out                                             ),
    .TimerCSC_BF_bf_CCM3_CH1_out                 ( TimerCSC_BF_bf_CCM3_CH1_out                                               ),
    .TimerCSC_BF_bf_CCUVAL3_CH1_flipflop_in      ( TimerCSC_BF_bf_CCUVAL3_CH1_flipflop_in                                    ),
    .TimerCSC_BF_bf_CCUVAL3_CH1_flipflop_en      ( TimerCSC_BF_bf_CCUVAL3_CH1_flipflop_en                                    ),
    .TimerCSC_BF_bf_CCUVAL3_CH1_out              ( TimerCSC_BF_bf_CCUVAL3_CH1_out                                            ),
    .TimerCSC_BF_bf_CapIM4_CH1_out               ( TimerCSC_BF_bf_CapIM4_CH1_out                                             ),
    .TimerCSC_BF_bf_CCM4_CH1_out                 ( TimerCSC_BF_bf_CCM4_CH1_out                                               ),
    .TimerCSC_BF_bf_CCUVAL4_CH1_flipflop_in      ( TimerCSC_BF_bf_CCUVAL4_CH1_flipflop_in                                    ),
    .TimerCSC_BF_bf_CCUVAL4_CH1_flipflop_en      ( TimerCSC_BF_bf_CCUVAL4_CH1_flipflop_en                                    ),
    .TimerCSC_BF_bf_CCUVAL4_CH1_out              ( TimerCSC_BF_bf_CCUVAL4_CH1_out                                            ),
    .TimerCSC_BF_bf_CapIM5_CH1_out               ( TimerCSC_BF_bf_CapIM5_CH1_out                                             ),
    .TimerCSC_BF_bf_CCM5_CH1_out                 ( TimerCSC_BF_bf_CCM5_CH1_out                                               ),
    .TimerCSC_BF_bf_CCUVAL5_CH1_flipflop_in      ( TimerCSC_BF_bf_CCUVAL5_CH1_flipflop_in                                    ),
    .TimerCSC_BF_bf_CCUVAL5_CH1_flipflop_en      ( TimerCSC_BF_bf_CCUVAL5_CH1_flipflop_en                                    ),
    .TimerCSC_BF_bf_CCUVAL5_CH1_out              ( TimerCSC_BF_bf_CCUVAL5_CH1_out                                            )
);

tc_soc_timer_Reg_IF_AHB_RAI_Bridge comp_AHB_RAI_Bridge(
    .HADDR_i                           ( SX_AHB_HADDR                                       ),
    .HWDATA_i                          ( SX_AHB_HWDATA                                      ),
    .HBURST_i                          ( SX_AHB_HBURST                                      ),
    .HMASTLOCK_i                       ( SX_AHB_HMASTLOCK                                   ),
    .HSIZE_i                           ( SX_AHB_HSIZE                                       ),
    .HTRANS_i                          ( SX_AHB_HTRANS                                      ),
    .HWRITE_i                          ( SX_AHB_HWRITE                                      ),
    .HSEL_i                            ( SX_AHB_HSEL                                        ),
    .HREADY_i                          ( SX_AHB_HREADY                                      ),
    .HPROT_i                           ( SX_AHB_HPROT                                       ),
    .rai_per_rdata_i                   ( Top_CSC_default_interface_data_out_s               ),
    .rai_per_ack_i                     ( (AHB_RAI_Bridge_rai_per_acc_en_o_s | 1'b1)         ),
    .rai_per_err_i                     ( Top_CSC_default_interface_error_s                  ),
    .HCLK_i                            ( HCLK_i                                             ),
    .HRESET_n_i                        ( HRESET_n_i                                         ),
    .HRDATA_o                          ( SX_AHB_HRDATA                                      ),
    .HREADYOUT_o                       ( SX_AHB_HREADYOUT                                   ),
    .HRESP_o                           ( SX_AHB_HRESP                                       ),
    .rai_per_acc_en_o                  ( AHB_RAI_Bridge_rai_per_acc_en_o_s                  ),
    .rai_per_wr_en_o                   ( AHB_RAI_Bridge_rai_per_wr_en_o_s                   ),
    .csc_access_size_o                 ( AHB_RAI_Bridge_csc_access_size_o_s                 ),
    .rai_per_wdata_o                   ( AHB_RAI_Bridge_rai_per_wdata_o_s                   ),
    .bridge_fsm_haddr_reg_Outp_out_out ( AHB_RAI_Bridge_bridge_fsm_haddr_reg_Outp_out_out_s )
);


endmodule

