/* ===============================================================
Copyright 2026, Infineon Technologies AG or an 
affiliate of Infineon Technologies AG.  All rights reserved.
 
This software, associated documentation and materials ("Software") is owned by
Infineon Technologies AG or one of its affiliates ("Infineon") and is 
protected by and subject to worldwide patent protection (United States and 
foreign), United States copyright laws and international treaty provisions. 
Therefore, you may use this Software only as provided in the license agreement
accompanying the software package from which you obtained this 
Software ("EULA"). If no EULA applies, then any reproduction, modification, 
translation, compilation, or representation of this Software is prohibited 
without the express written permission of Infineon.
 
Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF 
ANY KIND, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, 
NONINFRINGEMENT, IMPLIED WARRANTIES OF  MERCHANTABILITY AND
FITNESS FOR A PARTICULAR PURPOSE.  Infineon reserves the right to make
changes to the Software without notice. Infineon does not assume any liability
arising out of the application or use of the Software or any product or 
circuit described in the Software. Infineon does not authorize its products 
for use in any products where a malfunction or failure of the Infineon product 
may reasonably be expected to result in significant property damage, injury or
death ("High Risk Product").  By including Infineon 's product in a High Risk 
Product, the manufacturer of such system or application assumes all risk of 
such use and in doing so agrees to indemnify Infineon against all liability.

 ===============================================================
*/ 
// File : tc_soc_timer_Reg_IF_Top_CSC_Top_CSC_default_interface.sv 
// Author : tahiraga 
// Date : 15:07:02    25/09/2026 
// Revision :  
// =============================================================== 
// Description : 
/*
---- Auto Generated by MetaRTL , a MetaGen application
---- Contact: ParitoshKumar.Sinha@infineon.com
---- Contact: Yash.Ranjan@infineon.com
===============================================================
*/


module tc_soc_timer_Reg_IF_Top_CSC_Top_CSC_default_interface (
    input logic  [31:0] default_interface_addr,
    output logic  default_interface_Address_Error_Port,
    input logic  [1:0] default_interface_AccessSize,
    input logic  [31:0] default_interface_data_in,
    input logic  default_interface_wr_en,
    output logic  [31:0] default_interface_data_out,
    input logic  default_interface_rd_en,
    output logic  default_interface_ready,
    output logic  default_interface_BF_bf_OvfIntEn_CH0_input,
    output logic  default_interface_BF_bf_OvfIntEn_CH0_enable,
    input logic  default_interface_BF_bf_OvfIntEn_CH0_output,
    output logic  default_interface_BF_bf_OvfIntEn_CH0_out,
    output logic  [2:0] default_interface_BF_bf_CntIM_CH0_input,
    output logic  default_interface_BF_bf_CntIM_CH0_enable,
    input logic  [2:0] default_interface_BF_bf_CntIM_CH0_output,
    output logic  [2:0] default_interface_BF_bf_CntIM_CH0_out,
    output logic  [2:0] default_interface_BF_bf_ResIM_CH0_input,
    output logic  default_interface_BF_bf_ResIM_CH0_enable,
    input logic  [2:0] default_interface_BF_bf_ResIM_CH0_output,
    output logic  [2:0] default_interface_BF_bf_ResIM_CH0_out,
    output logic  default_interface_BF_bf_TimEn_CH0_input,
    output logic  default_interface_BF_bf_TimEn_CH0_enable,
    input logic  default_interface_BF_bf_TimEn_CH0_output,
    output logic  default_interface_BF_bf_TimEn_CH0_out,
    output logic  [31:0] default_interface_BF_bf_ACTVAL_CH0_flipflop_in,
    output logic  default_interface_BF_bf_ACTVAL_CH0_flipflop_en,
    input logic  [31:0] default_interface_BF_bf_ACTVAL_CH0_flipflop_out,
    input logic  [31:0] default_interface_BF_bf_ACTVAL_CH0_in,
    input logic  default_interface_BF_bf_ACTVAL_CH0_peripheral_wr_en,
    output logic  [31:0] default_interface_BF_bf_ACTVAL_CH0_out,
    output logic  [31:0] default_interface_BF_bf_MAXVAL_CH0_flipflop_in,
    output logic  default_interface_BF_bf_MAXVAL_CH0_flipflop_en,
    input logic  [31:0] default_interface_BF_bf_MAXVAL_CH0_flipflop_out,
    output logic  [31:0] default_interface_BF_bf_MAXVAL_CH0_out,
    output logic  [2:0] default_interface_BF_bf_CapIM0_CH0_input,
    output logic  default_interface_BF_bf_CapIM0_CH0_enable,
    input logic  [2:0] default_interface_BF_bf_CapIM0_CH0_output,
    output logic  [2:0] default_interface_BF_bf_CapIM0_CH0_out,
    output logic  [2:0] default_interface_BF_bf_CCM0_CH0_input,
    output logic  default_interface_BF_bf_CCM0_CH0_enable,
    input logic  [2:0] default_interface_BF_bf_CCM0_CH0_output,
    output logic  [2:0] default_interface_BF_bf_CCM0_CH0_out,
    output logic  [31:0] default_interface_BF_bf_CCUVAL0_CH0_flipflop_in,
    output logic  default_interface_BF_bf_CCUVAL0_CH0_flipflop_en,
    input logic  [31:0] default_interface_BF_bf_CCUVAL0_CH0_flipflop_out,
    input logic  [31:0] default_interface_BF_bf_CCUVAL0_CH0_in,
    input logic  default_interface_BF_bf_CCUVAL0_CH0_peripheral_wr_en,
    output logic  [31:0] default_interface_BF_bf_CCUVAL0_CH0_out,
    output logic  default_interface_BF_bf_OvfIntEn_CH1_input,
    output logic  default_interface_BF_bf_OvfIntEn_CH1_enable,
    input logic  default_interface_BF_bf_OvfIntEn_CH1_output,
    output logic  default_interface_BF_bf_OvfIntEn_CH1_out,
    output logic  [2:0] default_interface_BF_bf_CntIM_CH1_input,
    output logic  default_interface_BF_bf_CntIM_CH1_enable,
    input logic  [2:0] default_interface_BF_bf_CntIM_CH1_output,
    output logic  [2:0] default_interface_BF_bf_CntIM_CH1_out,
    output logic  [2:0] default_interface_BF_bf_ResIM_CH1_input,
    output logic  default_interface_BF_bf_ResIM_CH1_enable,
    input logic  [2:0] default_interface_BF_bf_ResIM_CH1_output,
    output logic  [2:0] default_interface_BF_bf_ResIM_CH1_out,
    output logic  default_interface_BF_bf_TimEn_CH1_input,
    output logic  default_interface_BF_bf_TimEn_CH1_enable,
    input logic  default_interface_BF_bf_TimEn_CH1_output,
    output logic  default_interface_BF_bf_TimEn_CH1_out,
    output logic  [31:0] default_interface_BF_bf_ACTVAL_CH1_flipflop_in,
    output logic  default_interface_BF_bf_ACTVAL_CH1_flipflop_en,
    input logic  [31:0] default_interface_BF_bf_ACTVAL_CH1_flipflop_out,
    input logic  [31:0] default_interface_BF_bf_ACTVAL_CH1_in,
    input logic  default_interface_BF_bf_ACTVAL_CH1_peripheral_wr_en,
    output logic  [31:0] default_interface_BF_bf_ACTVAL_CH1_out,
    output logic  [31:0] default_interface_BF_bf_MAXVAL_CH1_flipflop_in,
    output logic  default_interface_BF_bf_MAXVAL_CH1_flipflop_en,
    input logic  [31:0] default_interface_BF_bf_MAXVAL_CH1_flipflop_out,
    output logic  [31:0] default_interface_BF_bf_MAXVAL_CH1_out,
    output logic  [2:0] default_interface_BF_bf_CapIM0_CH1_input,
    output logic  default_interface_BF_bf_CapIM0_CH1_enable,
    input logic  [2:0] default_interface_BF_bf_CapIM0_CH1_output,
    output logic  [2:0] default_interface_BF_bf_CapIM0_CH1_out,
    output logic  [2:0] default_interface_BF_bf_CCM0_CH1_input,
    output logic  default_interface_BF_bf_CCM0_CH1_enable,
    input logic  [2:0] default_interface_BF_bf_CCM0_CH1_output,
    output logic  [2:0] default_interface_BF_bf_CCM0_CH1_out,
    output logic  [31:0] default_interface_BF_bf_CCUVAL0_CH1_flipflop_in,
    output logic  default_interface_BF_bf_CCUVAL0_CH1_flipflop_en,
    input logic  [31:0] default_interface_BF_bf_CCUVAL0_CH1_flipflop_out,
    input logic  [31:0] default_interface_BF_bf_CCUVAL0_CH1_in,
    input logic  default_interface_BF_bf_CCUVAL0_CH1_peripheral_wr_en,
    output logic  [31:0] default_interface_BF_bf_CCUVAL0_CH1_out,
    output logic  [2:0] default_interface_BF_bf_CapIM1_CH1_input,
    output logic  default_interface_BF_bf_CapIM1_CH1_enable,
    input logic  [2:0] default_interface_BF_bf_CapIM1_CH1_output,
    output logic  [2:0] default_interface_BF_bf_CapIM1_CH1_out,
    output logic  [2:0] default_interface_BF_bf_CCM1_CH1_input,
    output logic  default_interface_BF_bf_CCM1_CH1_enable,
    input logic  [2:0] default_interface_BF_bf_CCM1_CH1_output,
    output logic  [2:0] default_interface_BF_bf_CCM1_CH1_out,
    output logic  [31:0] default_interface_BF_bf_CCUVAL1_CH1_flipflop_in,
    output logic  default_interface_BF_bf_CCUVAL1_CH1_flipflop_en,
    input logic  [31:0] default_interface_BF_bf_CCUVAL1_CH1_flipflop_out,
    input logic  [31:0] default_interface_BF_bf_CCUVAL1_CH1_in,
    input logic  default_interface_BF_bf_CCUVAL1_CH1_peripheral_wr_en,
    output logic  [31:0] default_interface_BF_bf_CCUVAL1_CH1_out,
    output logic  [2:0] default_interface_BF_bf_CapIM2_CH1_input,
    output logic  default_interface_BF_bf_CapIM2_CH1_enable,
    input logic  [2:0] default_interface_BF_bf_CapIM2_CH1_output,
    output logic  [2:0] default_interface_BF_bf_CapIM2_CH1_out,
    output logic  [2:0] default_interface_BF_bf_CCM2_CH1_input,
    output logic  default_interface_BF_bf_CCM2_CH1_enable,
    input logic  [2:0] default_interface_BF_bf_CCM2_CH1_output,
    output logic  [2:0] default_interface_BF_bf_CCM2_CH1_out,
    output logic  [31:0] default_interface_BF_bf_CCUVAL2_CH1_flipflop_in,
    output logic  default_interface_BF_bf_CCUVAL2_CH1_flipflop_en,
    input logic  [31:0] default_interface_BF_bf_CCUVAL2_CH1_flipflop_out,
    input logic  [31:0] default_interface_BF_bf_CCUVAL2_CH1_in,
    input logic  default_interface_BF_bf_CCUVAL2_CH1_peripheral_wr_en,
    output logic  [31:0] default_interface_BF_bf_CCUVAL2_CH1_out,
    output logic  [2:0] default_interface_BF_bf_CapIM3_CH1_input,
    output logic  default_interface_BF_bf_CapIM3_CH1_enable,
    input logic  [2:0] default_interface_BF_bf_CapIM3_CH1_output,
    output logic  [2:0] default_interface_BF_bf_CapIM3_CH1_out,
    output logic  [2:0] default_interface_BF_bf_CCM3_CH1_input,
    output logic  default_interface_BF_bf_CCM3_CH1_enable,
    input logic  [2:0] default_interface_BF_bf_CCM3_CH1_output,
    output logic  [2:0] default_interface_BF_bf_CCM3_CH1_out,
    output logic  [31:0] default_interface_BF_bf_CCUVAL3_CH1_flipflop_in,
    output logic  default_interface_BF_bf_CCUVAL3_CH1_flipflop_en,
    input logic  [31:0] default_interface_BF_bf_CCUVAL3_CH1_flipflop_out,
    input logic  [31:0] default_interface_BF_bf_CCUVAL3_CH1_in,
    input logic  default_interface_BF_bf_CCUVAL3_CH1_peripheral_wr_en,
    output logic  [31:0] default_interface_BF_bf_CCUVAL3_CH1_out,
    output logic  [2:0] default_interface_BF_bf_CapIM4_CH1_input,
    output logic  default_interface_BF_bf_CapIM4_CH1_enable,
    input logic  [2:0] default_interface_BF_bf_CapIM4_CH1_output,
    output logic  [2:0] default_interface_BF_bf_CapIM4_CH1_out,
    output logic  [2:0] default_interface_BF_bf_CCM4_CH1_input,
    output logic  default_interface_BF_bf_CCM4_CH1_enable,
    input logic  [2:0] default_interface_BF_bf_CCM4_CH1_output,
    output logic  [2:0] default_interface_BF_bf_CCM4_CH1_out,
    output logic  [31:0] default_interface_BF_bf_CCUVAL4_CH1_flipflop_in,
    output logic  default_interface_BF_bf_CCUVAL4_CH1_flipflop_en,
    input logic  [31:0] default_interface_BF_bf_CCUVAL4_CH1_flipflop_out,
    input logic  [31:0] default_interface_BF_bf_CCUVAL4_CH1_in,
    input logic  default_interface_BF_bf_CCUVAL4_CH1_peripheral_wr_en,
    output logic  [31:0] default_interface_BF_bf_CCUVAL4_CH1_out,
    output logic  [2:0] default_interface_BF_bf_CapIM5_CH1_input,
    output logic  default_interface_BF_bf_CapIM5_CH1_enable,
    input logic  [2:0] default_interface_BF_bf_CapIM5_CH1_output,
    output logic  [2:0] default_interface_BF_bf_CapIM5_CH1_out,
    output logic  [2:0] default_interface_BF_bf_CCM5_CH1_input,
    output logic  default_interface_BF_bf_CCM5_CH1_enable,
    input logic  [2:0] default_interface_BF_bf_CCM5_CH1_output,
    output logic  [2:0] default_interface_BF_bf_CCM5_CH1_out,
    output logic  [31:0] default_interface_BF_bf_CCUVAL5_CH1_flipflop_in,
    output logic  default_interface_BF_bf_CCUVAL5_CH1_flipflop_en,
    input logic  [31:0] default_interface_BF_bf_CCUVAL5_CH1_flipflop_out,
    input logic  [31:0] default_interface_BF_bf_CCUVAL5_CH1_in,
    input logic  default_interface_BF_bf_CCUVAL5_CH1_peripheral_wr_en,
    output logic  [31:0] default_interface_BF_bf_CCUVAL5_CH1_out
);

logic   [31:0] Top_CSC_default_interface_AccessSizeCircuit_default_interface_AS_masking_mux_out_s;
logic   [4:0] Top_CSC_default_interface_AccessSizeCircuit_default_interface_AS_shift_value_mux_out_s;
logic   Top_CSC_default_interface_AccessSizeCircuit_Address_EQ_Port_CH0_CTRLSTAT_s;
logic   Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_OvfIntEn_CH0_of_CH0_CTRLSTAT_s;
logic   Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CntIM_CH0_of_CH0_CTRLSTAT_s;
logic   Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_ResIM_CH0_of_CH0_CTRLSTAT_s;
logic   Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_TimEn_CH0_of_CH0_CTRLSTAT_s;
logic   Top_CSC_default_interface_AccessSizeCircuit_Address_EQ_Port_CH0_ACTVAL_s;
logic   Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_ACTVAL_CH0_of_CH0_ACTVAL_s;
logic   Top_CSC_default_interface_AccessSizeCircuit_Address_EQ_Port_CH0_MAXVAL_s;
logic   Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_MAXVAL_CH0_of_CH0_MAXVAL_s;
logic   Top_CSC_default_interface_AccessSizeCircuit_Address_EQ_Port_CH0_CCUCTRL0_s;
logic   Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CapIM0_CH0_of_CH0_CCUCTRL0_s;
logic   Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CCM0_CH0_of_CH0_CCUCTRL0_s;
logic   Top_CSC_default_interface_AccessSizeCircuit_Address_EQ_Port_CH0_CCUVAL0_s;
logic   Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CCUVAL0_CH0_of_CH0_CCUVAL0_s;
logic   Top_CSC_default_interface_AccessSizeCircuit_Address_EQ_Port_CH1_CTRLSTAT_s;
logic   Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_OvfIntEn_CH1_of_CH1_CTRLSTAT_s;
logic   Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CntIM_CH1_of_CH1_CTRLSTAT_s;
logic   Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_ResIM_CH1_of_CH1_CTRLSTAT_s;
logic   Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_TimEn_CH1_of_CH1_CTRLSTAT_s;
logic   Top_CSC_default_interface_AccessSizeCircuit_Address_EQ_Port_CH1_ACTVAL_s;
logic   Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_ACTVAL_CH1_of_CH1_ACTVAL_s;
logic   Top_CSC_default_interface_AccessSizeCircuit_Address_EQ_Port_CH1_MAXVAL_s;
logic   Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_MAXVAL_CH1_of_CH1_MAXVAL_s;
logic   Top_CSC_default_interface_AccessSizeCircuit_Address_EQ_Port_CH1_CCUCTRL0_s;
logic   Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CapIM0_CH1_of_CH1_CCUCTRL0_s;
logic   Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CCM0_CH1_of_CH1_CCUCTRL0_s;
logic   Top_CSC_default_interface_AccessSizeCircuit_Address_EQ_Port_CH1_CCUVAL0_s;
logic   Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CCUVAL0_CH1_of_CH1_CCUVAL0_s;
logic   Top_CSC_default_interface_AccessSizeCircuit_Address_EQ_Port_CH1_CCUCTRL1_s;
logic   Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CapIM1_CH1_of_CH1_CCUCTRL1_s;
logic   Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CCM1_CH1_of_CH1_CCUCTRL1_s;
logic   Top_CSC_default_interface_AccessSizeCircuit_Address_EQ_Port_CH1_CCUVAL1_s;
logic   Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CCUVAL1_CH1_of_CH1_CCUVAL1_s;
logic   Top_CSC_default_interface_AccessSizeCircuit_Address_EQ_Port_CH1_CCUCTRL2_s;
logic   Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CapIM2_CH1_of_CH1_CCUCTRL2_s;
logic   Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CCM2_CH1_of_CH1_CCUCTRL2_s;
logic   Top_CSC_default_interface_AccessSizeCircuit_Address_EQ_Port_CH1_CCUVAL2_s;
logic   Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CCUVAL2_CH1_of_CH1_CCUVAL2_s;
logic   Top_CSC_default_interface_AccessSizeCircuit_Address_EQ_Port_CH1_CCUCTRL3_s;
logic   Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CapIM3_CH1_of_CH1_CCUCTRL3_s;
logic   Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CCM3_CH1_of_CH1_CCUCTRL3_s;
logic   Top_CSC_default_interface_AccessSizeCircuit_Address_EQ_Port_CH1_CCUVAL3_s;
logic   Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CCUVAL3_CH1_of_CH1_CCUVAL3_s;
logic   Top_CSC_default_interface_AccessSizeCircuit_Address_EQ_Port_CH1_CCUCTRL4_s;
logic   Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CapIM4_CH1_of_CH1_CCUCTRL4_s;
logic   Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CCM4_CH1_of_CH1_CCUCTRL4_s;
logic   Top_CSC_default_interface_AccessSizeCircuit_Address_EQ_Port_CH1_CCUVAL4_s;
logic   Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CCUVAL4_CH1_of_CH1_CCUVAL4_s;
logic   Top_CSC_default_interface_AccessSizeCircuit_Address_EQ_Port_CH1_CCUCTRL5_s;
logic   Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CapIM5_CH1_of_CH1_CCUCTRL5_s;
logic   Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CCM5_CH1_of_CH1_CCUCTRL5_s;
logic   Top_CSC_default_interface_AccessSizeCircuit_Address_EQ_Port_CH1_CCUVAL5_s;
logic   Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CCUVAL5_CH1_of_CH1_CCUVAL5_s;

tc_soc_timer_Reg_IF_Top_CSC_Top_CSC_default_interface_Top_CSC_default_interface_WriteCircuit comp_Top_CSC_default_interface_WriteCircuit(
    .default_interface_w_c_data_in                                   ( default_interface_data_in                                                                ),
    .dc_land_for_Reg_bf_OvfIntEn_CH0_CH0_CTRLSTAT                    ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_OvfIntEn_CH0_of_CH0_CTRLSTAT_s ),
    .dc_land_for_Reg_bf_CntIM_CH0_CH0_CTRLSTAT                       ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CntIM_CH0_of_CH0_CTRLSTAT_s    ),
    .dc_land_for_Reg_bf_ResIM_CH0_CH0_CTRLSTAT                       ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_ResIM_CH0_of_CH0_CTRLSTAT_s    ),
    .dc_land_for_Reg_bf_TimEn_CH0_CH0_CTRLSTAT                       ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_TimEn_CH0_of_CH0_CTRLSTAT_s    ),
    .dc_land_for_Reg_bf_ACTVAL_CH0_CH0_ACTVAL                        ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_ACTVAL_CH0_of_CH0_ACTVAL_s     ),
    .default_interface_w_c_BF_bf_ACTVAL_CH0_in                       ( default_interface_BF_bf_ACTVAL_CH0_in                                                    ),
    .default_interface_w_c_BF_bf_ACTVAL_CH0_peripheral_wr_en         ( default_interface_BF_bf_ACTVAL_CH0_peripheral_wr_en                                      ),
    .dc_land_for_Reg_bf_MAXVAL_CH0_CH0_MAXVAL                        ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_MAXVAL_CH0_of_CH0_MAXVAL_s     ),
    .dc_land_for_Reg_bf_CapIM0_CH0_CH0_CCUCTRL0                      ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CapIM0_CH0_of_CH0_CCUCTRL0_s   ),
    .dc_land_for_Reg_bf_CCM0_CH0_CH0_CCUCTRL0                        ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CCM0_CH0_of_CH0_CCUCTRL0_s     ),
    .dc_land_for_Reg_bf_CCUVAL0_CH0_CH0_CCUVAL0                      ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CCUVAL0_CH0_of_CH0_CCUVAL0_s   ),
    .default_interface_w_c_BF_bf_CCUVAL0_CH0_in                      ( default_interface_BF_bf_CCUVAL0_CH0_in                                                   ),
    .default_interface_w_c_BF_bf_CCUVAL0_CH0_peripheral_wr_en        ( default_interface_BF_bf_CCUVAL0_CH0_peripheral_wr_en                                     ),
    .dc_land_for_Reg_bf_OvfIntEn_CH1_CH1_CTRLSTAT                    ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_OvfIntEn_CH1_of_CH1_CTRLSTAT_s ),
    .dc_land_for_Reg_bf_CntIM_CH1_CH1_CTRLSTAT                       ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CntIM_CH1_of_CH1_CTRLSTAT_s    ),
    .dc_land_for_Reg_bf_ResIM_CH1_CH1_CTRLSTAT                       ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_ResIM_CH1_of_CH1_CTRLSTAT_s    ),
    .dc_land_for_Reg_bf_TimEn_CH1_CH1_CTRLSTAT                       ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_TimEn_CH1_of_CH1_CTRLSTAT_s    ),
    .dc_land_for_Reg_bf_ACTVAL_CH1_CH1_ACTVAL                        ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_ACTVAL_CH1_of_CH1_ACTVAL_s     ),
    .default_interface_w_c_BF_bf_ACTVAL_CH1_in                       ( default_interface_BF_bf_ACTVAL_CH1_in                                                    ),
    .default_interface_w_c_BF_bf_ACTVAL_CH1_peripheral_wr_en         ( default_interface_BF_bf_ACTVAL_CH1_peripheral_wr_en                                      ),
    .dc_land_for_Reg_bf_MAXVAL_CH1_CH1_MAXVAL                        ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_MAXVAL_CH1_of_CH1_MAXVAL_s     ),
    .dc_land_for_Reg_bf_CapIM0_CH1_CH1_CCUCTRL0                      ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CapIM0_CH1_of_CH1_CCUCTRL0_s   ),
    .dc_land_for_Reg_bf_CCM0_CH1_CH1_CCUCTRL0                        ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CCM0_CH1_of_CH1_CCUCTRL0_s     ),
    .dc_land_for_Reg_bf_CCUVAL0_CH1_CH1_CCUVAL0                      ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CCUVAL0_CH1_of_CH1_CCUVAL0_s   ),
    .default_interface_w_c_BF_bf_CCUVAL0_CH1_in                      ( default_interface_BF_bf_CCUVAL0_CH1_in                                                   ),
    .default_interface_w_c_BF_bf_CCUVAL0_CH1_peripheral_wr_en        ( default_interface_BF_bf_CCUVAL0_CH1_peripheral_wr_en                                     ),
    .dc_land_for_Reg_bf_CapIM1_CH1_CH1_CCUCTRL1                      ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CapIM1_CH1_of_CH1_CCUCTRL1_s   ),
    .dc_land_for_Reg_bf_CCM1_CH1_CH1_CCUCTRL1                        ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CCM1_CH1_of_CH1_CCUCTRL1_s     ),
    .dc_land_for_Reg_bf_CCUVAL1_CH1_CH1_CCUVAL1                      ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CCUVAL1_CH1_of_CH1_CCUVAL1_s   ),
    .default_interface_w_c_BF_bf_CCUVAL1_CH1_in                      ( default_interface_BF_bf_CCUVAL1_CH1_in                                                   ),
    .default_interface_w_c_BF_bf_CCUVAL1_CH1_peripheral_wr_en        ( default_interface_BF_bf_CCUVAL1_CH1_peripheral_wr_en                                     ),
    .dc_land_for_Reg_bf_CapIM2_CH1_CH1_CCUCTRL2                      ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CapIM2_CH1_of_CH1_CCUCTRL2_s   ),
    .dc_land_for_Reg_bf_CCM2_CH1_CH1_CCUCTRL2                        ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CCM2_CH1_of_CH1_CCUCTRL2_s     ),
    .dc_land_for_Reg_bf_CCUVAL2_CH1_CH1_CCUVAL2                      ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CCUVAL2_CH1_of_CH1_CCUVAL2_s   ),
    .default_interface_w_c_BF_bf_CCUVAL2_CH1_in                      ( default_interface_BF_bf_CCUVAL2_CH1_in                                                   ),
    .default_interface_w_c_BF_bf_CCUVAL2_CH1_peripheral_wr_en        ( default_interface_BF_bf_CCUVAL2_CH1_peripheral_wr_en                                     ),
    .dc_land_for_Reg_bf_CapIM3_CH1_CH1_CCUCTRL3                      ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CapIM3_CH1_of_CH1_CCUCTRL3_s   ),
    .dc_land_for_Reg_bf_CCM3_CH1_CH1_CCUCTRL3                        ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CCM3_CH1_of_CH1_CCUCTRL3_s     ),
    .dc_land_for_Reg_bf_CCUVAL3_CH1_CH1_CCUVAL3                      ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CCUVAL3_CH1_of_CH1_CCUVAL3_s   ),
    .default_interface_w_c_BF_bf_CCUVAL3_CH1_in                      ( default_interface_BF_bf_CCUVAL3_CH1_in                                                   ),
    .default_interface_w_c_BF_bf_CCUVAL3_CH1_peripheral_wr_en        ( default_interface_BF_bf_CCUVAL3_CH1_peripheral_wr_en                                     ),
    .dc_land_for_Reg_bf_CapIM4_CH1_CH1_CCUCTRL4                      ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CapIM4_CH1_of_CH1_CCUCTRL4_s   ),
    .dc_land_for_Reg_bf_CCM4_CH1_CH1_CCUCTRL4                        ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CCM4_CH1_of_CH1_CCUCTRL4_s     ),
    .dc_land_for_Reg_bf_CCUVAL4_CH1_CH1_CCUVAL4                      ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CCUVAL4_CH1_of_CH1_CCUVAL4_s   ),
    .default_interface_w_c_BF_bf_CCUVAL4_CH1_in                      ( default_interface_BF_bf_CCUVAL4_CH1_in                                                   ),
    .default_interface_w_c_BF_bf_CCUVAL4_CH1_peripheral_wr_en        ( default_interface_BF_bf_CCUVAL4_CH1_peripheral_wr_en                                     ),
    .dc_land_for_Reg_bf_CapIM5_CH1_CH1_CCUCTRL5                      ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CapIM5_CH1_of_CH1_CCUCTRL5_s   ),
    .dc_land_for_Reg_bf_CCM5_CH1_CH1_CCUCTRL5                        ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CCM5_CH1_of_CH1_CCUCTRL5_s     ),
    .dc_land_for_Reg_bf_CCUVAL5_CH1_CH1_CCUVAL5                      ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CCUVAL5_CH1_of_CH1_CCUVAL5_s   ),
    .default_interface_w_c_BF_bf_CCUVAL5_CH1_in                      ( default_interface_BF_bf_CCUVAL5_CH1_in                                                   ),
    .default_interface_w_c_BF_bf_CCUVAL5_CH1_peripheral_wr_en        ( default_interface_BF_bf_CCUVAL5_CH1_peripheral_wr_en                                     ),
    .Input_of_Reg_bf_OvfIntEn_CH0                                    ( default_interface_BF_bf_OvfIntEn_CH0_input                                               ),
    .Enable_of_Reg_bf_OvfIntEn_CH0                                   ( default_interface_BF_bf_OvfIntEn_CH0_enable                                              ),
    .Input_of_Reg_bf_CntIM_CH0                                       ( default_interface_BF_bf_CntIM_CH0_input                                                  ),
    .Enable_of_Reg_bf_CntIM_CH0                                      ( default_interface_BF_bf_CntIM_CH0_enable                                                 ),
    .Input_of_Reg_bf_ResIM_CH0                                       ( default_interface_BF_bf_ResIM_CH0_input                                                  ),
    .Enable_of_Reg_bf_ResIM_CH0                                      ( default_interface_BF_bf_ResIM_CH0_enable                                                 ),
    .Input_of_Reg_bf_TimEn_CH0                                       ( default_interface_BF_bf_TimEn_CH0_input                                                  ),
    .Enable_of_Reg_bf_TimEn_CH0                                      ( default_interface_BF_bf_TimEn_CH0_enable                                                 ),
    .default_interface_w_c_BF_bf_ACTVAL_CH0_CH0_ACTVAL_flipflop_in   ( default_interface_BF_bf_ACTVAL_CH0_flipflop_in                                           ),
    .default_interface_w_c_BF_bf_ACTVAL_CH0_CH0_ACTVAL_flipflop_en   ( default_interface_BF_bf_ACTVAL_CH0_flipflop_en                                           ),
    .default_interface_w_c_BF_bf_MAXVAL_CH0_CH0_MAXVAL_flipflop_in   ( default_interface_BF_bf_MAXVAL_CH0_flipflop_in                                           ),
    .default_interface_w_c_BF_bf_MAXVAL_CH0_CH0_MAXVAL_flipflop_en   ( default_interface_BF_bf_MAXVAL_CH0_flipflop_en                                           ),
    .Input_of_Reg_bf_CapIM0_CH0                                      ( default_interface_BF_bf_CapIM0_CH0_input                                                 ),
    .Enable_of_Reg_bf_CapIM0_CH0                                     ( default_interface_BF_bf_CapIM0_CH0_enable                                                ),
    .Input_of_Reg_bf_CCM0_CH0                                        ( default_interface_BF_bf_CCM0_CH0_input                                                   ),
    .Enable_of_Reg_bf_CCM0_CH0                                       ( default_interface_BF_bf_CCM0_CH0_enable                                                  ),
    .default_interface_w_c_BF_bf_CCUVAL0_CH0_CH0_CCUVAL0_flipflop_in ( default_interface_BF_bf_CCUVAL0_CH0_flipflop_in                                          ),
    .default_interface_w_c_BF_bf_CCUVAL0_CH0_CH0_CCUVAL0_flipflop_en ( default_interface_BF_bf_CCUVAL0_CH0_flipflop_en                                          ),
    .Input_of_Reg_bf_OvfIntEn_CH1                                    ( default_interface_BF_bf_OvfIntEn_CH1_input                                               ),
    .Enable_of_Reg_bf_OvfIntEn_CH1                                   ( default_interface_BF_bf_OvfIntEn_CH1_enable                                              ),
    .Input_of_Reg_bf_CntIM_CH1                                       ( default_interface_BF_bf_CntIM_CH1_input                                                  ),
    .Enable_of_Reg_bf_CntIM_CH1                                      ( default_interface_BF_bf_CntIM_CH1_enable                                                 ),
    .Input_of_Reg_bf_ResIM_CH1                                       ( default_interface_BF_bf_ResIM_CH1_input                                                  ),
    .Enable_of_Reg_bf_ResIM_CH1                                      ( default_interface_BF_bf_ResIM_CH1_enable                                                 ),
    .Input_of_Reg_bf_TimEn_CH1                                       ( default_interface_BF_bf_TimEn_CH1_input                                                  ),
    .Enable_of_Reg_bf_TimEn_CH1                                      ( default_interface_BF_bf_TimEn_CH1_enable                                                 ),
    .default_interface_w_c_BF_bf_ACTVAL_CH1_CH1_ACTVAL_flipflop_in   ( default_interface_BF_bf_ACTVAL_CH1_flipflop_in                                           ),
    .default_interface_w_c_BF_bf_ACTVAL_CH1_CH1_ACTVAL_flipflop_en   ( default_interface_BF_bf_ACTVAL_CH1_flipflop_en                                           ),
    .default_interface_w_c_BF_bf_MAXVAL_CH1_CH1_MAXVAL_flipflop_in   ( default_interface_BF_bf_MAXVAL_CH1_flipflop_in                                           ),
    .default_interface_w_c_BF_bf_MAXVAL_CH1_CH1_MAXVAL_flipflop_en   ( default_interface_BF_bf_MAXVAL_CH1_flipflop_en                                           ),
    .Input_of_Reg_bf_CapIM0_CH1                                      ( default_interface_BF_bf_CapIM0_CH1_input                                                 ),
    .Enable_of_Reg_bf_CapIM0_CH1                                     ( default_interface_BF_bf_CapIM0_CH1_enable                                                ),
    .Input_of_Reg_bf_CCM0_CH1                                        ( default_interface_BF_bf_CCM0_CH1_input                                                   ),
    .Enable_of_Reg_bf_CCM0_CH1                                       ( default_interface_BF_bf_CCM0_CH1_enable                                                  ),
    .default_interface_w_c_BF_bf_CCUVAL0_CH1_CH1_CCUVAL0_flipflop_in ( default_interface_BF_bf_CCUVAL0_CH1_flipflop_in                                          ),
    .default_interface_w_c_BF_bf_CCUVAL0_CH1_CH1_CCUVAL0_flipflop_en ( default_interface_BF_bf_CCUVAL0_CH1_flipflop_en                                          ),
    .Input_of_Reg_bf_CapIM1_CH1                                      ( default_interface_BF_bf_CapIM1_CH1_input                                                 ),
    .Enable_of_Reg_bf_CapIM1_CH1                                     ( default_interface_BF_bf_CapIM1_CH1_enable                                                ),
    .Input_of_Reg_bf_CCM1_CH1                                        ( default_interface_BF_bf_CCM1_CH1_input                                                   ),
    .Enable_of_Reg_bf_CCM1_CH1                                       ( default_interface_BF_bf_CCM1_CH1_enable                                                  ),
    .default_interface_w_c_BF_bf_CCUVAL1_CH1_CH1_CCUVAL1_flipflop_in ( default_interface_BF_bf_CCUVAL1_CH1_flipflop_in                                          ),
    .default_interface_w_c_BF_bf_CCUVAL1_CH1_CH1_CCUVAL1_flipflop_en ( default_interface_BF_bf_CCUVAL1_CH1_flipflop_en                                          ),
    .Input_of_Reg_bf_CapIM2_CH1                                      ( default_interface_BF_bf_CapIM2_CH1_input                                                 ),
    .Enable_of_Reg_bf_CapIM2_CH1                                     ( default_interface_BF_bf_CapIM2_CH1_enable                                                ),
    .Input_of_Reg_bf_CCM2_CH1                                        ( default_interface_BF_bf_CCM2_CH1_input                                                   ),
    .Enable_of_Reg_bf_CCM2_CH1                                       ( default_interface_BF_bf_CCM2_CH1_enable                                                  ),
    .default_interface_w_c_BF_bf_CCUVAL2_CH1_CH1_CCUVAL2_flipflop_in ( default_interface_BF_bf_CCUVAL2_CH1_flipflop_in                                          ),
    .default_interface_w_c_BF_bf_CCUVAL2_CH1_CH1_CCUVAL2_flipflop_en ( default_interface_BF_bf_CCUVAL2_CH1_flipflop_en                                          ),
    .Input_of_Reg_bf_CapIM3_CH1                                      ( default_interface_BF_bf_CapIM3_CH1_input                                                 ),
    .Enable_of_Reg_bf_CapIM3_CH1                                     ( default_interface_BF_bf_CapIM3_CH1_enable                                                ),
    .Input_of_Reg_bf_CCM3_CH1                                        ( default_interface_BF_bf_CCM3_CH1_input                                                   ),
    .Enable_of_Reg_bf_CCM3_CH1                                       ( default_interface_BF_bf_CCM3_CH1_enable                                                  ),
    .default_interface_w_c_BF_bf_CCUVAL3_CH1_CH1_CCUVAL3_flipflop_in ( default_interface_BF_bf_CCUVAL3_CH1_flipflop_in                                          ),
    .default_interface_w_c_BF_bf_CCUVAL3_CH1_CH1_CCUVAL3_flipflop_en ( default_interface_BF_bf_CCUVAL3_CH1_flipflop_en                                          ),
    .Input_of_Reg_bf_CapIM4_CH1                                      ( default_interface_BF_bf_CapIM4_CH1_input                                                 ),
    .Enable_of_Reg_bf_CapIM4_CH1                                     ( default_interface_BF_bf_CapIM4_CH1_enable                                                ),
    .Input_of_Reg_bf_CCM4_CH1                                        ( default_interface_BF_bf_CCM4_CH1_input                                                   ),
    .Enable_of_Reg_bf_CCM4_CH1                                       ( default_interface_BF_bf_CCM4_CH1_enable                                                  ),
    .default_interface_w_c_BF_bf_CCUVAL4_CH1_CH1_CCUVAL4_flipflop_in ( default_interface_BF_bf_CCUVAL4_CH1_flipflop_in                                          ),
    .default_interface_w_c_BF_bf_CCUVAL4_CH1_CH1_CCUVAL4_flipflop_en ( default_interface_BF_bf_CCUVAL4_CH1_flipflop_en                                          ),
    .Input_of_Reg_bf_CapIM5_CH1                                      ( default_interface_BF_bf_CapIM5_CH1_input                                                 ),
    .Enable_of_Reg_bf_CapIM5_CH1                                     ( default_interface_BF_bf_CapIM5_CH1_enable                                                ),
    .Input_of_Reg_bf_CCM5_CH1                                        ( default_interface_BF_bf_CCM5_CH1_input                                                   ),
    .Enable_of_Reg_bf_CCM5_CH1                                       ( default_interface_BF_bf_CCM5_CH1_enable                                                  ),
    .default_interface_w_c_BF_bf_CCUVAL5_CH1_CH1_CCUVAL5_flipflop_in ( default_interface_BF_bf_CCUVAL5_CH1_flipflop_in                                          ),
    .default_interface_w_c_BF_bf_CCUVAL5_CH1_CH1_CCUVAL5_flipflop_en ( default_interface_BF_bf_CCUVAL5_CH1_flipflop_en                                          )
);

tc_soc_timer_Reg_IF_Top_CSC_Top_CSC_default_interface_Top_CSC_default_interface_ReadCircuit comp_Top_CSC_default_interface_ReadCircuit(
    .default_interface_RC_rd_en                  ( default_interface_rd_en                                                                ),
    .default_interface_RC_Shifting_Value_Mux_out ( Top_CSC_default_interface_AccessSizeCircuit_default_interface_AS_shift_value_mux_out_s ),
    .default_interface_RC_Masking_Mux_out        ( Top_CSC_default_interface_AccessSizeCircuit_default_interface_AS_masking_mux_out_s     ),
    .Port_of_Reg_bf_OvfIntEn_CH0                 ( default_interface_BF_bf_OvfIntEn_CH0_output                                            ),
    .Port_of_Reg_bf_CntIM_CH0                    ( default_interface_BF_bf_CntIM_CH0_output                                               ),
    .Port_of_Reg_bf_ResIM_CH0                    ( default_interface_BF_bf_ResIM_CH0_output                                               ),
    .Port_of_Reg_bf_TimEn_CH0                    ( default_interface_BF_bf_TimEn_CH0_output                                               ),
    .Address_EQ_Port_CH0_CTRLSTAT                ( Top_CSC_default_interface_AccessSizeCircuit_Address_EQ_Port_CH0_CTRLSTAT_s             ),
    .Port_of_BF_bf_ACTVAL_CH0_flipflop_out       ( default_interface_BF_bf_ACTVAL_CH0_flipflop_out                                        ),
    .Address_EQ_Port_CH0_ACTVAL                  ( Top_CSC_default_interface_AccessSizeCircuit_Address_EQ_Port_CH0_ACTVAL_s               ),
    .Port_of_BF_bf_MAXVAL_CH0_flipflop_out       ( default_interface_BF_bf_MAXVAL_CH0_flipflop_out                                        ),
    .Address_EQ_Port_CH0_MAXVAL                  ( Top_CSC_default_interface_AccessSizeCircuit_Address_EQ_Port_CH0_MAXVAL_s               ),
    .Port_of_Reg_bf_CapIM0_CH0                   ( default_interface_BF_bf_CapIM0_CH0_output                                              ),
    .Port_of_Reg_bf_CCM0_CH0                     ( default_interface_BF_bf_CCM0_CH0_output                                                ),
    .Address_EQ_Port_CH0_CCUCTRL0                ( Top_CSC_default_interface_AccessSizeCircuit_Address_EQ_Port_CH0_CCUCTRL0_s             ),
    .Port_of_BF_bf_CCUVAL0_CH0_flipflop_out      ( default_interface_BF_bf_CCUVAL0_CH0_flipflop_out                                       ),
    .Address_EQ_Port_CH0_CCUVAL0                 ( Top_CSC_default_interface_AccessSizeCircuit_Address_EQ_Port_CH0_CCUVAL0_s              ),
    .Port_of_Reg_bf_OvfIntEn_CH1                 ( default_interface_BF_bf_OvfIntEn_CH1_output                                            ),
    .Port_of_Reg_bf_CntIM_CH1                    ( default_interface_BF_bf_CntIM_CH1_output                                               ),
    .Port_of_Reg_bf_ResIM_CH1                    ( default_interface_BF_bf_ResIM_CH1_output                                               ),
    .Port_of_Reg_bf_TimEn_CH1                    ( default_interface_BF_bf_TimEn_CH1_output                                               ),
    .Address_EQ_Port_CH1_CTRLSTAT                ( Top_CSC_default_interface_AccessSizeCircuit_Address_EQ_Port_CH1_CTRLSTAT_s             ),
    .Port_of_BF_bf_ACTVAL_CH1_flipflop_out       ( default_interface_BF_bf_ACTVAL_CH1_flipflop_out                                        ),
    .Address_EQ_Port_CH1_ACTVAL                  ( Top_CSC_default_interface_AccessSizeCircuit_Address_EQ_Port_CH1_ACTVAL_s               ),
    .Port_of_BF_bf_MAXVAL_CH1_flipflop_out       ( default_interface_BF_bf_MAXVAL_CH1_flipflop_out                                        ),
    .Address_EQ_Port_CH1_MAXVAL                  ( Top_CSC_default_interface_AccessSizeCircuit_Address_EQ_Port_CH1_MAXVAL_s               ),
    .Port_of_Reg_bf_CapIM0_CH1                   ( default_interface_BF_bf_CapIM0_CH1_output                                              ),
    .Port_of_Reg_bf_CCM0_CH1                     ( default_interface_BF_bf_CCM0_CH1_output                                                ),
    .Address_EQ_Port_CH1_CCUCTRL0                ( Top_CSC_default_interface_AccessSizeCircuit_Address_EQ_Port_CH1_CCUCTRL0_s             ),
    .Port_of_BF_bf_CCUVAL0_CH1_flipflop_out      ( default_interface_BF_bf_CCUVAL0_CH1_flipflop_out                                       ),
    .Address_EQ_Port_CH1_CCUVAL0                 ( Top_CSC_default_interface_AccessSizeCircuit_Address_EQ_Port_CH1_CCUVAL0_s              ),
    .Port_of_Reg_bf_CapIM1_CH1                   ( default_interface_BF_bf_CapIM1_CH1_output                                              ),
    .Port_of_Reg_bf_CCM1_CH1                     ( default_interface_BF_bf_CCM1_CH1_output                                                ),
    .Address_EQ_Port_CH1_CCUCTRL1                ( Top_CSC_default_interface_AccessSizeCircuit_Address_EQ_Port_CH1_CCUCTRL1_s             ),
    .Port_of_BF_bf_CCUVAL1_CH1_flipflop_out      ( default_interface_BF_bf_CCUVAL1_CH1_flipflop_out                                       ),
    .Address_EQ_Port_CH1_CCUVAL1                 ( Top_CSC_default_interface_AccessSizeCircuit_Address_EQ_Port_CH1_CCUVAL1_s              ),
    .Port_of_Reg_bf_CapIM2_CH1                   ( default_interface_BF_bf_CapIM2_CH1_output                                              ),
    .Port_of_Reg_bf_CCM2_CH1                     ( default_interface_BF_bf_CCM2_CH1_output                                                ),
    .Address_EQ_Port_CH1_CCUCTRL2                ( Top_CSC_default_interface_AccessSizeCircuit_Address_EQ_Port_CH1_CCUCTRL2_s             ),
    .Port_of_BF_bf_CCUVAL2_CH1_flipflop_out      ( default_interface_BF_bf_CCUVAL2_CH1_flipflop_out                                       ),
    .Address_EQ_Port_CH1_CCUVAL2                 ( Top_CSC_default_interface_AccessSizeCircuit_Address_EQ_Port_CH1_CCUVAL2_s              ),
    .Port_of_Reg_bf_CapIM3_CH1                   ( default_interface_BF_bf_CapIM3_CH1_output                                              ),
    .Port_of_Reg_bf_CCM3_CH1                     ( default_interface_BF_bf_CCM3_CH1_output                                                ),
    .Address_EQ_Port_CH1_CCUCTRL3                ( Top_CSC_default_interface_AccessSizeCircuit_Address_EQ_Port_CH1_CCUCTRL3_s             ),
    .Port_of_BF_bf_CCUVAL3_CH1_flipflop_out      ( default_interface_BF_bf_CCUVAL3_CH1_flipflop_out                                       ),
    .Address_EQ_Port_CH1_CCUVAL3                 ( Top_CSC_default_interface_AccessSizeCircuit_Address_EQ_Port_CH1_CCUVAL3_s              ),
    .Port_of_Reg_bf_CapIM4_CH1                   ( default_interface_BF_bf_CapIM4_CH1_output                                              ),
    .Port_of_Reg_bf_CCM4_CH1                     ( default_interface_BF_bf_CCM4_CH1_output                                                ),
    .Address_EQ_Port_CH1_CCUCTRL4                ( Top_CSC_default_interface_AccessSizeCircuit_Address_EQ_Port_CH1_CCUCTRL4_s             ),
    .Port_of_BF_bf_CCUVAL4_CH1_flipflop_out      ( default_interface_BF_bf_CCUVAL4_CH1_flipflop_out                                       ),
    .Address_EQ_Port_CH1_CCUVAL4                 ( Top_CSC_default_interface_AccessSizeCircuit_Address_EQ_Port_CH1_CCUVAL4_s              ),
    .Port_of_Reg_bf_CapIM5_CH1                   ( default_interface_BF_bf_CapIM5_CH1_output                                              ),
    .Port_of_Reg_bf_CCM5_CH1                     ( default_interface_BF_bf_CCM5_CH1_output                                                ),
    .Address_EQ_Port_CH1_CCUCTRL5                ( Top_CSC_default_interface_AccessSizeCircuit_Address_EQ_Port_CH1_CCUCTRL5_s             ),
    .Port_of_BF_bf_CCUVAL5_CH1_flipflop_out      ( default_interface_BF_bf_CCUVAL5_CH1_flipflop_out                                       ),
    .Address_EQ_Port_CH1_CCUVAL5                 ( Top_CSC_default_interface_AccessSizeCircuit_Address_EQ_Port_CH1_CCUVAL5_s              ),
    .default_interface_RC_data_out               ( default_interface_data_out                                                             ),
    .default_interface_RC_bf_OvfIntEn_CH0_out    ( default_interface_BF_bf_OvfIntEn_CH0_out                                               ),
    .default_interface_RC_bf_CntIM_CH0_out       ( default_interface_BF_bf_CntIM_CH0_out                                                  ),
    .default_interface_RC_bf_ResIM_CH0_out       ( default_interface_BF_bf_ResIM_CH0_out                                                  ),
    .default_interface_RC_bf_TimEn_CH0_out       ( default_interface_BF_bf_TimEn_CH0_out                                                  ),
    .default_interface_RC_bf_ACTVAL_CH0_out      ( default_interface_BF_bf_ACTVAL_CH0_out                                                 ),
    .default_interface_RC_bf_MAXVAL_CH0_out      ( default_interface_BF_bf_MAXVAL_CH0_out                                                 ),
    .default_interface_RC_bf_CapIM0_CH0_out      ( default_interface_BF_bf_CapIM0_CH0_out                                                 ),
    .default_interface_RC_bf_CCM0_CH0_out        ( default_interface_BF_bf_CCM0_CH0_out                                                   ),
    .default_interface_RC_bf_CCUVAL0_CH0_out     ( default_interface_BF_bf_CCUVAL0_CH0_out                                                ),
    .default_interface_RC_bf_OvfIntEn_CH1_out    ( default_interface_BF_bf_OvfIntEn_CH1_out                                               ),
    .default_interface_RC_bf_CntIM_CH1_out       ( default_interface_BF_bf_CntIM_CH1_out                                                  ),
    .default_interface_RC_bf_ResIM_CH1_out       ( default_interface_BF_bf_ResIM_CH1_out                                                  ),
    .default_interface_RC_bf_TimEn_CH1_out       ( default_interface_BF_bf_TimEn_CH1_out                                                  ),
    .default_interface_RC_bf_ACTVAL_CH1_out      ( default_interface_BF_bf_ACTVAL_CH1_out                                                 ),
    .default_interface_RC_bf_MAXVAL_CH1_out      ( default_interface_BF_bf_MAXVAL_CH1_out                                                 ),
    .default_interface_RC_bf_CapIM0_CH1_out      ( default_interface_BF_bf_CapIM0_CH1_out                                                 ),
    .default_interface_RC_bf_CCM0_CH1_out        ( default_interface_BF_bf_CCM0_CH1_out                                                   ),
    .default_interface_RC_bf_CCUVAL0_CH1_out     ( default_interface_BF_bf_CCUVAL0_CH1_out                                                ),
    .default_interface_RC_bf_CapIM1_CH1_out      ( default_interface_BF_bf_CapIM1_CH1_out                                                 ),
    .default_interface_RC_bf_CCM1_CH1_out        ( default_interface_BF_bf_CCM1_CH1_out                                                   ),
    .default_interface_RC_bf_CCUVAL1_CH1_out     ( default_interface_BF_bf_CCUVAL1_CH1_out                                                ),
    .default_interface_RC_bf_CapIM2_CH1_out      ( default_interface_BF_bf_CapIM2_CH1_out                                                 ),
    .default_interface_RC_bf_CCM2_CH1_out        ( default_interface_BF_bf_CCM2_CH1_out                                                   ),
    .default_interface_RC_bf_CCUVAL2_CH1_out     ( default_interface_BF_bf_CCUVAL2_CH1_out                                                ),
    .default_interface_RC_bf_CapIM3_CH1_out      ( default_interface_BF_bf_CapIM3_CH1_out                                                 ),
    .default_interface_RC_bf_CCM3_CH1_out        ( default_interface_BF_bf_CCM3_CH1_out                                                   ),
    .default_interface_RC_bf_CCUVAL3_CH1_out     ( default_interface_BF_bf_CCUVAL3_CH1_out                                                ),
    .default_interface_RC_bf_CapIM4_CH1_out      ( default_interface_BF_bf_CapIM4_CH1_out                                                 ),
    .default_interface_RC_bf_CCM4_CH1_out        ( default_interface_BF_bf_CCM4_CH1_out                                                   ),
    .default_interface_RC_bf_CCUVAL4_CH1_out     ( default_interface_BF_bf_CCUVAL4_CH1_out                                                ),
    .default_interface_RC_bf_CapIM5_CH1_out      ( default_interface_BF_bf_CapIM5_CH1_out                                                 ),
    .default_interface_RC_bf_CCM5_CH1_out        ( default_interface_BF_bf_CCM5_CH1_out                                                   ),
    .default_interface_RC_bf_CCUVAL5_CH1_out     ( default_interface_BF_bf_CCUVAL5_CH1_out                                                )
);

tc_soc_timer_Reg_IF_Top_CSC_Top_CSC_default_interface_Top_CSC_default_interface_AccessSizeCircuit comp_Top_CSC_default_interface_AccessSizeCircuit(
    .default_interface_addr                     ( default_interface_addr                                                                   ),
    .default_interface_wr_en                    ( default_interface_wr_en                                                                  ),
    .default_interface_AS_in_AS_block           ( default_interface_AccessSize                                                             ),
    .default_interface_AS_masking_mux_out       ( Top_CSC_default_interface_AccessSizeCircuit_default_interface_AS_masking_mux_out_s       ),
    .default_interface_AS_shift_value_mux_out   ( Top_CSC_default_interface_AccessSizeCircuit_default_interface_AS_shift_value_mux_out_s   ),
    .default_interface_Address_Error_Port       ( default_interface_Address_Error_Port                                                     ),
    .Address_EQ_Port_CH0_CTRLSTAT               ( Top_CSC_default_interface_AccessSizeCircuit_Address_EQ_Port_CH0_CTRLSTAT_s               ),
    .Enable_Reg_bf_OvfIntEn_CH0_of_CH0_CTRLSTAT ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_OvfIntEn_CH0_of_CH0_CTRLSTAT_s ),
    .Enable_Reg_bf_CntIM_CH0_of_CH0_CTRLSTAT    ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CntIM_CH0_of_CH0_CTRLSTAT_s    ),
    .Enable_Reg_bf_ResIM_CH0_of_CH0_CTRLSTAT    ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_ResIM_CH0_of_CH0_CTRLSTAT_s    ),
    .Enable_Reg_bf_TimEn_CH0_of_CH0_CTRLSTAT    ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_TimEn_CH0_of_CH0_CTRLSTAT_s    ),
    .Address_EQ_Port_CH0_ACTVAL                 ( Top_CSC_default_interface_AccessSizeCircuit_Address_EQ_Port_CH0_ACTVAL_s                 ),
    .Enable_Reg_bf_ACTVAL_CH0_of_CH0_ACTVAL     ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_ACTVAL_CH0_of_CH0_ACTVAL_s     ),
    .Address_EQ_Port_CH0_MAXVAL                 ( Top_CSC_default_interface_AccessSizeCircuit_Address_EQ_Port_CH0_MAXVAL_s                 ),
    .Enable_Reg_bf_MAXVAL_CH0_of_CH0_MAXVAL     ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_MAXVAL_CH0_of_CH0_MAXVAL_s     ),
    .Address_EQ_Port_CH0_CCUCTRL0               ( Top_CSC_default_interface_AccessSizeCircuit_Address_EQ_Port_CH0_CCUCTRL0_s               ),
    .Enable_Reg_bf_CapIM0_CH0_of_CH0_CCUCTRL0   ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CapIM0_CH0_of_CH0_CCUCTRL0_s   ),
    .Enable_Reg_bf_CCM0_CH0_of_CH0_CCUCTRL0     ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CCM0_CH0_of_CH0_CCUCTRL0_s     ),
    .Address_EQ_Port_CH0_CCUVAL0                ( Top_CSC_default_interface_AccessSizeCircuit_Address_EQ_Port_CH0_CCUVAL0_s                ),
    .Enable_Reg_bf_CCUVAL0_CH0_of_CH0_CCUVAL0   ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CCUVAL0_CH0_of_CH0_CCUVAL0_s   ),
    .Address_EQ_Port_CH1_CTRLSTAT               ( Top_CSC_default_interface_AccessSizeCircuit_Address_EQ_Port_CH1_CTRLSTAT_s               ),
    .Enable_Reg_bf_OvfIntEn_CH1_of_CH1_CTRLSTAT ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_OvfIntEn_CH1_of_CH1_CTRLSTAT_s ),
    .Enable_Reg_bf_CntIM_CH1_of_CH1_CTRLSTAT    ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CntIM_CH1_of_CH1_CTRLSTAT_s    ),
    .Enable_Reg_bf_ResIM_CH1_of_CH1_CTRLSTAT    ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_ResIM_CH1_of_CH1_CTRLSTAT_s    ),
    .Enable_Reg_bf_TimEn_CH1_of_CH1_CTRLSTAT    ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_TimEn_CH1_of_CH1_CTRLSTAT_s    ),
    .Address_EQ_Port_CH1_ACTVAL                 ( Top_CSC_default_interface_AccessSizeCircuit_Address_EQ_Port_CH1_ACTVAL_s                 ),
    .Enable_Reg_bf_ACTVAL_CH1_of_CH1_ACTVAL     ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_ACTVAL_CH1_of_CH1_ACTVAL_s     ),
    .Address_EQ_Port_CH1_MAXVAL                 ( Top_CSC_default_interface_AccessSizeCircuit_Address_EQ_Port_CH1_MAXVAL_s                 ),
    .Enable_Reg_bf_MAXVAL_CH1_of_CH1_MAXVAL     ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_MAXVAL_CH1_of_CH1_MAXVAL_s     ),
    .Address_EQ_Port_CH1_CCUCTRL0               ( Top_CSC_default_interface_AccessSizeCircuit_Address_EQ_Port_CH1_CCUCTRL0_s               ),
    .Enable_Reg_bf_CapIM0_CH1_of_CH1_CCUCTRL0   ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CapIM0_CH1_of_CH1_CCUCTRL0_s   ),
    .Enable_Reg_bf_CCM0_CH1_of_CH1_CCUCTRL0     ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CCM0_CH1_of_CH1_CCUCTRL0_s     ),
    .Address_EQ_Port_CH1_CCUVAL0                ( Top_CSC_default_interface_AccessSizeCircuit_Address_EQ_Port_CH1_CCUVAL0_s                ),
    .Enable_Reg_bf_CCUVAL0_CH1_of_CH1_CCUVAL0   ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CCUVAL0_CH1_of_CH1_CCUVAL0_s   ),
    .Address_EQ_Port_CH1_CCUCTRL1               ( Top_CSC_default_interface_AccessSizeCircuit_Address_EQ_Port_CH1_CCUCTRL1_s               ),
    .Enable_Reg_bf_CapIM1_CH1_of_CH1_CCUCTRL1   ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CapIM1_CH1_of_CH1_CCUCTRL1_s   ),
    .Enable_Reg_bf_CCM1_CH1_of_CH1_CCUCTRL1     ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CCM1_CH1_of_CH1_CCUCTRL1_s     ),
    .Address_EQ_Port_CH1_CCUVAL1                ( Top_CSC_default_interface_AccessSizeCircuit_Address_EQ_Port_CH1_CCUVAL1_s                ),
    .Enable_Reg_bf_CCUVAL1_CH1_of_CH1_CCUVAL1   ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CCUVAL1_CH1_of_CH1_CCUVAL1_s   ),
    .Address_EQ_Port_CH1_CCUCTRL2               ( Top_CSC_default_interface_AccessSizeCircuit_Address_EQ_Port_CH1_CCUCTRL2_s               ),
    .Enable_Reg_bf_CapIM2_CH1_of_CH1_CCUCTRL2   ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CapIM2_CH1_of_CH1_CCUCTRL2_s   ),
    .Enable_Reg_bf_CCM2_CH1_of_CH1_CCUCTRL2     ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CCM2_CH1_of_CH1_CCUCTRL2_s     ),
    .Address_EQ_Port_CH1_CCUVAL2                ( Top_CSC_default_interface_AccessSizeCircuit_Address_EQ_Port_CH1_CCUVAL2_s                ),
    .Enable_Reg_bf_CCUVAL2_CH1_of_CH1_CCUVAL2   ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CCUVAL2_CH1_of_CH1_CCUVAL2_s   ),
    .Address_EQ_Port_CH1_CCUCTRL3               ( Top_CSC_default_interface_AccessSizeCircuit_Address_EQ_Port_CH1_CCUCTRL3_s               ),
    .Enable_Reg_bf_CapIM3_CH1_of_CH1_CCUCTRL3   ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CapIM3_CH1_of_CH1_CCUCTRL3_s   ),
    .Enable_Reg_bf_CCM3_CH1_of_CH1_CCUCTRL3     ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CCM3_CH1_of_CH1_CCUCTRL3_s     ),
    .Address_EQ_Port_CH1_CCUVAL3                ( Top_CSC_default_interface_AccessSizeCircuit_Address_EQ_Port_CH1_CCUVAL3_s                ),
    .Enable_Reg_bf_CCUVAL3_CH1_of_CH1_CCUVAL3   ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CCUVAL3_CH1_of_CH1_CCUVAL3_s   ),
    .Address_EQ_Port_CH1_CCUCTRL4               ( Top_CSC_default_interface_AccessSizeCircuit_Address_EQ_Port_CH1_CCUCTRL4_s               ),
    .Enable_Reg_bf_CapIM4_CH1_of_CH1_CCUCTRL4   ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CapIM4_CH1_of_CH1_CCUCTRL4_s   ),
    .Enable_Reg_bf_CCM4_CH1_of_CH1_CCUCTRL4     ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CCM4_CH1_of_CH1_CCUCTRL4_s     ),
    .Address_EQ_Port_CH1_CCUVAL4                ( Top_CSC_default_interface_AccessSizeCircuit_Address_EQ_Port_CH1_CCUVAL4_s                ),
    .Enable_Reg_bf_CCUVAL4_CH1_of_CH1_CCUVAL4   ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CCUVAL4_CH1_of_CH1_CCUVAL4_s   ),
    .Address_EQ_Port_CH1_CCUCTRL5               ( Top_CSC_default_interface_AccessSizeCircuit_Address_EQ_Port_CH1_CCUCTRL5_s               ),
    .Enable_Reg_bf_CapIM5_CH1_of_CH1_CCUCTRL5   ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CapIM5_CH1_of_CH1_CCUCTRL5_s   ),
    .Enable_Reg_bf_CCM5_CH1_of_CH1_CCUCTRL5     ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CCM5_CH1_of_CH1_CCUCTRL5_s     ),
    .Address_EQ_Port_CH1_CCUVAL5                ( Top_CSC_default_interface_AccessSizeCircuit_Address_EQ_Port_CH1_CCUVAL5_s                ),
    .Enable_Reg_bf_CCUVAL5_CH1_of_CH1_CCUVAL5   ( Top_CSC_default_interface_AccessSizeCircuit_Enable_Reg_bf_CCUVAL5_CH1_of_CH1_CCUVAL5_s   )
);

assign default_interface_ready = 1'b1;

endmodule

