/* ===============================================================
Copyright 2026, Infineon Technologies AG or an 
affiliate of Infineon Technologies AG.  All rights reserved.
 
This software, associated documentation and materials ("Software") is owned by
Infineon Technologies AG or one of its affiliates ("Infineon") and is 
protected by and subject to worldwide patent protection (United States and 
foreign), United States copyright laws and international treaty provisions. 
Therefore, you may use this Software only as provided in the license agreement
accompanying the software package from which you obtained this 
Software ("EULA"). If no EULA applies, then any reproduction, modification, 
translation, compilation, or representation of this Software is prohibited 
without the express written permission of Infineon.
 
Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF 
ANY KIND, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, 
NONINFRINGEMENT, IMPLIED WARRANTIES OF  MERCHANTABILITY AND
FITNESS FOR A PARTICULAR PURPOSE.  Infineon reserves the right to make
changes to the Software without notice. Infineon does not assume any liability
arising out of the application or use of the Software or any product or 
circuit described in the Software. Infineon does not authorize its products 
for use in any products where a malfunction or failure of the Infineon product 
may reasonably be expected to result in significant property damage, injury or
death ("High Risk Product").  By including Infineon 's product in a High Risk 
Product, the manufacturer of such system or application assumes all risk of 
such use and in doing so agrees to indemnify Infineon against all liability.

 ===============================================================
*/ 
// File : tc_soc_timer_timer_TimerChannel_1_CCU_5.sv 
// Author : tahiraga 
// Date : 15:07:02    25/09/2026 
// Revision :  
// =============================================================== 
// Description : 
/*
---- Auto Generated by MetaRTL , a MetaGen application
---- Contact: ParitoshKumar.Sinha@infineon.com
---- Contact: Yash.Ranjan@infineon.com
===============================================================
*/


module tc_soc_timer_cCCUnit (
    input logic  [2:0] CCM,
    input logic  [31:0] ACTVAL_in,
    input logic  ExtCap_trig,
    input logic  CCUVAL_flipflop_en,
    input logic  [31:0] CCUVAL_flipflop_in,
    output logic  [31:0] CCUVAL_flipflop_out,
    input logic  [31:0] CCUVAL_in,
    output logic  [31:0] CCUVAL_out,
    output logic  CCUVAL_wr,
    output logic  ExtComp,
    input logic  HCLK_i,
    input logic  HRESET_n_i
);

logic   [5:0] Comparator_ComStat_out_s;
logic   comparator_bit_5_Outp_s;
logic   comparator_bit_4_Outp_s;
logic   comparator_bit_3_Outp_s;
logic   comparator_bit_2_Outp_s;
logic   comparator_bit_1_Outp_s;
logic   comparator_bit_0_Outp_s;
logic   CapMode_Outp_s;

logic   ComstatDec_Outp_s;

tc_soc_timer_cComparator comp_Comparator(
    .ACTVAL_in   ( ACTVAL_in                ),
    .CCUVAL_in   ( CCUVAL_in                ),
    .ComStat_out ( Comparator_ComStat_out_s )
);

assign comparator_bit_5_Outp_s = Comparator_ComStat_out_s[5];

assign comparator_bit_4_Outp_s = Comparator_ComStat_out_s[4];

assign comparator_bit_3_Outp_s = Comparator_ComStat_out_s[3];

assign comparator_bit_2_Outp_s = Comparator_ComStat_out_s[2];

assign comparator_bit_1_Outp_s = Comparator_ComStat_out_s[1];

assign comparator_bit_0_Outp_s = Comparator_ComStat_out_s[0];

always_comb
begin
    case (CCM)
        3'b0 : ComstatDec_Outp_s = 1'b0;
        3'b1 : ComstatDec_Outp_s = comparator_bit_0_Outp_s;
        3'b10 : ComstatDec_Outp_s = comparator_bit_1_Outp_s;
        3'b11 : ComstatDec_Outp_s = comparator_bit_2_Outp_s;
        3'b100 : ComstatDec_Outp_s = comparator_bit_3_Outp_s;
        3'b101 : ComstatDec_Outp_s = comparator_bit_4_Outp_s;
        3'b110 : ComstatDec_Outp_s = comparator_bit_5_Outp_s;
        default : ComstatDec_Outp_s = 1'b0;
    endcase

end

assign ExtComp = ComstatDec_Outp_s & (~CapMode_Outp_s);

assign CapMode_Outp_s = 3'b0 == CCM ? 1'b1 : 1'b0;

assign CCUVAL_wr = CapMode_Outp_s & ExtCap_trig;

always_ff @(negedge HRESET_n_i, posedge HCLK_i)
begin
    if (HRESET_n_i == 1'b0) begin
        CCUVAL_flipflop_out <= 32'b0;
    end else begin
        if (CCUVAL_flipflop_en == 1'b1) begin
            CCUVAL_flipflop_out <= CCUVAL_flipflop_in;
        end
    end

end

assign CCUVAL_out = ACTVAL_in;

endmodule

