/* ===============================================================
Copyright 2026, Infineon Technologies AG or an 
affiliate of Infineon Technologies AG.  All rights reserved.
 
This software, associated documentation and materials ("Software") is owned by
Infineon Technologies AG or one of its affiliates ("Infineon") and is 
protected by and subject to worldwide patent protection (United States and 
foreign), United States copyright laws and international treaty provisions. 
Therefore, you may use this Software only as provided in the license agreement
accompanying the software package from which you obtained this 
Software ("EULA"). If no EULA applies, then any reproduction, modification, 
translation, compilation, or representation of this Software is prohibited 
without the express written permission of Infineon.
 
Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF 
ANY KIND, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, 
NONINFRINGEMENT, IMPLIED WARRANTIES OF  MERCHANTABILITY AND
FITNESS FOR A PARTICULAR PURPOSE.  Infineon reserves the right to make
changes to the Software without notice. Infineon does not assume any liability
arising out of the application or use of the Software or any product or 
circuit described in the Software. Infineon does not authorize its products 
for use in any products where a malfunction or failure of the Infineon product 
may reasonably be expected to result in significant property damage, injury or
death ("High Risk Product").  By including Infineon 's product in a High Risk 
Product, the manufacturer of such system or application assumes all risk of 
such use and in doing so agrees to indemnify Infineon against all liability.

 ===============================================================
*/ 
// File : tc_soc_timer_timer.sv 
// Author : tahiraga 
// Date : 15:07:02    25/09/2026 
// Revision :  
// =============================================================== 
// Description : 
/*
---- Auto Generated by MetaRTL , a MetaGen application
---- Contact: ParitoshKumar.Sinha@infineon.com
---- Contact: Yash.Ranjan@infineon.com
===============================================================
tc_soc_timer_timer: Timer component which contains the TimerChannels and is accessed via a CSC interface 
 */


module tc_soc_timer_timer (
    input logic  TIM0_ExtRes,
    input logic  TIM0_ExtCnt,
    output logic  TIM0_OvfInt,
    input logic  TIM0_OvfIntRes,
    input logic  TIM0_CCU0_ExtCap,
    output logic  TIM0_CCU0_ExtComp,
    input logic  TIM1_ExtRes,
    input logic  TIM1_ExtCnt,
    output logic  TIM1_OvfInt,
    input logic  TIM1_OvfIntRes,
    input logic  TIM1_CCU0_ExtCap,
    output logic  TIM1_CCU0_ExtComp,
    input logic  TIM1_CCU1_ExtCap,
    output logic  TIM1_CCU1_ExtComp,
    input logic  TIM1_CCU2_ExtCap,
    output logic  TIM1_CCU2_ExtComp,
    input logic  TIM1_CCU3_ExtCap,
    output logic  TIM1_CCU3_ExtComp,
    input logic  TIM1_CCU4_ExtCap,
    output logic  TIM1_CCU4_ExtComp,
    input logic  TIM1_CCU5_ExtCap,
    output logic  TIM1_CCU5_ExtComp,
    input logic  bf_TimEn_CH0_out,
    input logic  bf_OvfIntEn_CH0_out,
    input logic  [2:0] bf_ResIM_CH0_out,
    input logic  [2:0] bf_CntIM_CH0_out,
    input logic  [31:0] bf_ACTVAL_CH0_flipflop_in,
    output logic  [31:0] bf_ACTVAL_CH0_flipflop_out,
    input logic  bf_ACTVAL_CH0_flipflop_en,
    output logic  [31:0] bf_ACTVAL_CH0_in,
    input logic  [31:0] bf_ACTVAL_CH0_out,
    output logic  bf_ACTVAL_CH0_peripheral_wr_en,
    input logic  [31:0] bf_MAXVAL_CH0_flipflop_in,
    output logic  [31:0] bf_MAXVAL_CH0_flipflop_out,
    input logic  bf_MAXVAL_CH0_flipflop_en,
    input logic  [31:0] bf_MAXVAL_CH0_out,
    input logic  [31:0] bf_CCUVAL0_CH0_flipflop_in,
    output logic  [31:0] bf_CCUVAL0_CH0_flipflop_out,
    input logic  bf_CCUVAL0_CH0_flipflop_en,
    output logic  [31:0] bf_CCUVAL0_CH0_in,
    input logic  [31:0] bf_CCUVAL0_CH0_out,
    output logic  bf_CCUVAL0_CH0_peripheral_wr_en,
    input logic  [2:0] bf_CapIM0_CH0_out,
    input logic  [2:0] bf_CCM0_CH0_out,
    input logic  bf_TimEn_CH1_out,
    input logic  bf_OvfIntEn_CH1_out,
    input logic  [2:0] bf_ResIM_CH1_out,
    input logic  [2:0] bf_CntIM_CH1_out,
    input logic  [31:0] bf_ACTVAL_CH1_flipflop_in,
    output logic  [31:0] bf_ACTVAL_CH1_flipflop_out,
    input logic  bf_ACTVAL_CH1_flipflop_en,
    output logic  [31:0] bf_ACTVAL_CH1_in,
    input logic  [31:0] bf_ACTVAL_CH1_out,
    output logic  bf_ACTVAL_CH1_peripheral_wr_en,
    input logic  [31:0] bf_MAXVAL_CH1_flipflop_in,
    output logic  [31:0] bf_MAXVAL_CH1_flipflop_out,
    input logic  bf_MAXVAL_CH1_flipflop_en,
    input logic  [31:0] bf_MAXVAL_CH1_out,
    input logic  [31:0] bf_CCUVAL0_CH1_flipflop_in,
    output logic  [31:0] bf_CCUVAL0_CH1_flipflop_out,
    input logic  bf_CCUVAL0_CH1_flipflop_en,
    output logic  [31:0] bf_CCUVAL0_CH1_in,
    input logic  [31:0] bf_CCUVAL0_CH1_out,
    output logic  bf_CCUVAL0_CH1_peripheral_wr_en,
    input logic  [2:0] bf_CapIM0_CH1_out,
    input logic  [2:0] bf_CCM0_CH1_out,
    input logic  [31:0] bf_CCUVAL1_CH1_flipflop_in,
    output logic  [31:0] bf_CCUVAL1_CH1_flipflop_out,
    input logic  bf_CCUVAL1_CH1_flipflop_en,
    output logic  [31:0] bf_CCUVAL1_CH1_in,
    input logic  [31:0] bf_CCUVAL1_CH1_out,
    output logic  bf_CCUVAL1_CH1_peripheral_wr_en,
    input logic  [2:0] bf_CapIM1_CH1_out,
    input logic  [2:0] bf_CCM1_CH1_out,
    input logic  [31:0] bf_CCUVAL2_CH1_flipflop_in,
    output logic  [31:0] bf_CCUVAL2_CH1_flipflop_out,
    input logic  bf_CCUVAL2_CH1_flipflop_en,
    output logic  [31:0] bf_CCUVAL2_CH1_in,
    input logic  [31:0] bf_CCUVAL2_CH1_out,
    output logic  bf_CCUVAL2_CH1_peripheral_wr_en,
    input logic  [2:0] bf_CapIM2_CH1_out,
    input logic  [2:0] bf_CCM2_CH1_out,
    input logic  [31:0] bf_CCUVAL3_CH1_flipflop_in,
    output logic  [31:0] bf_CCUVAL3_CH1_flipflop_out,
    input logic  bf_CCUVAL3_CH1_flipflop_en,
    output logic  [31:0] bf_CCUVAL3_CH1_in,
    input logic  [31:0] bf_CCUVAL3_CH1_out,
    output logic  bf_CCUVAL3_CH1_peripheral_wr_en,
    input logic  [2:0] bf_CapIM3_CH1_out,
    input logic  [2:0] bf_CCM3_CH1_out,
    input logic  [31:0] bf_CCUVAL4_CH1_flipflop_in,
    output logic  [31:0] bf_CCUVAL4_CH1_flipflop_out,
    input logic  bf_CCUVAL4_CH1_flipflop_en,
    output logic  [31:0] bf_CCUVAL4_CH1_in,
    input logic  [31:0] bf_CCUVAL4_CH1_out,
    output logic  bf_CCUVAL4_CH1_peripheral_wr_en,
    input logic  [2:0] bf_CapIM4_CH1_out,
    input logic  [2:0] bf_CCM4_CH1_out,
    input logic  [31:0] bf_CCUVAL5_CH1_flipflop_in,
    output logic  [31:0] bf_CCUVAL5_CH1_flipflop_out,
    input logic  bf_CCUVAL5_CH1_flipflop_en,
    output logic  [31:0] bf_CCUVAL5_CH1_in,
    input logic  [31:0] bf_CCUVAL5_CH1_out,
    output logic  bf_CCUVAL5_CH1_peripheral_wr_en,
    input logic  [2:0] bf_CapIM5_CH1_out,
    input logic  [2:0] bf_CCM5_CH1_out,
    input logic  HCLK_i,
    input logic  HRESET_n_i
);

tc_soc_timer_timer_TimerChannel_1 comp_TimerChannel_1(
    .MAXVAL_flipflop_en   ( bf_MAXVAL_CH1_flipflop_en       ),
    .MAXVAL_flipflop_in   ( bf_MAXVAL_CH1_flipflop_in       ),
    .MAXVAL_in            ( bf_MAXVAL_CH1_out               ),
    .ResIM                ( bf_ResIM_CH1_out                ),
    .ExtRes               ( TIM1_ExtRes                     ),
    .ExtCnt               ( TIM1_ExtCnt                     ),
    .CntIM                ( bf_CntIM_CH1_out                ),
    .ExtCap0              ( TIM1_CCU0_ExtCap                ),
    .CapIM0               ( bf_CapIM0_CH1_out               ),
    .ExtCap1              ( TIM1_CCU1_ExtCap                ),
    .CapIM1               ( bf_CapIM1_CH1_out               ),
    .ExtCap2              ( TIM1_CCU2_ExtCap                ),
    .CapIM2               ( bf_CapIM2_CH1_out               ),
    .ExtCap3              ( TIM1_CCU3_ExtCap                ),
    .CapIM3               ( bf_CapIM3_CH1_out               ),
    .ExtCap4              ( TIM1_CCU4_ExtCap                ),
    .CapIM4               ( bf_CapIM4_CH1_out               ),
    .ExtCap5              ( TIM1_CCU5_ExtCap                ),
    .CapIM5               ( bf_CapIM5_CH1_out               ),
    .ACTVAL_flipflop_en   ( bf_ACTVAL_CH1_flipflop_en       ),
    .ACTVAL_flipflop_in   ( bf_ACTVAL_CH1_flipflop_in       ),
    .ACTVAL_in            ( bf_ACTVAL_CH1_out               ),
    .TimEn                ( bf_TimEn_CH1_out                ),
    .OvfIntRes            ( TIM1_OvfIntRes                  ),
    .OvfIntEn             ( bf_OvfIntEn_CH1_out             ),
    .CCM0                 ( bf_CCM0_CH1_out                 ),
    .CCUVAL0_flipflop_en  ( bf_CCUVAL0_CH1_flipflop_en      ),
    .CCUVAL0_flipflop_in  ( bf_CCUVAL0_CH1_flipflop_in      ),
    .CCUVAL0_in           ( bf_CCUVAL0_CH1_out              ),
    .CCM1                 ( bf_CCM1_CH1_out                 ),
    .CCUVAL1_flipflop_en  ( bf_CCUVAL1_CH1_flipflop_en      ),
    .CCUVAL1_flipflop_in  ( bf_CCUVAL1_CH1_flipflop_in      ),
    .CCUVAL1_in           ( bf_CCUVAL1_CH1_out              ),
    .CCM2                 ( bf_CCM2_CH1_out                 ),
    .CCUVAL2_flipflop_en  ( bf_CCUVAL2_CH1_flipflop_en      ),
    .CCUVAL2_flipflop_in  ( bf_CCUVAL2_CH1_flipflop_in      ),
    .CCUVAL2_in           ( bf_CCUVAL2_CH1_out              ),
    .CCM3                 ( bf_CCM3_CH1_out                 ),
    .CCUVAL3_flipflop_en  ( bf_CCUVAL3_CH1_flipflop_en      ),
    .CCUVAL3_flipflop_in  ( bf_CCUVAL3_CH1_flipflop_in      ),
    .CCUVAL3_in           ( bf_CCUVAL3_CH1_out              ),
    .CCM4                 ( bf_CCM4_CH1_out                 ),
    .CCUVAL4_flipflop_en  ( bf_CCUVAL4_CH1_flipflop_en      ),
    .CCUVAL4_flipflop_in  ( bf_CCUVAL4_CH1_flipflop_in      ),
    .CCUVAL4_in           ( bf_CCUVAL4_CH1_out              ),
    .CCM5                 ( bf_CCM5_CH1_out                 ),
    .CCUVAL5_flipflop_en  ( bf_CCUVAL5_CH1_flipflop_en      ),
    .CCUVAL5_flipflop_in  ( bf_CCUVAL5_CH1_flipflop_in      ),
    .CCUVAL5_in           ( bf_CCUVAL5_CH1_out              ),
    .HCLK_i               ( HCLK_i                          ),
    .HRESET_n_i           ( HRESET_n_i                      ),
    .MAXVAL_flipflop_out  ( bf_MAXVAL_CH1_flipflop_out      ),
    .ACTVAL_flipflop_out  ( bf_ACTVAL_CH1_flipflop_out      ),
    .ACTVAL_out           ( bf_ACTVAL_CH1_in                ),
    .ACTVAL_wr            ( bf_ACTVAL_CH1_peripheral_wr_en  ),
    .OvfInt               ( TIM1_OvfInt                     ),
    .CCUVAL0_flipflop_out ( bf_CCUVAL0_CH1_flipflop_out     ),
    .CCUVAL0_out          ( bf_CCUVAL0_CH1_in               ),
    .CCUVAL0_wr           ( bf_CCUVAL0_CH1_peripheral_wr_en ),
    .ExtComp0             ( TIM1_CCU0_ExtComp               ),
    .CCUVAL1_flipflop_out ( bf_CCUVAL1_CH1_flipflop_out     ),
    .CCUVAL1_out          ( bf_CCUVAL1_CH1_in               ),
    .CCUVAL1_wr           ( bf_CCUVAL1_CH1_peripheral_wr_en ),
    .ExtComp1             ( TIM1_CCU1_ExtComp               ),
    .CCUVAL2_flipflop_out ( bf_CCUVAL2_CH1_flipflop_out     ),
    .CCUVAL2_out          ( bf_CCUVAL2_CH1_in               ),
    .CCUVAL2_wr           ( bf_CCUVAL2_CH1_peripheral_wr_en ),
    .ExtComp2             ( TIM1_CCU2_ExtComp               ),
    .CCUVAL3_flipflop_out ( bf_CCUVAL3_CH1_flipflop_out     ),
    .CCUVAL3_out          ( bf_CCUVAL3_CH1_in               ),
    .CCUVAL3_wr           ( bf_CCUVAL3_CH1_peripheral_wr_en ),
    .ExtComp3             ( TIM1_CCU3_ExtComp               ),
    .CCUVAL4_flipflop_out ( bf_CCUVAL4_CH1_flipflop_out     ),
    .CCUVAL4_out          ( bf_CCUVAL4_CH1_in               ),
    .CCUVAL4_wr           ( bf_CCUVAL4_CH1_peripheral_wr_en ),
    .ExtComp4             ( TIM1_CCU4_ExtComp               ),
    .CCUVAL5_flipflop_out ( bf_CCUVAL5_CH1_flipflop_out     ),
    .CCUVAL5_out          ( bf_CCUVAL5_CH1_in               ),
    .CCUVAL5_wr           ( bf_CCUVAL5_CH1_peripheral_wr_en ),
    .ExtComp5             ( TIM1_CCU5_ExtComp               )
);

tc_soc_timer_timer_TimerChannel_0 comp_TimerChannel_0(
    .MAXVAL_flipflop_en   ( bf_MAXVAL_CH0_flipflop_en       ),
    .MAXVAL_flipflop_in   ( bf_MAXVAL_CH0_flipflop_in       ),
    .MAXVAL_in            ( bf_MAXVAL_CH0_out               ),
    .ResIM                ( bf_ResIM_CH0_out                ),
    .ExtRes               ( TIM0_ExtRes                     ),
    .ExtCnt               ( TIM0_ExtCnt                     ),
    .CntIM                ( bf_CntIM_CH0_out                ),
    .ExtCap0              ( TIM0_CCU0_ExtCap                ),
    .CapIM0               ( bf_CapIM0_CH0_out               ),
    .ACTVAL_flipflop_en   ( bf_ACTVAL_CH0_flipflop_en       ),
    .ACTVAL_flipflop_in   ( bf_ACTVAL_CH0_flipflop_in       ),
    .ACTVAL_in            ( bf_ACTVAL_CH0_out               ),
    .TimEn                ( bf_TimEn_CH0_out                ),
    .OvfIntRes            ( TIM0_OvfIntRes                  ),
    .OvfIntEn             ( bf_OvfIntEn_CH0_out             ),
    .CCM0                 ( bf_CCM0_CH0_out                 ),
    .CCUVAL0_flipflop_en  ( bf_CCUVAL0_CH0_flipflop_en      ),
    .CCUVAL0_flipflop_in  ( bf_CCUVAL0_CH0_flipflop_in      ),
    .CCUVAL0_in           ( bf_CCUVAL0_CH0_out              ),
    .HCLK_i               ( HCLK_i                          ),
    .HRESET_n_i           ( HRESET_n_i                      ),
    .MAXVAL_flipflop_out  ( bf_MAXVAL_CH0_flipflop_out      ),
    .ACTVAL_flipflop_out  ( bf_ACTVAL_CH0_flipflop_out      ),
    .ACTVAL_out           ( bf_ACTVAL_CH0_in                ),
    .ACTVAL_wr            ( bf_ACTVAL_CH0_peripheral_wr_en  ),
    .OvfInt               ( TIM0_OvfInt                     ),
    .CCUVAL0_flipflop_out ( bf_CCUVAL0_CH0_flipflop_out     ),
    .CCUVAL0_out          ( bf_CCUVAL0_CH0_in               ),
    .CCUVAL0_wr           ( bf_CCUVAL0_CH0_peripheral_wr_en ),
    .ExtComp0             ( TIM0_CCU0_ExtComp               )
);


endmodule

