/* ===============================================================
Copyright 2026, Infineon Technologies AG or an 
affiliate of Infineon Technologies AG.  All rights reserved.
 
This software, associated documentation and materials ("Software") is owned by
Infineon Technologies AG or one of its affiliates ("Infineon") and is 
protected by and subject to worldwide patent protection (United States and 
foreign), United States copyright laws and international treaty provisions. 
Therefore, you may use this Software only as provided in the license agreement
accompanying the software package from which you obtained this 
Software ("EULA"). If no EULA applies, then any reproduction, modification, 
translation, compilation, or representation of this Software is prohibited 
without the express written permission of Infineon.
 
Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF 
ANY KIND, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, 
NONINFRINGEMENT, IMPLIED WARRANTIES OF  MERCHANTABILITY AND
FITNESS FOR A PARTICULAR PURPOSE.  Infineon reserves the right to make
changes to the Software without notice. Infineon does not assume any liability
arising out of the application or use of the Software or any product or 
circuit described in the Software. Infineon does not authorize its products 
for use in any products where a malfunction or failure of the Infineon product 
may reasonably be expected to result in significant property damage, injury or
death ("High Risk Product").  By including Infineon 's product in a High Risk 
Product, the manufacturer of such system or application assumes all risk of 
such use and in doing so agrees to indemnify Infineon against all liability.

 ===============================================================
*/ 
// File : tc_soc_timer.sv 
// Author : tahiraga 
// Date : 15:07:02    25/09/2026 
// Revision :  
// =============================================================== 
// Description : 
/*
---- Auto Generated by MetaRTL , a MetaGen application
---- Contact: ParitoshKumar.Sinha@infineon.com
---- Contact: Yash.Ranjan@infineon.com
===============================================================
*/


module tc_soc_timer (
    output logic  TIM1_CCU5_ExtComp,
    input logic  TIM0_CCU0_ExtCap,
    output logic  TIM1_CCU2_ExtComp,
    output logic  TIM1_CCU0_ExtComp,
    input logic  TIM1_CCU3_ExtCap,
    input logic  TIM1_CCU4_ExtCap,
    input logic  TIM1_CCU1_ExtCap,
    output logic  TIM1_CCU3_ExtComp,
    output logic  TIM1_CCU4_ExtComp,
    output logic  TIM0_CCU0_ExtComp,
    input logic  TIM1_CCU0_ExtCap,
    output logic  TIM1_CCU1_ExtComp,
    input logic  TIM0_ExtRes,
    input logic  TIM1_ExtCnt,
    input logic  TIM0_OvfIntRes,
    input logic  TIM0_ExtCnt,
    input logic  TIM1_OvfIntRes,
    output logic  TIM0_OvfInt,
    input logic  TIM1_ExtRes,
    input logic  TIM1_CCU2_ExtCap,
    output logic  TIM1_OvfInt,
    input logic  TIM1_CCU5_ExtCap,
    input logic  [31:0] SX_AHB_HADDR,
    input logic  SX_AHB_HREADY,
    output logic  [31:0] SX_AHB_HRDATA,
    input logic  SX_AHB_HSEL,
    input logic  SX_AHB_HWRITE,
    input logic  [31:0] SX_AHB_HWDATA,
    input logic  [1:0] SX_AHB_HTRANS,
    input logic  [2:0] SX_AHB_HSIZE,
    input logic  [3:0] SX_AHB_HPROT,
    input logic  [2:0] SX_AHB_HBURST,
    input logic  SX_AHB_HMASTLOCK,
    output logic  SX_AHB_HREADYOUT,
    output logic  SX_AHB_HRESP,
    input logic  HCLK_i,
    input logic  HRESET_n_i
);

logic   Reg_IF_TimerCSC_BF_bf_TimEn_CH0_out_s;
logic   [2:0] Reg_IF_TimerCSC_BF_bf_ResIM_CH0_out_s;
logic   [2:0] Reg_IF_TimerCSC_BF_bf_CntIM_CH0_out_s;
logic   Reg_IF_TimerCSC_BF_bf_OvfIntEn_CH0_out_s;
logic   [31:0] Reg_IF_TimerCSC_BF_bf_ACTVAL_CH0_out_s;
logic   [31:0] Reg_IF_TimerCSC_BF_bf_ACTVAL_CH0_flipflop_in_s;
logic   Reg_IF_TimerCSC_BF_bf_ACTVAL_CH0_flipflop_en_s;
logic   [31:0] Reg_IF_TimerCSC_BF_bf_MAXVAL_CH0_out_s;
logic   [31:0] Reg_IF_TimerCSC_BF_bf_MAXVAL_CH0_flipflop_in_s;
logic   Reg_IF_TimerCSC_BF_bf_MAXVAL_CH0_flipflop_en_s;
logic   [2:0] Reg_IF_TimerCSC_BF_bf_CCM0_CH0_out_s;
logic   [2:0] Reg_IF_TimerCSC_BF_bf_CapIM0_CH0_out_s;
logic   [31:0] Reg_IF_TimerCSC_BF_bf_CCUVAL0_CH0_out_s;
logic   [31:0] Reg_IF_TimerCSC_BF_bf_CCUVAL0_CH0_flipflop_in_s;
logic   Reg_IF_TimerCSC_BF_bf_CCUVAL0_CH0_flipflop_en_s;
logic   Reg_IF_TimerCSC_BF_bf_TimEn_CH1_out_s;
logic   [2:0] Reg_IF_TimerCSC_BF_bf_ResIM_CH1_out_s;
logic   [2:0] Reg_IF_TimerCSC_BF_bf_CntIM_CH1_out_s;
logic   Reg_IF_TimerCSC_BF_bf_OvfIntEn_CH1_out_s;
logic   [31:0] Reg_IF_TimerCSC_BF_bf_ACTVAL_CH1_out_s;
logic   [31:0] Reg_IF_TimerCSC_BF_bf_ACTVAL_CH1_flipflop_in_s;
logic   Reg_IF_TimerCSC_BF_bf_ACTVAL_CH1_flipflop_en_s;
logic   [31:0] Reg_IF_TimerCSC_BF_bf_MAXVAL_CH1_out_s;
logic   [31:0] Reg_IF_TimerCSC_BF_bf_MAXVAL_CH1_flipflop_in_s;
logic   Reg_IF_TimerCSC_BF_bf_MAXVAL_CH1_flipflop_en_s;
logic   [2:0] Reg_IF_TimerCSC_BF_bf_CCM0_CH1_out_s;
logic   [2:0] Reg_IF_TimerCSC_BF_bf_CapIM0_CH1_out_s;
logic   [31:0] Reg_IF_TimerCSC_BF_bf_CCUVAL0_CH1_out_s;
logic   [31:0] Reg_IF_TimerCSC_BF_bf_CCUVAL0_CH1_flipflop_in_s;
logic   Reg_IF_TimerCSC_BF_bf_CCUVAL0_CH1_flipflop_en_s;
logic   [2:0] Reg_IF_TimerCSC_BF_bf_CCM1_CH1_out_s;
logic   [2:0] Reg_IF_TimerCSC_BF_bf_CapIM1_CH1_out_s;
logic   [31:0] Reg_IF_TimerCSC_BF_bf_CCUVAL1_CH1_out_s;
logic   [31:0] Reg_IF_TimerCSC_BF_bf_CCUVAL1_CH1_flipflop_in_s;
logic   Reg_IF_TimerCSC_BF_bf_CCUVAL1_CH1_flipflop_en_s;
logic   [2:0] Reg_IF_TimerCSC_BF_bf_CCM2_CH1_out_s;
logic   [2:0] Reg_IF_TimerCSC_BF_bf_CapIM2_CH1_out_s;
logic   [31:0] Reg_IF_TimerCSC_BF_bf_CCUVAL2_CH1_out_s;
logic   [31:0] Reg_IF_TimerCSC_BF_bf_CCUVAL2_CH1_flipflop_in_s;
logic   Reg_IF_TimerCSC_BF_bf_CCUVAL2_CH1_flipflop_en_s;
logic   [2:0] Reg_IF_TimerCSC_BF_bf_CCM3_CH1_out_s;
logic   [2:0] Reg_IF_TimerCSC_BF_bf_CapIM3_CH1_out_s;
logic   [31:0] Reg_IF_TimerCSC_BF_bf_CCUVAL3_CH1_out_s;
logic   [31:0] Reg_IF_TimerCSC_BF_bf_CCUVAL3_CH1_flipflop_in_s;
logic   Reg_IF_TimerCSC_BF_bf_CCUVAL3_CH1_flipflop_en_s;
logic   [2:0] Reg_IF_TimerCSC_BF_bf_CCM4_CH1_out_s;
logic   [2:0] Reg_IF_TimerCSC_BF_bf_CapIM4_CH1_out_s;
logic   [31:0] Reg_IF_TimerCSC_BF_bf_CCUVAL4_CH1_out_s;
logic   [31:0] Reg_IF_TimerCSC_BF_bf_CCUVAL4_CH1_flipflop_in_s;
logic   Reg_IF_TimerCSC_BF_bf_CCUVAL4_CH1_flipflop_en_s;
logic   [2:0] Reg_IF_TimerCSC_BF_bf_CCM5_CH1_out_s;
logic   [2:0] Reg_IF_TimerCSC_BF_bf_CapIM5_CH1_out_s;
logic   [31:0] Reg_IF_TimerCSC_BF_bf_CCUVAL5_CH1_out_s;
logic   [31:0] Reg_IF_TimerCSC_BF_bf_CCUVAL5_CH1_flipflop_in_s;
logic   Reg_IF_TimerCSC_BF_bf_CCUVAL5_CH1_flipflop_en_s;
logic   [31:0] timer_bf_ACTVAL_CH0_flipflop_out_s;
logic   [31:0] timer_bf_ACTVAL_CH0_in_s;
logic   timer_bf_ACTVAL_CH0_peripheral_wr_en_s;
logic   [31:0] timer_bf_MAXVAL_CH0_flipflop_out_s;
logic   [31:0] timer_bf_CCUVAL0_CH0_flipflop_out_s;
logic   [31:0] timer_bf_CCUVAL0_CH0_in_s;
logic   timer_bf_CCUVAL0_CH0_peripheral_wr_en_s;
logic   [31:0] timer_bf_ACTVAL_CH1_flipflop_out_s;
logic   [31:0] timer_bf_ACTVAL_CH1_in_s;
logic   timer_bf_ACTVAL_CH1_peripheral_wr_en_s;
logic   [31:0] timer_bf_MAXVAL_CH1_flipflop_out_s;
logic   [31:0] timer_bf_CCUVAL0_CH1_flipflop_out_s;
logic   [31:0] timer_bf_CCUVAL0_CH1_in_s;
logic   timer_bf_CCUVAL0_CH1_peripheral_wr_en_s;
logic   [31:0] timer_bf_CCUVAL1_CH1_flipflop_out_s;
logic   [31:0] timer_bf_CCUVAL1_CH1_in_s;
logic   timer_bf_CCUVAL1_CH1_peripheral_wr_en_s;
logic   [31:0] timer_bf_CCUVAL2_CH1_flipflop_out_s;
logic   [31:0] timer_bf_CCUVAL2_CH1_in_s;
logic   timer_bf_CCUVAL2_CH1_peripheral_wr_en_s;
logic   [31:0] timer_bf_CCUVAL3_CH1_flipflop_out_s;
logic   [31:0] timer_bf_CCUVAL3_CH1_in_s;
logic   timer_bf_CCUVAL3_CH1_peripheral_wr_en_s;
logic   [31:0] timer_bf_CCUVAL4_CH1_flipflop_out_s;
logic   [31:0] timer_bf_CCUVAL4_CH1_in_s;
logic   timer_bf_CCUVAL4_CH1_peripheral_wr_en_s;
logic   [31:0] timer_bf_CCUVAL5_CH1_flipflop_out_s;
logic   [31:0] timer_bf_CCUVAL5_CH1_in_s;
logic   timer_bf_CCUVAL5_CH1_peripheral_wr_en_s;

tc_soc_timer_Reg_IF comp_Reg_IF(
    .SX_AHB_HADDR                                ( SX_AHB_HADDR                                    ),
    .SX_AHB_HWDATA                               ( SX_AHB_HWDATA                                   ),
    .SX_AHB_HBURST                               ( SX_AHB_HBURST                                   ),
    .SX_AHB_HMASTLOCK                            ( SX_AHB_HMASTLOCK                                ),
    .SX_AHB_HPROT                                ( SX_AHB_HPROT                                    ),
    .SX_AHB_HSIZE                                ( SX_AHB_HSIZE                                    ),
    .SX_AHB_HTRANS                               ( SX_AHB_HTRANS                                   ),
    .SX_AHB_HWRITE                               ( SX_AHB_HWRITE                                   ),
    .SX_AHB_HSEL                                 ( SX_AHB_HSEL                                     ),
    .SX_AHB_HREADY                               ( SX_AHB_HREADY                                   ),
    .TimerCSC_BF_bf_ACTVAL_CH0_in                ( timer_bf_ACTVAL_CH0_in_s                        ),
    .TimerCSC_BF_bf_ACTVAL_CH0_peripheral_wr_en  ( timer_bf_ACTVAL_CH0_peripheral_wr_en_s          ),
    .TimerCSC_BF_bf_ACTVAL_CH0_flipflop_out      ( timer_bf_ACTVAL_CH0_flipflop_out_s              ),
    .TimerCSC_BF_bf_MAXVAL_CH0_flipflop_out      ( timer_bf_MAXVAL_CH0_flipflop_out_s              ),
    .TimerCSC_BF_bf_CCUVAL0_CH0_in               ( timer_bf_CCUVAL0_CH0_in_s                       ),
    .TimerCSC_BF_bf_CCUVAL0_CH0_peripheral_wr_en ( timer_bf_CCUVAL0_CH0_peripheral_wr_en_s         ),
    .TimerCSC_BF_bf_CCUVAL0_CH0_flipflop_out     ( timer_bf_CCUVAL0_CH0_flipflop_out_s             ),
    .TimerCSC_BF_bf_ACTVAL_CH1_in                ( timer_bf_ACTVAL_CH1_in_s                        ),
    .TimerCSC_BF_bf_ACTVAL_CH1_peripheral_wr_en  ( timer_bf_ACTVAL_CH1_peripheral_wr_en_s          ),
    .TimerCSC_BF_bf_ACTVAL_CH1_flipflop_out      ( timer_bf_ACTVAL_CH1_flipflop_out_s              ),
    .TimerCSC_BF_bf_MAXVAL_CH1_flipflop_out      ( timer_bf_MAXVAL_CH1_flipflop_out_s              ),
    .TimerCSC_BF_bf_CCUVAL0_CH1_in               ( timer_bf_CCUVAL0_CH1_in_s                       ),
    .TimerCSC_BF_bf_CCUVAL0_CH1_peripheral_wr_en ( timer_bf_CCUVAL0_CH1_peripheral_wr_en_s         ),
    .TimerCSC_BF_bf_CCUVAL0_CH1_flipflop_out     ( timer_bf_CCUVAL0_CH1_flipflop_out_s             ),
    .TimerCSC_BF_bf_CCUVAL1_CH1_in               ( timer_bf_CCUVAL1_CH1_in_s                       ),
    .TimerCSC_BF_bf_CCUVAL1_CH1_peripheral_wr_en ( timer_bf_CCUVAL1_CH1_peripheral_wr_en_s         ),
    .TimerCSC_BF_bf_CCUVAL1_CH1_flipflop_out     ( timer_bf_CCUVAL1_CH1_flipflop_out_s             ),
    .TimerCSC_BF_bf_CCUVAL2_CH1_in               ( timer_bf_CCUVAL2_CH1_in_s                       ),
    .TimerCSC_BF_bf_CCUVAL2_CH1_peripheral_wr_en ( timer_bf_CCUVAL2_CH1_peripheral_wr_en_s         ),
    .TimerCSC_BF_bf_CCUVAL2_CH1_flipflop_out     ( timer_bf_CCUVAL2_CH1_flipflop_out_s             ),
    .TimerCSC_BF_bf_CCUVAL3_CH1_in               ( timer_bf_CCUVAL3_CH1_in_s                       ),
    .TimerCSC_BF_bf_CCUVAL3_CH1_peripheral_wr_en ( timer_bf_CCUVAL3_CH1_peripheral_wr_en_s         ),
    .TimerCSC_BF_bf_CCUVAL3_CH1_flipflop_out     ( timer_bf_CCUVAL3_CH1_flipflop_out_s             ),
    .TimerCSC_BF_bf_CCUVAL4_CH1_in               ( timer_bf_CCUVAL4_CH1_in_s                       ),
    .TimerCSC_BF_bf_CCUVAL4_CH1_peripheral_wr_en ( timer_bf_CCUVAL4_CH1_peripheral_wr_en_s         ),
    .TimerCSC_BF_bf_CCUVAL4_CH1_flipflop_out     ( timer_bf_CCUVAL4_CH1_flipflop_out_s             ),
    .TimerCSC_BF_bf_CCUVAL5_CH1_in               ( timer_bf_CCUVAL5_CH1_in_s                       ),
    .TimerCSC_BF_bf_CCUVAL5_CH1_peripheral_wr_en ( timer_bf_CCUVAL5_CH1_peripheral_wr_en_s         ),
    .TimerCSC_BF_bf_CCUVAL5_CH1_flipflop_out     ( timer_bf_CCUVAL5_CH1_flipflop_out_s             ),
    .HCLK_i                                      ( HCLK_i                                          ),
    .HRESET_n_i                                  ( HRESET_n_i                                      ),
    .SX_AHB_HRDATA                               ( SX_AHB_HRDATA                                   ),
    .SX_AHB_HREADYOUT                            ( SX_AHB_HREADYOUT                                ),
    .SX_AHB_HRESP                                ( SX_AHB_HRESP                                    ),
    .TimerCSC_BF_bf_TimEn_CH0_out                ( Reg_IF_TimerCSC_BF_bf_TimEn_CH0_out_s           ),
    .TimerCSC_BF_bf_ResIM_CH0_out                ( Reg_IF_TimerCSC_BF_bf_ResIM_CH0_out_s           ),
    .TimerCSC_BF_bf_CntIM_CH0_out                ( Reg_IF_TimerCSC_BF_bf_CntIM_CH0_out_s           ),
    .TimerCSC_BF_bf_OvfIntEn_CH0_out             ( Reg_IF_TimerCSC_BF_bf_OvfIntEn_CH0_out_s        ),
    .TimerCSC_BF_bf_ACTVAL_CH0_out               ( Reg_IF_TimerCSC_BF_bf_ACTVAL_CH0_out_s          ),
    .TimerCSC_BF_bf_ACTVAL_CH0_flipflop_in       ( Reg_IF_TimerCSC_BF_bf_ACTVAL_CH0_flipflop_in_s  ),
    .TimerCSC_BF_bf_ACTVAL_CH0_flipflop_en       ( Reg_IF_TimerCSC_BF_bf_ACTVAL_CH0_flipflop_en_s  ),
    .TimerCSC_BF_bf_MAXVAL_CH0_out               ( Reg_IF_TimerCSC_BF_bf_MAXVAL_CH0_out_s          ),
    .TimerCSC_BF_bf_MAXVAL_CH0_flipflop_in       ( Reg_IF_TimerCSC_BF_bf_MAXVAL_CH0_flipflop_in_s  ),
    .TimerCSC_BF_bf_MAXVAL_CH0_flipflop_en       ( Reg_IF_TimerCSC_BF_bf_MAXVAL_CH0_flipflop_en_s  ),
    .TimerCSC_BF_bf_CCM0_CH0_out                 ( Reg_IF_TimerCSC_BF_bf_CCM0_CH0_out_s            ),
    .TimerCSC_BF_bf_CapIM0_CH0_out               ( Reg_IF_TimerCSC_BF_bf_CapIM0_CH0_out_s          ),
    .TimerCSC_BF_bf_CCUVAL0_CH0_out              ( Reg_IF_TimerCSC_BF_bf_CCUVAL0_CH0_out_s         ),
    .TimerCSC_BF_bf_CCUVAL0_CH0_flipflop_in      ( Reg_IF_TimerCSC_BF_bf_CCUVAL0_CH0_flipflop_in_s ),
    .TimerCSC_BF_bf_CCUVAL0_CH0_flipflop_en      ( Reg_IF_TimerCSC_BF_bf_CCUVAL0_CH0_flipflop_en_s ),
    .TimerCSC_BF_bf_TimEn_CH1_out                ( Reg_IF_TimerCSC_BF_bf_TimEn_CH1_out_s           ),
    .TimerCSC_BF_bf_ResIM_CH1_out                ( Reg_IF_TimerCSC_BF_bf_ResIM_CH1_out_s           ),
    .TimerCSC_BF_bf_CntIM_CH1_out                ( Reg_IF_TimerCSC_BF_bf_CntIM_CH1_out_s           ),
    .TimerCSC_BF_bf_OvfIntEn_CH1_out             ( Reg_IF_TimerCSC_BF_bf_OvfIntEn_CH1_out_s        ),
    .TimerCSC_BF_bf_ACTVAL_CH1_out               ( Reg_IF_TimerCSC_BF_bf_ACTVAL_CH1_out_s          ),
    .TimerCSC_BF_bf_ACTVAL_CH1_flipflop_in       ( Reg_IF_TimerCSC_BF_bf_ACTVAL_CH1_flipflop_in_s  ),
    .TimerCSC_BF_bf_ACTVAL_CH1_flipflop_en       ( Reg_IF_TimerCSC_BF_bf_ACTVAL_CH1_flipflop_en_s  ),
    .TimerCSC_BF_bf_MAXVAL_CH1_out               ( Reg_IF_TimerCSC_BF_bf_MAXVAL_CH1_out_s          ),
    .TimerCSC_BF_bf_MAXVAL_CH1_flipflop_in       ( Reg_IF_TimerCSC_BF_bf_MAXVAL_CH1_flipflop_in_s  ),
    .TimerCSC_BF_bf_MAXVAL_CH1_flipflop_en       ( Reg_IF_TimerCSC_BF_bf_MAXVAL_CH1_flipflop_en_s  ),
    .TimerCSC_BF_bf_CCM0_CH1_out                 ( Reg_IF_TimerCSC_BF_bf_CCM0_CH1_out_s            ),
    .TimerCSC_BF_bf_CapIM0_CH1_out               ( Reg_IF_TimerCSC_BF_bf_CapIM0_CH1_out_s          ),
    .TimerCSC_BF_bf_CCUVAL0_CH1_out              ( Reg_IF_TimerCSC_BF_bf_CCUVAL0_CH1_out_s         ),
    .TimerCSC_BF_bf_CCUVAL0_CH1_flipflop_in      ( Reg_IF_TimerCSC_BF_bf_CCUVAL0_CH1_flipflop_in_s ),
    .TimerCSC_BF_bf_CCUVAL0_CH1_flipflop_en      ( Reg_IF_TimerCSC_BF_bf_CCUVAL0_CH1_flipflop_en_s ),
    .TimerCSC_BF_bf_CCM1_CH1_out                 ( Reg_IF_TimerCSC_BF_bf_CCM1_CH1_out_s            ),
    .TimerCSC_BF_bf_CapIM1_CH1_out               ( Reg_IF_TimerCSC_BF_bf_CapIM1_CH1_out_s          ),
    .TimerCSC_BF_bf_CCUVAL1_CH1_out              ( Reg_IF_TimerCSC_BF_bf_CCUVAL1_CH1_out_s         ),
    .TimerCSC_BF_bf_CCUVAL1_CH1_flipflop_in      ( Reg_IF_TimerCSC_BF_bf_CCUVAL1_CH1_flipflop_in_s ),
    .TimerCSC_BF_bf_CCUVAL1_CH1_flipflop_en      ( Reg_IF_TimerCSC_BF_bf_CCUVAL1_CH1_flipflop_en_s ),
    .TimerCSC_BF_bf_CCM2_CH1_out                 ( Reg_IF_TimerCSC_BF_bf_CCM2_CH1_out_s            ),
    .TimerCSC_BF_bf_CapIM2_CH1_out               ( Reg_IF_TimerCSC_BF_bf_CapIM2_CH1_out_s          ),
    .TimerCSC_BF_bf_CCUVAL2_CH1_out              ( Reg_IF_TimerCSC_BF_bf_CCUVAL2_CH1_out_s         ),
    .TimerCSC_BF_bf_CCUVAL2_CH1_flipflop_in      ( Reg_IF_TimerCSC_BF_bf_CCUVAL2_CH1_flipflop_in_s ),
    .TimerCSC_BF_bf_CCUVAL2_CH1_flipflop_en      ( Reg_IF_TimerCSC_BF_bf_CCUVAL2_CH1_flipflop_en_s ),
    .TimerCSC_BF_bf_CCM3_CH1_out                 ( Reg_IF_TimerCSC_BF_bf_CCM3_CH1_out_s            ),
    .TimerCSC_BF_bf_CapIM3_CH1_out               ( Reg_IF_TimerCSC_BF_bf_CapIM3_CH1_out_s          ),
    .TimerCSC_BF_bf_CCUVAL3_CH1_out              ( Reg_IF_TimerCSC_BF_bf_CCUVAL3_CH1_out_s         ),
    .TimerCSC_BF_bf_CCUVAL3_CH1_flipflop_in      ( Reg_IF_TimerCSC_BF_bf_CCUVAL3_CH1_flipflop_in_s ),
    .TimerCSC_BF_bf_CCUVAL3_CH1_flipflop_en      ( Reg_IF_TimerCSC_BF_bf_CCUVAL3_CH1_flipflop_en_s ),
    .TimerCSC_BF_bf_CCM4_CH1_out                 ( Reg_IF_TimerCSC_BF_bf_CCM4_CH1_out_s            ),
    .TimerCSC_BF_bf_CapIM4_CH1_out               ( Reg_IF_TimerCSC_BF_bf_CapIM4_CH1_out_s          ),
    .TimerCSC_BF_bf_CCUVAL4_CH1_out              ( Reg_IF_TimerCSC_BF_bf_CCUVAL4_CH1_out_s         ),
    .TimerCSC_BF_bf_CCUVAL4_CH1_flipflop_in      ( Reg_IF_TimerCSC_BF_bf_CCUVAL4_CH1_flipflop_in_s ),
    .TimerCSC_BF_bf_CCUVAL4_CH1_flipflop_en      ( Reg_IF_TimerCSC_BF_bf_CCUVAL4_CH1_flipflop_en_s ),
    .TimerCSC_BF_bf_CCM5_CH1_out                 ( Reg_IF_TimerCSC_BF_bf_CCM5_CH1_out_s            ),
    .TimerCSC_BF_bf_CapIM5_CH1_out               ( Reg_IF_TimerCSC_BF_bf_CapIM5_CH1_out_s          ),
    .TimerCSC_BF_bf_CCUVAL5_CH1_out              ( Reg_IF_TimerCSC_BF_bf_CCUVAL5_CH1_out_s         ),
    .TimerCSC_BF_bf_CCUVAL5_CH1_flipflop_in      ( Reg_IF_TimerCSC_BF_bf_CCUVAL5_CH1_flipflop_in_s ),
    .TimerCSC_BF_bf_CCUVAL5_CH1_flipflop_en      ( Reg_IF_TimerCSC_BF_bf_CCUVAL5_CH1_flipflop_en_s )
);

tc_soc_timer_timer comp_timer(
    .TIM0_ExtRes                     ( TIM0_ExtRes                                     ),
    .TIM0_ExtCnt                     ( TIM0_ExtCnt                                     ),
    .TIM0_OvfIntRes                  ( TIM0_OvfIntRes                                  ),
    .TIM0_CCU0_ExtCap                ( TIM0_CCU0_ExtCap                                ),
    .TIM1_ExtRes                     ( TIM1_ExtRes                                     ),
    .TIM1_ExtCnt                     ( TIM1_ExtCnt                                     ),
    .TIM1_OvfIntRes                  ( TIM1_OvfIntRes                                  ),
    .TIM1_CCU0_ExtCap                ( TIM1_CCU0_ExtCap                                ),
    .TIM1_CCU1_ExtCap                ( TIM1_CCU1_ExtCap                                ),
    .TIM1_CCU2_ExtCap                ( TIM1_CCU2_ExtCap                                ),
    .TIM1_CCU3_ExtCap                ( TIM1_CCU3_ExtCap                                ),
    .TIM1_CCU4_ExtCap                ( TIM1_CCU4_ExtCap                                ),
    .TIM1_CCU5_ExtCap                ( TIM1_CCU5_ExtCap                                ),
    .bf_TimEn_CH0_out                ( Reg_IF_TimerCSC_BF_bf_TimEn_CH0_out_s           ),
    .bf_OvfIntEn_CH0_out             ( Reg_IF_TimerCSC_BF_bf_OvfIntEn_CH0_out_s        ),
    .bf_ResIM_CH0_out                ( Reg_IF_TimerCSC_BF_bf_ResIM_CH0_out_s           ),
    .bf_CntIM_CH0_out                ( Reg_IF_TimerCSC_BF_bf_CntIM_CH0_out_s           ),
    .bf_ACTVAL_CH0_flipflop_in       ( Reg_IF_TimerCSC_BF_bf_ACTVAL_CH0_flipflop_in_s  ),
    .bf_ACTVAL_CH0_flipflop_en       ( Reg_IF_TimerCSC_BF_bf_ACTVAL_CH0_flipflop_en_s  ),
    .bf_ACTVAL_CH0_out               ( Reg_IF_TimerCSC_BF_bf_ACTVAL_CH0_out_s          ),
    .bf_MAXVAL_CH0_flipflop_in       ( Reg_IF_TimerCSC_BF_bf_MAXVAL_CH0_flipflop_in_s  ),
    .bf_MAXVAL_CH0_flipflop_en       ( Reg_IF_TimerCSC_BF_bf_MAXVAL_CH0_flipflop_en_s  ),
    .bf_MAXVAL_CH0_out               ( Reg_IF_TimerCSC_BF_bf_MAXVAL_CH0_out_s          ),
    .bf_CCUVAL0_CH0_flipflop_in      ( Reg_IF_TimerCSC_BF_bf_CCUVAL0_CH0_flipflop_in_s ),
    .bf_CCUVAL0_CH0_flipflop_en      ( Reg_IF_TimerCSC_BF_bf_CCUVAL0_CH0_flipflop_en_s ),
    .bf_CCUVAL0_CH0_out              ( Reg_IF_TimerCSC_BF_bf_CCUVAL0_CH0_out_s         ),
    .bf_CapIM0_CH0_out               ( Reg_IF_TimerCSC_BF_bf_CapIM0_CH0_out_s          ),
    .bf_CCM0_CH0_out                 ( Reg_IF_TimerCSC_BF_bf_CCM0_CH0_out_s            ),
    .bf_TimEn_CH1_out                ( Reg_IF_TimerCSC_BF_bf_TimEn_CH1_out_s           ),
    .bf_OvfIntEn_CH1_out             ( Reg_IF_TimerCSC_BF_bf_OvfIntEn_CH1_out_s        ),
    .bf_ResIM_CH1_out                ( Reg_IF_TimerCSC_BF_bf_ResIM_CH1_out_s           ),
    .bf_CntIM_CH1_out                ( Reg_IF_TimerCSC_BF_bf_CntIM_CH1_out_s           ),
    .bf_ACTVAL_CH1_flipflop_in       ( Reg_IF_TimerCSC_BF_bf_ACTVAL_CH1_flipflop_in_s  ),
    .bf_ACTVAL_CH1_flipflop_en       ( Reg_IF_TimerCSC_BF_bf_ACTVAL_CH1_flipflop_en_s  ),
    .bf_ACTVAL_CH1_out               ( Reg_IF_TimerCSC_BF_bf_ACTVAL_CH1_out_s          ),
    .bf_MAXVAL_CH1_flipflop_in       ( Reg_IF_TimerCSC_BF_bf_MAXVAL_CH1_flipflop_in_s  ),
    .bf_MAXVAL_CH1_flipflop_en       ( Reg_IF_TimerCSC_BF_bf_MAXVAL_CH1_flipflop_en_s  ),
    .bf_MAXVAL_CH1_out               ( Reg_IF_TimerCSC_BF_bf_MAXVAL_CH1_out_s          ),
    .bf_CCUVAL0_CH1_flipflop_in      ( Reg_IF_TimerCSC_BF_bf_CCUVAL0_CH1_flipflop_in_s ),
    .bf_CCUVAL0_CH1_flipflop_en      ( Reg_IF_TimerCSC_BF_bf_CCUVAL0_CH1_flipflop_en_s ),
    .bf_CCUVAL0_CH1_out              ( Reg_IF_TimerCSC_BF_bf_CCUVAL0_CH1_out_s         ),
    .bf_CapIM0_CH1_out               ( Reg_IF_TimerCSC_BF_bf_CapIM0_CH1_out_s          ),
    .bf_CCM0_CH1_out                 ( Reg_IF_TimerCSC_BF_bf_CCM0_CH1_out_s            ),
    .bf_CCUVAL1_CH1_flipflop_in      ( Reg_IF_TimerCSC_BF_bf_CCUVAL1_CH1_flipflop_in_s ),
    .bf_CCUVAL1_CH1_flipflop_en      ( Reg_IF_TimerCSC_BF_bf_CCUVAL1_CH1_flipflop_en_s ),
    .bf_CCUVAL1_CH1_out              ( Reg_IF_TimerCSC_BF_bf_CCUVAL1_CH1_out_s         ),
    .bf_CapIM1_CH1_out               ( Reg_IF_TimerCSC_BF_bf_CapIM1_CH1_out_s          ),
    .bf_CCM1_CH1_out                 ( Reg_IF_TimerCSC_BF_bf_CCM1_CH1_out_s            ),
    .bf_CCUVAL2_CH1_flipflop_in      ( Reg_IF_TimerCSC_BF_bf_CCUVAL2_CH1_flipflop_in_s ),
    .bf_CCUVAL2_CH1_flipflop_en      ( Reg_IF_TimerCSC_BF_bf_CCUVAL2_CH1_flipflop_en_s ),
    .bf_CCUVAL2_CH1_out              ( Reg_IF_TimerCSC_BF_bf_CCUVAL2_CH1_out_s         ),
    .bf_CapIM2_CH1_out               ( Reg_IF_TimerCSC_BF_bf_CapIM2_CH1_out_s          ),
    .bf_CCM2_CH1_out                 ( Reg_IF_TimerCSC_BF_bf_CCM2_CH1_out_s            ),
    .bf_CCUVAL3_CH1_flipflop_in      ( Reg_IF_TimerCSC_BF_bf_CCUVAL3_CH1_flipflop_in_s ),
    .bf_CCUVAL3_CH1_flipflop_en      ( Reg_IF_TimerCSC_BF_bf_CCUVAL3_CH1_flipflop_en_s ),
    .bf_CCUVAL3_CH1_out              ( Reg_IF_TimerCSC_BF_bf_CCUVAL3_CH1_out_s         ),
    .bf_CapIM3_CH1_out               ( Reg_IF_TimerCSC_BF_bf_CapIM3_CH1_out_s          ),
    .bf_CCM3_CH1_out                 ( Reg_IF_TimerCSC_BF_bf_CCM3_CH1_out_s            ),
    .bf_CCUVAL4_CH1_flipflop_in      ( Reg_IF_TimerCSC_BF_bf_CCUVAL4_CH1_flipflop_in_s ),
    .bf_CCUVAL4_CH1_flipflop_en      ( Reg_IF_TimerCSC_BF_bf_CCUVAL4_CH1_flipflop_en_s ),
    .bf_CCUVAL4_CH1_out              ( Reg_IF_TimerCSC_BF_bf_CCUVAL4_CH1_out_s         ),
    .bf_CapIM4_CH1_out               ( Reg_IF_TimerCSC_BF_bf_CapIM4_CH1_out_s          ),
    .bf_CCM4_CH1_out                 ( Reg_IF_TimerCSC_BF_bf_CCM4_CH1_out_s            ),
    .bf_CCUVAL5_CH1_flipflop_in      ( Reg_IF_TimerCSC_BF_bf_CCUVAL5_CH1_flipflop_in_s ),
    .bf_CCUVAL5_CH1_flipflop_en      ( Reg_IF_TimerCSC_BF_bf_CCUVAL5_CH1_flipflop_en_s ),
    .bf_CCUVAL5_CH1_out              ( Reg_IF_TimerCSC_BF_bf_CCUVAL5_CH1_out_s         ),
    .bf_CapIM5_CH1_out               ( Reg_IF_TimerCSC_BF_bf_CapIM5_CH1_out_s          ),
    .bf_CCM5_CH1_out                 ( Reg_IF_TimerCSC_BF_bf_CCM5_CH1_out_s            ),
    .HCLK_i                          ( HCLK_i                                          ),
    .HRESET_n_i                      ( HRESET_n_i                                      ),
    .TIM0_OvfInt                     ( TIM0_OvfInt                                     ),
    .TIM0_CCU0_ExtComp               ( TIM0_CCU0_ExtComp                               ),
    .TIM1_OvfInt                     ( TIM1_OvfInt                                     ),
    .TIM1_CCU0_ExtComp               ( TIM1_CCU0_ExtComp                               ),
    .TIM1_CCU1_ExtComp               ( TIM1_CCU1_ExtComp                               ),
    .TIM1_CCU2_ExtComp               ( TIM1_CCU2_ExtComp                               ),
    .TIM1_CCU3_ExtComp               ( TIM1_CCU3_ExtComp                               ),
    .TIM1_CCU4_ExtComp               ( TIM1_CCU4_ExtComp                               ),
    .TIM1_CCU5_ExtComp               ( TIM1_CCU5_ExtComp                               ),
    .bf_ACTVAL_CH0_flipflop_out      ( timer_bf_ACTVAL_CH0_flipflop_out_s              ),
    .bf_ACTVAL_CH0_in                ( timer_bf_ACTVAL_CH0_in_s                        ),
    .bf_ACTVAL_CH0_peripheral_wr_en  ( timer_bf_ACTVAL_CH0_peripheral_wr_en_s          ),
    .bf_MAXVAL_CH0_flipflop_out      ( timer_bf_MAXVAL_CH0_flipflop_out_s              ),
    .bf_CCUVAL0_CH0_flipflop_out     ( timer_bf_CCUVAL0_CH0_flipflop_out_s             ),
    .bf_CCUVAL0_CH0_in               ( timer_bf_CCUVAL0_CH0_in_s                       ),
    .bf_CCUVAL0_CH0_peripheral_wr_en ( timer_bf_CCUVAL0_CH0_peripheral_wr_en_s         ),
    .bf_ACTVAL_CH1_flipflop_out      ( timer_bf_ACTVAL_CH1_flipflop_out_s              ),
    .bf_ACTVAL_CH1_in                ( timer_bf_ACTVAL_CH1_in_s                        ),
    .bf_ACTVAL_CH1_peripheral_wr_en  ( timer_bf_ACTVAL_CH1_peripheral_wr_en_s          ),
    .bf_MAXVAL_CH1_flipflop_out      ( timer_bf_MAXVAL_CH1_flipflop_out_s              ),
    .bf_CCUVAL0_CH1_flipflop_out     ( timer_bf_CCUVAL0_CH1_flipflop_out_s             ),
    .bf_CCUVAL0_CH1_in               ( timer_bf_CCUVAL0_CH1_in_s                       ),
    .bf_CCUVAL0_CH1_peripheral_wr_en ( timer_bf_CCUVAL0_CH1_peripheral_wr_en_s         ),
    .bf_CCUVAL1_CH1_flipflop_out     ( timer_bf_CCUVAL1_CH1_flipflop_out_s             ),
    .bf_CCUVAL1_CH1_in               ( timer_bf_CCUVAL1_CH1_in_s                       ),
    .bf_CCUVAL1_CH1_peripheral_wr_en ( timer_bf_CCUVAL1_CH1_peripheral_wr_en_s         ),
    .bf_CCUVAL2_CH1_flipflop_out     ( timer_bf_CCUVAL2_CH1_flipflop_out_s             ),
    .bf_CCUVAL2_CH1_in               ( timer_bf_CCUVAL2_CH1_in_s                       ),
    .bf_CCUVAL2_CH1_peripheral_wr_en ( timer_bf_CCUVAL2_CH1_peripheral_wr_en_s         ),
    .bf_CCUVAL3_CH1_flipflop_out     ( timer_bf_CCUVAL3_CH1_flipflop_out_s             ),
    .bf_CCUVAL3_CH1_in               ( timer_bf_CCUVAL3_CH1_in_s                       ),
    .bf_CCUVAL3_CH1_peripheral_wr_en ( timer_bf_CCUVAL3_CH1_peripheral_wr_en_s         ),
    .bf_CCUVAL4_CH1_flipflop_out     ( timer_bf_CCUVAL4_CH1_flipflop_out_s             ),
    .bf_CCUVAL4_CH1_in               ( timer_bf_CCUVAL4_CH1_in_s                       ),
    .bf_CCUVAL4_CH1_peripheral_wr_en ( timer_bf_CCUVAL4_CH1_peripheral_wr_en_s         ),
    .bf_CCUVAL5_CH1_flipflop_out     ( timer_bf_CCUVAL5_CH1_flipflop_out_s             ),
    .bf_CCUVAL5_CH1_in               ( timer_bf_CCUVAL5_CH1_in_s                       ),
    .bf_CCUVAL5_CH1_peripheral_wr_en ( timer_bf_CCUVAL5_CH1_peripheral_wr_en_s         )
);


endmodule

