/* ===============================================================
Copyright 2026, Infineon Technologies AG or an 
affiliate of Infineon Technologies AG.  All rights reserved.
 
This software, associated documentation and materials ("Software") is owned by
Infineon Technologies AG or one of its affiliates ("Infineon") and is 
protected by and subject to worldwide patent protection (United States and 
foreign), United States copyright laws and international treaty provisions. 
Therefore, you may use this Software only as provided in the license agreement
accompanying the software package from which you obtained this 
Software ("EULA"). If no EULA applies, then any reproduction, modification, 
translation, compilation, or representation of this Software is prohibited 
without the express written permission of Infineon.
 
Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF 
ANY KIND, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, 
NONINFRINGEMENT, IMPLIED WARRANTIES OF  MERCHANTABILITY AND
FITNESS FOR A PARTICULAR PURPOSE.  Infineon reserves the right to make
changes to the Software without notice. Infineon does not assume any liability
arising out of the application or use of the Software or any product or 
circuit described in the Software. Infineon does not authorize its products 
for use in any products where a malfunction or failure of the Infineon product 
may reasonably be expected to result in significant property damage, injury or
death ("High Risk Product").  By including Infineon 's product in a High Risk 
Product, the manufacturer of such system or application assumes all risk of 
such use and in doing so agrees to indemnify Infineon against all liability.

 ===============================================================
*/ 
// File : tc_soc_timer_Reg_IF_Top_CSC_Top_CSC_default_interface_Top_CSC_default_interface_WriteCircuit.sv 
// Author : tahiraga 
// Date : 15:07:01    25/09/2026 
// Revision :  
// =============================================================== 
// Description : 
/*
---- Auto Generated by MetaRTL , a MetaGen application
---- Contact: ParitoshKumar.Sinha@infineon.com
---- Contact: Yash.Ranjan@infineon.com
===============================================================
*/


module tc_soc_timer_Reg_IF_Top_CSC_Top_CSC_default_interface_Top_CSC_default_interface_WriteCircuit (
    input logic  [31:0] default_interface_w_c_data_in,
    output logic  Input_of_Reg_bf_OvfIntEn_CH0,
    output logic  Enable_of_Reg_bf_OvfIntEn_CH0,
    input logic  dc_land_for_Reg_bf_OvfIntEn_CH0_CH0_CTRLSTAT,
    output logic  [2:0] Input_of_Reg_bf_CntIM_CH0,
    output logic  Enable_of_Reg_bf_CntIM_CH0,
    input logic  dc_land_for_Reg_bf_CntIM_CH0_CH0_CTRLSTAT,
    output logic  [2:0] Input_of_Reg_bf_ResIM_CH0,
    output logic  Enable_of_Reg_bf_ResIM_CH0,
    input logic  dc_land_for_Reg_bf_ResIM_CH0_CH0_CTRLSTAT,
    output logic  Input_of_Reg_bf_TimEn_CH0,
    output logic  Enable_of_Reg_bf_TimEn_CH0,
    input logic  dc_land_for_Reg_bf_TimEn_CH0_CH0_CTRLSTAT,
    output logic  [31:0] default_interface_w_c_BF_bf_ACTVAL_CH0_CH0_ACTVAL_flipflop_in,
    output logic  default_interface_w_c_BF_bf_ACTVAL_CH0_CH0_ACTVAL_flipflop_en,
    input logic  dc_land_for_Reg_bf_ACTVAL_CH0_CH0_ACTVAL,
    input logic  [31:0] default_interface_w_c_BF_bf_ACTVAL_CH0_in,
    input logic  default_interface_w_c_BF_bf_ACTVAL_CH0_peripheral_wr_en,
    output logic  [31:0] default_interface_w_c_BF_bf_MAXVAL_CH0_CH0_MAXVAL_flipflop_in,
    output logic  default_interface_w_c_BF_bf_MAXVAL_CH0_CH0_MAXVAL_flipflop_en,
    input logic  dc_land_for_Reg_bf_MAXVAL_CH0_CH0_MAXVAL,
    output logic  [2:0] Input_of_Reg_bf_CapIM0_CH0,
    output logic  Enable_of_Reg_bf_CapIM0_CH0,
    input logic  dc_land_for_Reg_bf_CapIM0_CH0_CH0_CCUCTRL0,
    output logic  [2:0] Input_of_Reg_bf_CCM0_CH0,
    output logic  Enable_of_Reg_bf_CCM0_CH0,
    input logic  dc_land_for_Reg_bf_CCM0_CH0_CH0_CCUCTRL0,
    output logic  [31:0] default_interface_w_c_BF_bf_CCUVAL0_CH0_CH0_CCUVAL0_flipflop_in,
    output logic  default_interface_w_c_BF_bf_CCUVAL0_CH0_CH0_CCUVAL0_flipflop_en,
    input logic  dc_land_for_Reg_bf_CCUVAL0_CH0_CH0_CCUVAL0,
    input logic  [31:0] default_interface_w_c_BF_bf_CCUVAL0_CH0_in,
    input logic  default_interface_w_c_BF_bf_CCUVAL0_CH0_peripheral_wr_en,
    output logic  Input_of_Reg_bf_OvfIntEn_CH1,
    output logic  Enable_of_Reg_bf_OvfIntEn_CH1,
    input logic  dc_land_for_Reg_bf_OvfIntEn_CH1_CH1_CTRLSTAT,
    output logic  [2:0] Input_of_Reg_bf_CntIM_CH1,
    output logic  Enable_of_Reg_bf_CntIM_CH1,
    input logic  dc_land_for_Reg_bf_CntIM_CH1_CH1_CTRLSTAT,
    output logic  [2:0] Input_of_Reg_bf_ResIM_CH1,
    output logic  Enable_of_Reg_bf_ResIM_CH1,
    input logic  dc_land_for_Reg_bf_ResIM_CH1_CH1_CTRLSTAT,
    output logic  Input_of_Reg_bf_TimEn_CH1,
    output logic  Enable_of_Reg_bf_TimEn_CH1,
    input logic  dc_land_for_Reg_bf_TimEn_CH1_CH1_CTRLSTAT,
    output logic  [31:0] default_interface_w_c_BF_bf_ACTVAL_CH1_CH1_ACTVAL_flipflop_in,
    output logic  default_interface_w_c_BF_bf_ACTVAL_CH1_CH1_ACTVAL_flipflop_en,
    input logic  dc_land_for_Reg_bf_ACTVAL_CH1_CH1_ACTVAL,
    input logic  [31:0] default_interface_w_c_BF_bf_ACTVAL_CH1_in,
    input logic  default_interface_w_c_BF_bf_ACTVAL_CH1_peripheral_wr_en,
    output logic  [31:0] default_interface_w_c_BF_bf_MAXVAL_CH1_CH1_MAXVAL_flipflop_in,
    output logic  default_interface_w_c_BF_bf_MAXVAL_CH1_CH1_MAXVAL_flipflop_en,
    input logic  dc_land_for_Reg_bf_MAXVAL_CH1_CH1_MAXVAL,
    output logic  [2:0] Input_of_Reg_bf_CapIM0_CH1,
    output logic  Enable_of_Reg_bf_CapIM0_CH1,
    input logic  dc_land_for_Reg_bf_CapIM0_CH1_CH1_CCUCTRL0,
    output logic  [2:0] Input_of_Reg_bf_CCM0_CH1,
    output logic  Enable_of_Reg_bf_CCM0_CH1,
    input logic  dc_land_for_Reg_bf_CCM0_CH1_CH1_CCUCTRL0,
    output logic  [31:0] default_interface_w_c_BF_bf_CCUVAL0_CH1_CH1_CCUVAL0_flipflop_in,
    output logic  default_interface_w_c_BF_bf_CCUVAL0_CH1_CH1_CCUVAL0_flipflop_en,
    input logic  dc_land_for_Reg_bf_CCUVAL0_CH1_CH1_CCUVAL0,
    input logic  [31:0] default_interface_w_c_BF_bf_CCUVAL0_CH1_in,
    input logic  default_interface_w_c_BF_bf_CCUVAL0_CH1_peripheral_wr_en,
    output logic  [2:0] Input_of_Reg_bf_CapIM1_CH1,
    output logic  Enable_of_Reg_bf_CapIM1_CH1,
    input logic  dc_land_for_Reg_bf_CapIM1_CH1_CH1_CCUCTRL1,
    output logic  [2:0] Input_of_Reg_bf_CCM1_CH1,
    output logic  Enable_of_Reg_bf_CCM1_CH1,
    input logic  dc_land_for_Reg_bf_CCM1_CH1_CH1_CCUCTRL1,
    output logic  [31:0] default_interface_w_c_BF_bf_CCUVAL1_CH1_CH1_CCUVAL1_flipflop_in,
    output logic  default_interface_w_c_BF_bf_CCUVAL1_CH1_CH1_CCUVAL1_flipflop_en,
    input logic  dc_land_for_Reg_bf_CCUVAL1_CH1_CH1_CCUVAL1,
    input logic  [31:0] default_interface_w_c_BF_bf_CCUVAL1_CH1_in,
    input logic  default_interface_w_c_BF_bf_CCUVAL1_CH1_peripheral_wr_en,
    output logic  [2:0] Input_of_Reg_bf_CapIM2_CH1,
    output logic  Enable_of_Reg_bf_CapIM2_CH1,
    input logic  dc_land_for_Reg_bf_CapIM2_CH1_CH1_CCUCTRL2,
    output logic  [2:0] Input_of_Reg_bf_CCM2_CH1,
    output logic  Enable_of_Reg_bf_CCM2_CH1,
    input logic  dc_land_for_Reg_bf_CCM2_CH1_CH1_CCUCTRL2,
    output logic  [31:0] default_interface_w_c_BF_bf_CCUVAL2_CH1_CH1_CCUVAL2_flipflop_in,
    output logic  default_interface_w_c_BF_bf_CCUVAL2_CH1_CH1_CCUVAL2_flipflop_en,
    input logic  dc_land_for_Reg_bf_CCUVAL2_CH1_CH1_CCUVAL2,
    input logic  [31:0] default_interface_w_c_BF_bf_CCUVAL2_CH1_in,
    input logic  default_interface_w_c_BF_bf_CCUVAL2_CH1_peripheral_wr_en,
    output logic  [2:0] Input_of_Reg_bf_CapIM3_CH1,
    output logic  Enable_of_Reg_bf_CapIM3_CH1,
    input logic  dc_land_for_Reg_bf_CapIM3_CH1_CH1_CCUCTRL3,
    output logic  [2:0] Input_of_Reg_bf_CCM3_CH1,
    output logic  Enable_of_Reg_bf_CCM3_CH1,
    input logic  dc_land_for_Reg_bf_CCM3_CH1_CH1_CCUCTRL3,
    output logic  [31:0] default_interface_w_c_BF_bf_CCUVAL3_CH1_CH1_CCUVAL3_flipflop_in,
    output logic  default_interface_w_c_BF_bf_CCUVAL3_CH1_CH1_CCUVAL3_flipflop_en,
    input logic  dc_land_for_Reg_bf_CCUVAL3_CH1_CH1_CCUVAL3,
    input logic  [31:0] default_interface_w_c_BF_bf_CCUVAL3_CH1_in,
    input logic  default_interface_w_c_BF_bf_CCUVAL3_CH1_peripheral_wr_en,
    output logic  [2:0] Input_of_Reg_bf_CapIM4_CH1,
    output logic  Enable_of_Reg_bf_CapIM4_CH1,
    input logic  dc_land_for_Reg_bf_CapIM4_CH1_CH1_CCUCTRL4,
    output logic  [2:0] Input_of_Reg_bf_CCM4_CH1,
    output logic  Enable_of_Reg_bf_CCM4_CH1,
    input logic  dc_land_for_Reg_bf_CCM4_CH1_CH1_CCUCTRL4,
    output logic  [31:0] default_interface_w_c_BF_bf_CCUVAL4_CH1_CH1_CCUVAL4_flipflop_in,
    output logic  default_interface_w_c_BF_bf_CCUVAL4_CH1_CH1_CCUVAL4_flipflop_en,
    input logic  dc_land_for_Reg_bf_CCUVAL4_CH1_CH1_CCUVAL4,
    input logic  [31:0] default_interface_w_c_BF_bf_CCUVAL4_CH1_in,
    input logic  default_interface_w_c_BF_bf_CCUVAL4_CH1_peripheral_wr_en,
    output logic  [2:0] Input_of_Reg_bf_CapIM5_CH1,
    output logic  Enable_of_Reg_bf_CapIM5_CH1,
    input logic  dc_land_for_Reg_bf_CapIM5_CH1_CH1_CCUCTRL5,
    output logic  [2:0] Input_of_Reg_bf_CCM5_CH1,
    output logic  Enable_of_Reg_bf_CCM5_CH1,
    input logic  dc_land_for_Reg_bf_CCM5_CH1_CH1_CCUCTRL5,
    output logic  [31:0] default_interface_w_c_BF_bf_CCUVAL5_CH1_CH1_CCUVAL5_flipflop_in,
    output logic  default_interface_w_c_BF_bf_CCUVAL5_CH1_CH1_CCUVAL5_flipflop_en,
    input logic  dc_land_for_Reg_bf_CCUVAL5_CH1_CH1_CCUVAL5,
    input logic  [31:0] default_interface_w_c_BF_bf_CCUVAL5_CH1_in,
    input logic  default_interface_w_c_BF_bf_CCUVAL5_CH1_peripheral_wr_en
);

logic   [31:0] Mux_CH1_CCUVAL5_BF_bf_CCUVAL5_CH1_input_Outp_s;
logic   [31:0] Mux_CH1_CCUVAL4_BF_bf_CCUVAL4_CH1_input_Outp_s;
logic   [31:0] Mux_CH1_CCUVAL3_BF_bf_CCUVAL3_CH1_input_Outp_s;
logic   [31:0] Mux_CH1_CCUVAL2_BF_bf_CCUVAL2_CH1_input_Outp_s;
logic   [31:0] Mux_CH1_CCUVAL1_BF_bf_CCUVAL1_CH1_input_Outp_s;
logic   [31:0] Mux_CH1_CCUVAL0_BF_bf_CCUVAL0_CH1_input_Outp_s;
logic   [31:0] Mux_CH1_ACTVAL_BF_bf_ACTVAL_CH1_input_Outp_s;
logic   [31:0] Mux_CH0_CCUVAL0_BF_bf_CCUVAL0_CH0_input_Outp_s;
logic   [31:0] Mux_CH0_ACTVAL_BF_bf_ACTVAL_CH0_input_Outp_s;

assign default_interface_w_c_BF_bf_CCUVAL5_CH1_CH1_CCUVAL5_flipflop_en = default_interface_w_c_BF_bf_CCUVAL5_CH1_peripheral_wr_en | dc_land_for_Reg_bf_CCUVAL5_CH1_CH1_CCUVAL5;

always_comb
begin
    case (dc_land_for_Reg_bf_CCUVAL5_CH1_CH1_CCUVAL5)
        1'b1 : Mux_CH1_CCUVAL5_BF_bf_CCUVAL5_CH1_input_Outp_s = (default_interface_w_c_data_in[31:0]);
        default : Mux_CH1_CCUVAL5_BF_bf_CCUVAL5_CH1_input_Outp_s = 32'b0;
    endcase

end

always_comb
begin
    default_interface_w_c_BF_bf_CCUVAL5_CH1_CH1_CCUVAL5_flipflop_in = (default_interface_w_c_BF_bf_CCUVAL5_CH1_peripheral_wr_en) ? default_interface_w_c_BF_bf_CCUVAL5_CH1_in : Mux_CH1_CCUVAL5_BF_bf_CCUVAL5_CH1_input_Outp_s;
end

always_comb
begin
    case (dc_land_for_Reg_bf_CCM5_CH1_CH1_CCUCTRL5)
        1'b1 : Input_of_Reg_bf_CCM5_CH1 = (default_interface_w_c_data_in[2:0]);
        default : Input_of_Reg_bf_CCM5_CH1 = 3'b0;
    endcase

end

always_comb
begin
    case (dc_land_for_Reg_bf_CapIM5_CH1_CH1_CCUCTRL5)
        1'b1 : Input_of_Reg_bf_CapIM5_CH1 = (default_interface_w_c_data_in[5:3]);
        default : Input_of_Reg_bf_CapIM5_CH1 = 3'b0;
    endcase

end

assign default_interface_w_c_BF_bf_CCUVAL4_CH1_CH1_CCUVAL4_flipflop_en = default_interface_w_c_BF_bf_CCUVAL4_CH1_peripheral_wr_en | dc_land_for_Reg_bf_CCUVAL4_CH1_CH1_CCUVAL4;

always_comb
begin
    case (dc_land_for_Reg_bf_CCUVAL4_CH1_CH1_CCUVAL4)
        1'b1 : Mux_CH1_CCUVAL4_BF_bf_CCUVAL4_CH1_input_Outp_s = (default_interface_w_c_data_in[31:0]);
        default : Mux_CH1_CCUVAL4_BF_bf_CCUVAL4_CH1_input_Outp_s = 32'b0;
    endcase

end

always_comb
begin
    default_interface_w_c_BF_bf_CCUVAL4_CH1_CH1_CCUVAL4_flipflop_in = (default_interface_w_c_BF_bf_CCUVAL4_CH1_peripheral_wr_en) ? default_interface_w_c_BF_bf_CCUVAL4_CH1_in : Mux_CH1_CCUVAL4_BF_bf_CCUVAL4_CH1_input_Outp_s;
end

always_comb
begin
    case (dc_land_for_Reg_bf_CCM4_CH1_CH1_CCUCTRL4)
        1'b1 : Input_of_Reg_bf_CCM4_CH1 = (default_interface_w_c_data_in[2:0]);
        default : Input_of_Reg_bf_CCM4_CH1 = 3'b0;
    endcase

end

always_comb
begin
    case (dc_land_for_Reg_bf_CapIM4_CH1_CH1_CCUCTRL4)
        1'b1 : Input_of_Reg_bf_CapIM4_CH1 = (default_interface_w_c_data_in[5:3]);
        default : Input_of_Reg_bf_CapIM4_CH1 = 3'b0;
    endcase

end

assign default_interface_w_c_BF_bf_CCUVAL3_CH1_CH1_CCUVAL3_flipflop_en = default_interface_w_c_BF_bf_CCUVAL3_CH1_peripheral_wr_en | dc_land_for_Reg_bf_CCUVAL3_CH1_CH1_CCUVAL3;

always_comb
begin
    case (dc_land_for_Reg_bf_CCUVAL3_CH1_CH1_CCUVAL3)
        1'b1 : Mux_CH1_CCUVAL3_BF_bf_CCUVAL3_CH1_input_Outp_s = (default_interface_w_c_data_in[31:0]);
        default : Mux_CH1_CCUVAL3_BF_bf_CCUVAL3_CH1_input_Outp_s = 32'b0;
    endcase

end

always_comb
begin
    default_interface_w_c_BF_bf_CCUVAL3_CH1_CH1_CCUVAL3_flipflop_in = (default_interface_w_c_BF_bf_CCUVAL3_CH1_peripheral_wr_en) ? default_interface_w_c_BF_bf_CCUVAL3_CH1_in : Mux_CH1_CCUVAL3_BF_bf_CCUVAL3_CH1_input_Outp_s;
end

always_comb
begin
    case (dc_land_for_Reg_bf_CCM3_CH1_CH1_CCUCTRL3)
        1'b1 : Input_of_Reg_bf_CCM3_CH1 = (default_interface_w_c_data_in[2:0]);
        default : Input_of_Reg_bf_CCM3_CH1 = 3'b0;
    endcase

end

always_comb
begin
    case (dc_land_for_Reg_bf_CapIM3_CH1_CH1_CCUCTRL3)
        1'b1 : Input_of_Reg_bf_CapIM3_CH1 = (default_interface_w_c_data_in[5:3]);
        default : Input_of_Reg_bf_CapIM3_CH1 = 3'b0;
    endcase

end

assign default_interface_w_c_BF_bf_CCUVAL2_CH1_CH1_CCUVAL2_flipflop_en = default_interface_w_c_BF_bf_CCUVAL2_CH1_peripheral_wr_en | dc_land_for_Reg_bf_CCUVAL2_CH1_CH1_CCUVAL2;

always_comb
begin
    case (dc_land_for_Reg_bf_CCUVAL2_CH1_CH1_CCUVAL2)
        1'b1 : Mux_CH1_CCUVAL2_BF_bf_CCUVAL2_CH1_input_Outp_s = (default_interface_w_c_data_in[31:0]);
        default : Mux_CH1_CCUVAL2_BF_bf_CCUVAL2_CH1_input_Outp_s = 32'b0;
    endcase

end

always_comb
begin
    default_interface_w_c_BF_bf_CCUVAL2_CH1_CH1_CCUVAL2_flipflop_in = (default_interface_w_c_BF_bf_CCUVAL2_CH1_peripheral_wr_en) ? default_interface_w_c_BF_bf_CCUVAL2_CH1_in : Mux_CH1_CCUVAL2_BF_bf_CCUVAL2_CH1_input_Outp_s;
end

always_comb
begin
    case (dc_land_for_Reg_bf_CCM2_CH1_CH1_CCUCTRL2)
        1'b1 : Input_of_Reg_bf_CCM2_CH1 = (default_interface_w_c_data_in[2:0]);
        default : Input_of_Reg_bf_CCM2_CH1 = 3'b0;
    endcase

end

always_comb
begin
    case (dc_land_for_Reg_bf_CapIM2_CH1_CH1_CCUCTRL2)
        1'b1 : Input_of_Reg_bf_CapIM2_CH1 = (default_interface_w_c_data_in[5:3]);
        default : Input_of_Reg_bf_CapIM2_CH1 = 3'b0;
    endcase

end

assign default_interface_w_c_BF_bf_CCUVAL1_CH1_CH1_CCUVAL1_flipflop_en = default_interface_w_c_BF_bf_CCUVAL1_CH1_peripheral_wr_en | dc_land_for_Reg_bf_CCUVAL1_CH1_CH1_CCUVAL1;

always_comb
begin
    case (dc_land_for_Reg_bf_CCUVAL1_CH1_CH1_CCUVAL1)
        1'b1 : Mux_CH1_CCUVAL1_BF_bf_CCUVAL1_CH1_input_Outp_s = (default_interface_w_c_data_in[31:0]);
        default : Mux_CH1_CCUVAL1_BF_bf_CCUVAL1_CH1_input_Outp_s = 32'b0;
    endcase

end

always_comb
begin
    default_interface_w_c_BF_bf_CCUVAL1_CH1_CH1_CCUVAL1_flipflop_in = (default_interface_w_c_BF_bf_CCUVAL1_CH1_peripheral_wr_en) ? default_interface_w_c_BF_bf_CCUVAL1_CH1_in : Mux_CH1_CCUVAL1_BF_bf_CCUVAL1_CH1_input_Outp_s;
end

always_comb
begin
    case (dc_land_for_Reg_bf_CCM1_CH1_CH1_CCUCTRL1)
        1'b1 : Input_of_Reg_bf_CCM1_CH1 = (default_interface_w_c_data_in[2:0]);
        default : Input_of_Reg_bf_CCM1_CH1 = 3'b0;
    endcase

end

always_comb
begin
    case (dc_land_for_Reg_bf_CapIM1_CH1_CH1_CCUCTRL1)
        1'b1 : Input_of_Reg_bf_CapIM1_CH1 = (default_interface_w_c_data_in[5:3]);
        default : Input_of_Reg_bf_CapIM1_CH1 = 3'b0;
    endcase

end

assign default_interface_w_c_BF_bf_CCUVAL0_CH1_CH1_CCUVAL0_flipflop_en = default_interface_w_c_BF_bf_CCUVAL0_CH1_peripheral_wr_en | dc_land_for_Reg_bf_CCUVAL0_CH1_CH1_CCUVAL0;

always_comb
begin
    case (dc_land_for_Reg_bf_CCUVAL0_CH1_CH1_CCUVAL0)
        1'b1 : Mux_CH1_CCUVAL0_BF_bf_CCUVAL0_CH1_input_Outp_s = (default_interface_w_c_data_in[31:0]);
        default : Mux_CH1_CCUVAL0_BF_bf_CCUVAL0_CH1_input_Outp_s = 32'b0;
    endcase

end

always_comb
begin
    default_interface_w_c_BF_bf_CCUVAL0_CH1_CH1_CCUVAL0_flipflop_in = (default_interface_w_c_BF_bf_CCUVAL0_CH1_peripheral_wr_en) ? default_interface_w_c_BF_bf_CCUVAL0_CH1_in : Mux_CH1_CCUVAL0_BF_bf_CCUVAL0_CH1_input_Outp_s;
end

always_comb
begin
    case (dc_land_for_Reg_bf_CCM0_CH1_CH1_CCUCTRL0)
        1'b1 : Input_of_Reg_bf_CCM0_CH1 = (default_interface_w_c_data_in[2:0]);
        default : Input_of_Reg_bf_CCM0_CH1 = 3'b0;
    endcase

end

always_comb
begin
    case (dc_land_for_Reg_bf_CapIM0_CH1_CH1_CCUCTRL0)
        1'b1 : Input_of_Reg_bf_CapIM0_CH1 = (default_interface_w_c_data_in[5:3]);
        default : Input_of_Reg_bf_CapIM0_CH1 = 3'b0;
    endcase

end

always_comb
begin
    case (dc_land_for_Reg_bf_MAXVAL_CH1_CH1_MAXVAL)
        1'b1 : default_interface_w_c_BF_bf_MAXVAL_CH1_CH1_MAXVAL_flipflop_in = (default_interface_w_c_data_in[31:0]);
        default : default_interface_w_c_BF_bf_MAXVAL_CH1_CH1_MAXVAL_flipflop_in = 32'b0;
    endcase

end

assign default_interface_w_c_BF_bf_ACTVAL_CH1_CH1_ACTVAL_flipflop_en = default_interface_w_c_BF_bf_ACTVAL_CH1_peripheral_wr_en | dc_land_for_Reg_bf_ACTVAL_CH1_CH1_ACTVAL;

always_comb
begin
    case (dc_land_for_Reg_bf_ACTVAL_CH1_CH1_ACTVAL)
        1'b1 : Mux_CH1_ACTVAL_BF_bf_ACTVAL_CH1_input_Outp_s = (default_interface_w_c_data_in[31:0]);
        default : Mux_CH1_ACTVAL_BF_bf_ACTVAL_CH1_input_Outp_s = 32'b0;
    endcase

end

always_comb
begin
    default_interface_w_c_BF_bf_ACTVAL_CH1_CH1_ACTVAL_flipflop_in = (default_interface_w_c_BF_bf_ACTVAL_CH1_peripheral_wr_en) ? default_interface_w_c_BF_bf_ACTVAL_CH1_in : Mux_CH1_ACTVAL_BF_bf_ACTVAL_CH1_input_Outp_s;
end

always_comb
begin
    case (dc_land_for_Reg_bf_TimEn_CH1_CH1_CTRLSTAT)
        1'b1 : Input_of_Reg_bf_TimEn_CH1 = (default_interface_w_c_data_in[0]);
        default : Input_of_Reg_bf_TimEn_CH1 = 1'b0;
    endcase

end

always_comb
begin
    case (dc_land_for_Reg_bf_ResIM_CH1_CH1_CTRLSTAT)
        1'b1 : Input_of_Reg_bf_ResIM_CH1 = (default_interface_w_c_data_in[3:1]);
        default : Input_of_Reg_bf_ResIM_CH1 = 3'b0;
    endcase

end

always_comb
begin
    case (dc_land_for_Reg_bf_CntIM_CH1_CH1_CTRLSTAT)
        1'b1 : Input_of_Reg_bf_CntIM_CH1 = (default_interface_w_c_data_in[6:4]);
        default : Input_of_Reg_bf_CntIM_CH1 = 3'b0;
    endcase

end

always_comb
begin
    case (dc_land_for_Reg_bf_OvfIntEn_CH1_CH1_CTRLSTAT)
        1'b1 : Input_of_Reg_bf_OvfIntEn_CH1 = (default_interface_w_c_data_in[7]);
        default : Input_of_Reg_bf_OvfIntEn_CH1 = 1'b0;
    endcase

end

assign default_interface_w_c_BF_bf_CCUVAL0_CH0_CH0_CCUVAL0_flipflop_en = default_interface_w_c_BF_bf_CCUVAL0_CH0_peripheral_wr_en | dc_land_for_Reg_bf_CCUVAL0_CH0_CH0_CCUVAL0;

always_comb
begin
    case (dc_land_for_Reg_bf_CCUVAL0_CH0_CH0_CCUVAL0)
        1'b1 : Mux_CH0_CCUVAL0_BF_bf_CCUVAL0_CH0_input_Outp_s = (default_interface_w_c_data_in[31:0]);
        default : Mux_CH0_CCUVAL0_BF_bf_CCUVAL0_CH0_input_Outp_s = 32'b0;
    endcase

end

always_comb
begin
    default_interface_w_c_BF_bf_CCUVAL0_CH0_CH0_CCUVAL0_flipflop_in = (default_interface_w_c_BF_bf_CCUVAL0_CH0_peripheral_wr_en) ? default_interface_w_c_BF_bf_CCUVAL0_CH0_in : Mux_CH0_CCUVAL0_BF_bf_CCUVAL0_CH0_input_Outp_s;
end

always_comb
begin
    case (dc_land_for_Reg_bf_CCM0_CH0_CH0_CCUCTRL0)
        1'b1 : Input_of_Reg_bf_CCM0_CH0 = (default_interface_w_c_data_in[2:0]);
        default : Input_of_Reg_bf_CCM0_CH0 = 3'b0;
    endcase

end

always_comb
begin
    case (dc_land_for_Reg_bf_CapIM0_CH0_CH0_CCUCTRL0)
        1'b1 : Input_of_Reg_bf_CapIM0_CH0 = (default_interface_w_c_data_in[5:3]);
        default : Input_of_Reg_bf_CapIM0_CH0 = 3'b0;
    endcase

end

always_comb
begin
    case (dc_land_for_Reg_bf_MAXVAL_CH0_CH0_MAXVAL)
        1'b1 : default_interface_w_c_BF_bf_MAXVAL_CH0_CH0_MAXVAL_flipflop_in = (default_interface_w_c_data_in[31:0]);
        default : default_interface_w_c_BF_bf_MAXVAL_CH0_CH0_MAXVAL_flipflop_in = 32'b0;
    endcase

end

assign default_interface_w_c_BF_bf_ACTVAL_CH0_CH0_ACTVAL_flipflop_en = default_interface_w_c_BF_bf_ACTVAL_CH0_peripheral_wr_en | dc_land_for_Reg_bf_ACTVAL_CH0_CH0_ACTVAL;

always_comb
begin
    case (dc_land_for_Reg_bf_ACTVAL_CH0_CH0_ACTVAL)
        1'b1 : Mux_CH0_ACTVAL_BF_bf_ACTVAL_CH0_input_Outp_s = (default_interface_w_c_data_in[31:0]);
        default : Mux_CH0_ACTVAL_BF_bf_ACTVAL_CH0_input_Outp_s = 32'b0;
    endcase

end

always_comb
begin
    default_interface_w_c_BF_bf_ACTVAL_CH0_CH0_ACTVAL_flipflop_in = (default_interface_w_c_BF_bf_ACTVAL_CH0_peripheral_wr_en) ? default_interface_w_c_BF_bf_ACTVAL_CH0_in : Mux_CH0_ACTVAL_BF_bf_ACTVAL_CH0_input_Outp_s;
end

always_comb
begin
    case (dc_land_for_Reg_bf_TimEn_CH0_CH0_CTRLSTAT)
        1'b1 : Input_of_Reg_bf_TimEn_CH0 = (default_interface_w_c_data_in[0]);
        default : Input_of_Reg_bf_TimEn_CH0 = 1'b0;
    endcase

end

always_comb
begin
    case (dc_land_for_Reg_bf_ResIM_CH0_CH0_CTRLSTAT)
        1'b1 : Input_of_Reg_bf_ResIM_CH0 = (default_interface_w_c_data_in[3:1]);
        default : Input_of_Reg_bf_ResIM_CH0 = 3'b0;
    endcase

end

always_comb
begin
    case (dc_land_for_Reg_bf_CntIM_CH0_CH0_CTRLSTAT)
        1'b1 : Input_of_Reg_bf_CntIM_CH0 = (default_interface_w_c_data_in[6:4]);
        default : Input_of_Reg_bf_CntIM_CH0 = 3'b0;
    endcase

end

always_comb
begin
    case (dc_land_for_Reg_bf_OvfIntEn_CH0_CH0_CTRLSTAT)
        1'b1 : Input_of_Reg_bf_OvfIntEn_CH0 = (default_interface_w_c_data_in[7]);
        default : Input_of_Reg_bf_OvfIntEn_CH0 = 1'b0;
    endcase

end

assign Enable_of_Reg_bf_OvfIntEn_CH0 = dc_land_for_Reg_bf_OvfIntEn_CH0_CH0_CTRLSTAT;
assign Enable_of_Reg_bf_CntIM_CH0 = dc_land_for_Reg_bf_CntIM_CH0_CH0_CTRLSTAT;
assign Enable_of_Reg_bf_ResIM_CH0 = dc_land_for_Reg_bf_ResIM_CH0_CH0_CTRLSTAT;
assign Enable_of_Reg_bf_TimEn_CH0 = dc_land_for_Reg_bf_TimEn_CH0_CH0_CTRLSTAT;
assign default_interface_w_c_BF_bf_MAXVAL_CH0_CH0_MAXVAL_flipflop_en = dc_land_for_Reg_bf_MAXVAL_CH0_CH0_MAXVAL;
assign Enable_of_Reg_bf_CapIM0_CH0 = dc_land_for_Reg_bf_CapIM0_CH0_CH0_CCUCTRL0;
assign Enable_of_Reg_bf_CCM0_CH0 = dc_land_for_Reg_bf_CCM0_CH0_CH0_CCUCTRL0;
assign Enable_of_Reg_bf_OvfIntEn_CH1 = dc_land_for_Reg_bf_OvfIntEn_CH1_CH1_CTRLSTAT;
assign Enable_of_Reg_bf_CntIM_CH1 = dc_land_for_Reg_bf_CntIM_CH1_CH1_CTRLSTAT;
assign Enable_of_Reg_bf_ResIM_CH1 = dc_land_for_Reg_bf_ResIM_CH1_CH1_CTRLSTAT;
assign Enable_of_Reg_bf_TimEn_CH1 = dc_land_for_Reg_bf_TimEn_CH1_CH1_CTRLSTAT;
assign default_interface_w_c_BF_bf_MAXVAL_CH1_CH1_MAXVAL_flipflop_en = dc_land_for_Reg_bf_MAXVAL_CH1_CH1_MAXVAL;
assign Enable_of_Reg_bf_CapIM0_CH1 = dc_land_for_Reg_bf_CapIM0_CH1_CH1_CCUCTRL0;
assign Enable_of_Reg_bf_CCM0_CH1 = dc_land_for_Reg_bf_CCM0_CH1_CH1_CCUCTRL0;
assign Enable_of_Reg_bf_CapIM1_CH1 = dc_land_for_Reg_bf_CapIM1_CH1_CH1_CCUCTRL1;
assign Enable_of_Reg_bf_CCM1_CH1 = dc_land_for_Reg_bf_CCM1_CH1_CH1_CCUCTRL1;
assign Enable_of_Reg_bf_CapIM2_CH1 = dc_land_for_Reg_bf_CapIM2_CH1_CH1_CCUCTRL2;
assign Enable_of_Reg_bf_CCM2_CH1 = dc_land_for_Reg_bf_CCM2_CH1_CH1_CCUCTRL2;
assign Enable_of_Reg_bf_CapIM3_CH1 = dc_land_for_Reg_bf_CapIM3_CH1_CH1_CCUCTRL3;
assign Enable_of_Reg_bf_CCM3_CH1 = dc_land_for_Reg_bf_CCM3_CH1_CH1_CCUCTRL3;
assign Enable_of_Reg_bf_CapIM4_CH1 = dc_land_for_Reg_bf_CapIM4_CH1_CH1_CCUCTRL4;
assign Enable_of_Reg_bf_CCM4_CH1 = dc_land_for_Reg_bf_CCM4_CH1_CH1_CCUCTRL4;
assign Enable_of_Reg_bf_CapIM5_CH1 = dc_land_for_Reg_bf_CapIM5_CH1_CH1_CCUCTRL5;
assign Enable_of_Reg_bf_CCM5_CH1 = dc_land_for_Reg_bf_CCM5_CH1_CH1_CCUCTRL5;

endmodule

