/* ===============================================================
Copyright 2026, Infineon Technologies AG or an 
affiliate of Infineon Technologies AG.  All rights reserved.
 
This software, associated documentation and materials ("Software") is owned by
Infineon Technologies AG or one of its affiliates ("Infineon") and is 
protected by and subject to worldwide patent protection (United States and 
foreign), United States copyright laws and international treaty provisions. 
Therefore, you may use this Software only as provided in the license agreement
accompanying the software package from which you obtained this 
Software ("EULA"). If no EULA applies, then any reproduction, modification, 
translation, compilation, or representation of this Software is prohibited 
without the express written permission of Infineon.
 
Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF 
ANY KIND, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, 
NONINFRINGEMENT, IMPLIED WARRANTIES OF  MERCHANTABILITY AND
FITNESS FOR A PARTICULAR PURPOSE.  Infineon reserves the right to make
changes to the Software without notice. Infineon does not assume any liability
arising out of the application or use of the Software or any product or 
circuit described in the Software. Infineon does not authorize its products 
for use in any products where a malfunction or failure of the Infineon product 
may reasonably be expected to result in significant property damage, injury or
death ("High Risk Product").  By including Infineon 's product in a High Risk 
Product, the manufacturer of such system or application assumes all risk of 
such use and in doing so agrees to indemnify Infineon against all liability.

 ===============================================================
*/ 
// File : tc_soc_timer_timer_TimerChannel_1_ACTVALCU.sv 
// Author : tahiraga 
// Date : 15:07:02    25/09/2026 
// Revision :  
// =============================================================== 
// Description : 
/*
---- Auto Generated by MetaRTL , a MetaGen application
---- Contact: ParitoshKumar.Sinha@infineon.com
---- Contact: Yash.Ranjan@infineon.com
===============================================================
tc_soc_timer_timer_TimerChannel_1_ACTVALCU: This units controls what and when should be written to the ACTVAL register by the hardware. It also controls the reset of ACTVAL. 
 */


module tc_soc_timer_cACTVALControlUnit (
    input logic  TimEn,
    input logic  [2:0] ResIM,
    input logic  [2:0] CntIM,
    input logic  ExtRes_sync,
    input logic  ExtCnt_sync,
    input logic  [31:0] ACTVAL,
    output logic  AutoResCondition,
    output logic  MuxACTVAL_sel,
    output logic  ACTVAL_wr
);

logic   ResEnable_ROR_Outp_s;
logic   ACTVAL_is_zero_Outp_s;
logic   ExtCntDis_EQ_Outp_s;
logic   ExtCnt_COND_NZERO_Outp_s;
logic   AutRes_CONDITION_Outp_s;
logic   AutRes_EQ_Outp_s;
logic   ACTVAL_is_not_zero_Outp_s;
logic   Cnt_COND_NZERO_Outp_s;
logic   ActRes_Outp_s;
logic   Cnt_CONDITION_Outp_s;
logic   Res_CONDITION_Outp_s;
logic   ACTVAL_en_GATE0_Outp_s;

assign ResEnable_ROR_Outp_s = &ResIM;

assign ACTVAL_is_zero_Outp_s = ACTVAL == { 31'b0 , 1'b0 } ? 1'b1 : 1'b0;

assign ExtCntDis_EQ_Outp_s = CntIM == { 2'b0 , (1'b0) } ? 1'b1 : 1'b0;

assign ExtCnt_COND_NZERO_Outp_s = (~ExtCntDis_EQ_Outp_s) & ExtCnt_sync;

assign AutRes_CONDITION_Outp_s = ACTVAL_is_zero_Outp_s & ResEnable_ROR_Outp_s;
assign AutoResCondition = AutRes_CONDITION_Outp_s;

assign AutRes_EQ_Outp_s = ResIM == (3'b111) ? 1'b1 : 1'b0;

assign ACTVAL_is_not_zero_Outp_s = ~ACTVAL_is_zero_Outp_s;

assign Cnt_COND_NZERO_Outp_s = ExtCnt_COND_NZERO_Outp_s | ExtCntDis_EQ_Outp_s;

assign ActRes_Outp_s = AutRes_EQ_Outp_s & AutRes_CONDITION_Outp_s;

assign Cnt_CONDITION_Outp_s = Cnt_COND_NZERO_Outp_s & ACTVAL_is_not_zero_Outp_s;

assign Res_CONDITION_Outp_s = ActRes_Outp_s | ExtRes_sync;
assign MuxACTVAL_sel = Res_CONDITION_Outp_s;

assign ACTVAL_en_GATE0_Outp_s = Res_CONDITION_Outp_s | Cnt_CONDITION_Outp_s;

assign ACTVAL_wr = TimEn & ACTVAL_en_GATE0_Outp_s;


endmodule

