/* ===============================================================
Copyright 2026, Infineon Technologies AG or an 
affiliate of Infineon Technologies AG.  All rights reserved.
 
This software, associated documentation and materials ("Software") is owned by
Infineon Technologies AG or one of its affiliates ("Infineon") and is 
protected by and subject to worldwide patent protection (United States and 
foreign), United States copyright laws and international treaty provisions. 
Therefore, you may use this Software only as provided in the license agreement
accompanying the software package from which you obtained this 
Software ("EULA"). If no EULA applies, then any reproduction, modification, 
translation, compilation, or representation of this Software is prohibited 
without the express written permission of Infineon.
 
Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF 
ANY KIND, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, 
NONINFRINGEMENT, IMPLIED WARRANTIES OF  MERCHANTABILITY AND
FITNESS FOR A PARTICULAR PURPOSE.  Infineon reserves the right to make
changes to the Software without notice. Infineon does not assume any liability
arising out of the application or use of the Software or any product or 
circuit described in the Software. Infineon does not authorize its products 
for use in any products where a malfunction or failure of the Infineon product 
may reasonably be expected to result in significant property damage, injury or
death ("High Risk Product").  By including Infineon 's product in a High Risk 
Product, the manufacturer of such system or application assumes all risk of 
such use and in doing so agrees to indemnify Infineon against all liability.

 ===============================================================
*/ 
// File : tc_soc_timer_timer_TimerChannel_1_CapSync_5.sv 
// Author : tahiraga 
// Date : 15:07:02    25/09/2026 
// Revision :  
// =============================================================== 
// Description : 
/*
---- Auto Generated by MetaRTL , a MetaGen application
---- Contact: ParitoshKumar.Sinha@infineon.com
---- Contact: Yash.Ranjan@infineon.com
===============================================================
tc_soc_timer_timer_TimerChannel_1_CapSync_5: Synchronizes the ExtCap5 signal 
 */


module tc_soc_timer_cBitSynchronizer (
    input logic  Async,
    output logic  Sync,
    input logic  [2:0] IM,
    input logic  HCLK_i,
    input logic  HRESET_n_i
);

logic   ch_GATE_fall_Outp_s;
logic   ch_GATE_rise_Outp_s;
logic   ch_GATE_risefall_Outp_s;
logic   Not_In_reg0_Outp_s;
logic   Not_In_reg1_Outp_s;
logic   ch_GATE_Outp_s;
logic   low_GATE_Outp_s;
logic   fall_GATE_Outp_s;
logic   high_GATE_Outp_s;
logic   rise_GATE_Outp_s;

logic   In_reg1_Outp_s;
logic   In_reg0_Outp_s;
logic   IM_DEC_Out00_s;
logic   IM_DEC_Out01_s;
logic   IM_DEC_Out02_s;
logic   IM_DEC_Out03_s;
logic   IM_DEC_Out04_s;

assign ch_GATE_fall_Outp_s = Not_In_reg0_Outp_s & In_reg1_Outp_s;

assign ch_GATE_rise_Outp_s = In_reg0_Outp_s & Not_In_reg1_Outp_s;

assign ch_GATE_risefall_Outp_s = ch_GATE_rise_Outp_s | ch_GATE_fall_Outp_s;

always_ff @(negedge HRESET_n_i, posedge HCLK_i)
begin
    if (HRESET_n_i == 1'b0) begin
        In_reg1_Outp_s <= 1'b0;
    end else begin
        In_reg1_Outp_s <= In_reg0_Outp_s;
    end

end

assign Not_In_reg0_Outp_s = ~In_reg0_Outp_s;

assign Not_In_reg1_Outp_s = ~In_reg1_Outp_s;

always_ff @(negedge HRESET_n_i, posedge HCLK_i)
begin
    if (HRESET_n_i == 1'b0) begin
        In_reg0_Outp_s <= 1'b0;
    end else begin
        In_reg0_Outp_s <= Async;
    end

end


always_comb
begin
    IM_DEC_Out00_s = (IM == 3'b1) ? 1'b1 : 1'b0;
    IM_DEC_Out01_s = (IM == 3'b10) ? 1'b1 : 1'b0;
    IM_DEC_Out02_s = (IM == 3'b11) ? 1'b1 : 1'b0;
    IM_DEC_Out03_s = (IM == 3'b100) ? 1'b1 : 1'b0;
    IM_DEC_Out04_s = (IM == 3'b101) ? 1'b1 : 1'b0;

end

assign ch_GATE_Outp_s = ch_GATE_risefall_Outp_s & IM_DEC_Out04_s;

assign low_GATE_Outp_s = IM_DEC_Out03_s & Not_In_reg0_Outp_s;

assign fall_GATE_Outp_s = IM_DEC_Out01_s & Not_In_reg0_Outp_s & In_reg1_Outp_s;

assign high_GATE_Outp_s = IM_DEC_Out02_s & In_reg0_Outp_s;

assign rise_GATE_Outp_s = IM_DEC_Out00_s & In_reg0_Outp_s & Not_In_reg1_Outp_s;

assign Sync = rise_GATE_Outp_s | high_GATE_Outp_s | fall_GATE_Outp_s | low_GATE_Outp_s | ch_GATE_Outp_s;


endmodule

