/* ===============================================================
Copyright 2026, Infineon Technologies AG or an 
affiliate of Infineon Technologies AG.  All rights reserved.
 
This software, associated documentation and materials ("Software") is owned by
Infineon Technologies AG or one of its affiliates ("Infineon") and is 
protected by and subject to worldwide patent protection (United States and 
foreign), United States copyright laws and international treaty provisions. 
Therefore, you may use this Software only as provided in the license agreement
accompanying the software package from which you obtained this 
Software ("EULA"). If no EULA applies, then any reproduction, modification, 
translation, compilation, or representation of this Software is prohibited 
without the express written permission of Infineon.
 
Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF 
ANY KIND, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, 
NONINFRINGEMENT, IMPLIED WARRANTIES OF  MERCHANTABILITY AND
FITNESS FOR A PARTICULAR PURPOSE.  Infineon reserves the right to make
changes to the Software without notice. Infineon does not assume any liability
arising out of the application or use of the Software or any product or 
circuit described in the Software. Infineon does not authorize its products 
for use in any products where a malfunction or failure of the Infineon product 
may reasonably be expected to result in significant property damage, injury or
death ("High Risk Product").  By including Infineon 's product in a High Risk 
Product, the manufacturer of such system or application assumes all risk of 
such use and in doing so agrees to indemnify Infineon against all liability.

 ===============================================================
*/ 
// File : tc_soc_timer_Reg_IF_Top_CSC_Top_CSC_default_interface_Top_CSC_default_interface_AccessSizeCircuit.sv 
// Author : tahiraga 
// Date : 15:07:01    25/09/2026 
// Revision :  
// =============================================================== 
// Description : 
/*
---- Auto Generated by MetaRTL , a MetaGen application
---- Contact: ParitoshKumar.Sinha@infineon.com
---- Contact: Yash.Ranjan@infineon.com
===============================================================
*/


module tc_soc_timer_Reg_IF_Top_CSC_Top_CSC_default_interface_Top_CSC_default_interface_AccessSizeCircuit (
    input logic  [31:0] default_interface_addr,
    input logic  default_interface_wr_en,
    input logic  [1:0] default_interface_AS_in_AS_block,
    output logic  [31:0] default_interface_AS_masking_mux_out,
    output logic  [4:0] default_interface_AS_shift_value_mux_out,
    output logic  default_interface_Address_Error_Port,
    output logic  Address_EQ_Port_CH0_CTRLSTAT,
    output logic  Enable_Reg_bf_OvfIntEn_CH0_of_CH0_CTRLSTAT,
    output logic  Enable_Reg_bf_CntIM_CH0_of_CH0_CTRLSTAT,
    output logic  Enable_Reg_bf_ResIM_CH0_of_CH0_CTRLSTAT,
    output logic  Enable_Reg_bf_TimEn_CH0_of_CH0_CTRLSTAT,
    output logic  Address_EQ_Port_CH0_ACTVAL,
    output logic  Enable_Reg_bf_ACTVAL_CH0_of_CH0_ACTVAL,
    output logic  Address_EQ_Port_CH0_MAXVAL,
    output logic  Enable_Reg_bf_MAXVAL_CH0_of_CH0_MAXVAL,
    output logic  Address_EQ_Port_CH0_CCUCTRL0,
    output logic  Enable_Reg_bf_CapIM0_CH0_of_CH0_CCUCTRL0,
    output logic  Enable_Reg_bf_CCM0_CH0_of_CH0_CCUCTRL0,
    output logic  Address_EQ_Port_CH0_CCUVAL0,
    output logic  Enable_Reg_bf_CCUVAL0_CH0_of_CH0_CCUVAL0,
    output logic  Address_EQ_Port_CH1_CTRLSTAT,
    output logic  Enable_Reg_bf_OvfIntEn_CH1_of_CH1_CTRLSTAT,
    output logic  Enable_Reg_bf_CntIM_CH1_of_CH1_CTRLSTAT,
    output logic  Enable_Reg_bf_ResIM_CH1_of_CH1_CTRLSTAT,
    output logic  Enable_Reg_bf_TimEn_CH1_of_CH1_CTRLSTAT,
    output logic  Address_EQ_Port_CH1_ACTVAL,
    output logic  Enable_Reg_bf_ACTVAL_CH1_of_CH1_ACTVAL,
    output logic  Address_EQ_Port_CH1_MAXVAL,
    output logic  Enable_Reg_bf_MAXVAL_CH1_of_CH1_MAXVAL,
    output logic  Address_EQ_Port_CH1_CCUCTRL0,
    output logic  Enable_Reg_bf_CapIM0_CH1_of_CH1_CCUCTRL0,
    output logic  Enable_Reg_bf_CCM0_CH1_of_CH1_CCUCTRL0,
    output logic  Address_EQ_Port_CH1_CCUVAL0,
    output logic  Enable_Reg_bf_CCUVAL0_CH1_of_CH1_CCUVAL0,
    output logic  Address_EQ_Port_CH1_CCUCTRL1,
    output logic  Enable_Reg_bf_CapIM1_CH1_of_CH1_CCUCTRL1,
    output logic  Enable_Reg_bf_CCM1_CH1_of_CH1_CCUCTRL1,
    output logic  Address_EQ_Port_CH1_CCUVAL1,
    output logic  Enable_Reg_bf_CCUVAL1_CH1_of_CH1_CCUVAL1,
    output logic  Address_EQ_Port_CH1_CCUCTRL2,
    output logic  Enable_Reg_bf_CapIM2_CH1_of_CH1_CCUCTRL2,
    output logic  Enable_Reg_bf_CCM2_CH1_of_CH1_CCUCTRL2,
    output logic  Address_EQ_Port_CH1_CCUVAL2,
    output logic  Enable_Reg_bf_CCUVAL2_CH1_of_CH1_CCUVAL2,
    output logic  Address_EQ_Port_CH1_CCUCTRL3,
    output logic  Enable_Reg_bf_CapIM3_CH1_of_CH1_CCUCTRL3,
    output logic  Enable_Reg_bf_CCM3_CH1_of_CH1_CCUCTRL3,
    output logic  Address_EQ_Port_CH1_CCUVAL3,
    output logic  Enable_Reg_bf_CCUVAL3_CH1_of_CH1_CCUVAL3,
    output logic  Address_EQ_Port_CH1_CCUCTRL4,
    output logic  Enable_Reg_bf_CapIM4_CH1_of_CH1_CCUCTRL4,
    output logic  Enable_Reg_bf_CCM4_CH1_of_CH1_CCUCTRL4,
    output logic  Address_EQ_Port_CH1_CCUVAL4,
    output logic  Enable_Reg_bf_CCUVAL4_CH1_of_CH1_CCUVAL4,
    output logic  Address_EQ_Port_CH1_CCUCTRL5,
    output logic  Enable_Reg_bf_CapIM5_CH1_of_CH1_CCUCTRL5,
    output logic  Enable_Reg_bf_CCM5_CH1_of_CH1_CCUCTRL5,
    output logic  Address_EQ_Port_CH1_CCUVAL5,
    output logic  Enable_Reg_bf_CCUVAL5_CH1_of_CH1_CCUVAL5
);

logic   EQ03_Outp_s;
logic   LAND00_Outp_s;
logic   LAND01_Outp_s;
logic   EQ01_Outp_s;
logic   EQ02_Outp_s;
logic   [29:0] default_interface_Slice_Up_Outp_s;
logic   LAND44_Outp_s;
logic   LAND41_Outp_s;
logic   LAND40_Outp_s;
logic   LAND37_Outp_s;
logic   LAND36_Outp_s;
logic   LAND33_Outp_s;
logic   LAND32_Outp_s;
logic   LAND29_Outp_s;
logic   LAND28_Outp_s;
logic   LAND25_Outp_s;
logic   LAND24_Outp_s;
logic   LAND21_Outp_s;
logic   LAND20_Outp_s;
logic   LAND19_Outp_s;
logic   LAND14_Outp_s;
logic   LAND13_Outp_s;
logic   LAND10_Outp_s;
logic   LAND09_Outp_s;
logic   LAND08_Outp_s;
logic   LAND03_Outp_s;
logic   EQ140_Outp_s;
logic   EQ133_Outp_s;
logic   EQ126_Outp_s;
logic   EQ119_Outp_s;
logic   EQ112_Outp_s;
logic   EQ105_Outp_s;
logic   EQ98_Outp_s;
logic   EQ91_Outp_s;
logic   EQ84_Outp_s;
logic   EQ77_Outp_s;
logic   EQ70_Outp_s;
logic   EQ63_Outp_s;
logic   EQ56_Outp_s;
logic   EQ49_Outp_s;
logic   EQ42_Outp_s;
logic   EQ35_Outp_s;
logic   EQ28_Outp_s;
logic   EQ21_Outp_s;
logic   EQ14_Outp_s;
logic   EQ07_Outp_s;
logic   [1:0] default_interface_Slice_Down_Outp_s;

logic   [1:0] default_interface_Decision_Mux_Outp_s;

assign Outp = 1'b0;

assign Outp = default_interface_Slice_Down_Outp_s == 2'b11 ? 1'b1 : 1'b0;

assign Outp = default_interface_Slice_Down_Outp_s == 2'b10 ? 1'b1 : 1'b0;

assign Outp = default_interface_Slice_Down_Outp_s == 2'b1 ? 1'b1 : 1'b0;

assign Outp = default_interface_Slice_Down_Outp_s == 2'b0 ? 1'b1 : 1'b0;

assign Outp = (default_interface_Slice_Down_Outp_s == 2'b0 ? 1'b1 : 1'b0) | (default_interface_Slice_Down_Outp_s == 2'b10 ? 1'b1 : 1'b0);

assign Outp = 1'b0;

assign Outp = default_interface_Slice_Down_Outp_s == 2'b11 ? 1'b1 : 1'b0;

assign Outp = default_interface_Slice_Down_Outp_s == 2'b10 ? 1'b1 : 1'b0;

assign Outp = default_interface_Slice_Down_Outp_s == 2'b1 ? 1'b1 : 1'b0;

assign Outp = default_interface_Slice_Down_Outp_s == 2'b0 ? 1'b1 : 1'b0;

assign Outp = (default_interface_Slice_Down_Outp_s == 2'b0 ? 1'b1 : 1'b0) | (default_interface_Slice_Down_Outp_s == 2'b10 ? 1'b1 : 1'b0);

assign Outp = 1'b0;

assign Outp = default_interface_Slice_Down_Outp_s == 2'b11 ? 1'b1 : 1'b0;

assign Outp = default_interface_Slice_Down_Outp_s == 2'b10 ? 1'b1 : 1'b0;

assign Outp = default_interface_Slice_Down_Outp_s == 2'b1 ? 1'b1 : 1'b0;

assign Outp = default_interface_Slice_Down_Outp_s == 2'b0 ? 1'b1 : 1'b0;

assign Outp = (default_interface_Slice_Down_Outp_s == 2'b0 ? 1'b1 : 1'b0) | (default_interface_Slice_Down_Outp_s == 2'b10 ? 1'b1 : 1'b0);

assign Outp = 1'b0;

assign Outp = default_interface_Slice_Down_Outp_s == 2'b11 ? 1'b1 : 1'b0;

assign Outp = default_interface_Slice_Down_Outp_s == 2'b10 ? 1'b1 : 1'b0;

assign Outp = default_interface_Slice_Down_Outp_s == 2'b1 ? 1'b1 : 1'b0;

assign Outp = default_interface_Slice_Down_Outp_s == 2'b0 ? 1'b1 : 1'b0;

assign Outp = (default_interface_Slice_Down_Outp_s == 2'b0 ? 1'b1 : 1'b0) | (default_interface_Slice_Down_Outp_s == 2'b10 ? 1'b1 : 1'b0);

assign Outp = 1'b0;

assign Outp = default_interface_Slice_Down_Outp_s == 2'b11 ? 1'b1 : 1'b0;

assign Outp = default_interface_Slice_Down_Outp_s == 2'b10 ? 1'b1 : 1'b0;

assign Outp = default_interface_Slice_Down_Outp_s == 2'b1 ? 1'b1 : 1'b0;

assign Outp = default_interface_Slice_Down_Outp_s == 2'b0 ? 1'b1 : 1'b0;

assign Outp = (default_interface_Slice_Down_Outp_s == 2'b0 ? 1'b1 : 1'b0) | (default_interface_Slice_Down_Outp_s == 2'b10 ? 1'b1 : 1'b0);

assign Outp = 1'b0;

assign Outp = default_interface_Slice_Down_Outp_s == 2'b11 ? 1'b1 : 1'b0;

assign Outp = default_interface_Slice_Down_Outp_s == 2'b10 ? 1'b1 : 1'b0;

assign Outp = default_interface_Slice_Down_Outp_s == 2'b1 ? 1'b1 : 1'b0;

assign Outp = default_interface_Slice_Down_Outp_s == 2'b0 ? 1'b1 : 1'b0;

assign Outp = (default_interface_Slice_Down_Outp_s == 2'b0 ? 1'b1 : 1'b0) | (default_interface_Slice_Down_Outp_s == 2'b10 ? 1'b1 : 1'b0);

assign Outp = 1'b0;

assign Outp = default_interface_Slice_Down_Outp_s == 2'b11 ? 1'b1 : 1'b0;

assign Outp = default_interface_Slice_Down_Outp_s == 2'b10 ? 1'b1 : 1'b0;

assign Outp = default_interface_Slice_Down_Outp_s == 2'b1 ? 1'b1 : 1'b0;

assign Outp = default_interface_Slice_Down_Outp_s == 2'b0 ? 1'b1 : 1'b0;

assign Outp = (default_interface_Slice_Down_Outp_s == 2'b0 ? 1'b1 : 1'b0) | (default_interface_Slice_Down_Outp_s == 2'b10 ? 1'b1 : 1'b0);

assign Outp = 1'b0;

assign Outp = default_interface_Slice_Down_Outp_s == 2'b11 ? 1'b1 : 1'b0;

assign Outp = default_interface_Slice_Down_Outp_s == 2'b10 ? 1'b1 : 1'b0;

assign Outp = default_interface_Slice_Down_Outp_s == 2'b1 ? 1'b1 : 1'b0;

assign Outp = default_interface_Slice_Down_Outp_s == 2'b0 ? 1'b1 : 1'b0;

assign Outp = (default_interface_Slice_Down_Outp_s == 2'b0 ? 1'b1 : 1'b0) | (default_interface_Slice_Down_Outp_s == 2'b10 ? 1'b1 : 1'b0);

assign Outp = 1'b0;

assign Outp = default_interface_Slice_Down_Outp_s == 2'b11 ? 1'b1 : 1'b0;

assign Outp = default_interface_Slice_Down_Outp_s == 2'b10 ? 1'b1 : 1'b0;

assign Outp = default_interface_Slice_Down_Outp_s == 2'b1 ? 1'b1 : 1'b0;

assign Outp = default_interface_Slice_Down_Outp_s == 2'b0 ? 1'b1 : 1'b0;

assign Outp = (default_interface_Slice_Down_Outp_s == 2'b0 ? 1'b1 : 1'b0) | (default_interface_Slice_Down_Outp_s == 2'b10 ? 1'b1 : 1'b0);

assign Outp = (default_interface_Slice_Down_Outp_s == 2'b10 ? 1'b1 : 1'b0) & EQ01_Outp_s;

assign Outp = default_interface_Slice_Down_Outp_s == 2'b11 ? 1'b1 : 1'b0;

assign Outp = default_interface_Slice_Down_Outp_s == 2'b1 ? 1'b1 : 1'b0;

assign Enable_Reg_bf_CCUVAL5_CH1_of_CH1_CCUVAL5 = LAND44_Outp_s & LAND00_Outp_s;

assign Enable_Reg_bf_CCM5_CH1_of_CH1_CCUCTRL5 = LAND41_Outp_s & (LAND01_Outp_s | (EQ03_Outp_s & EQ02_Outp_s) | LAND00_Outp_s);

assign Enable_Reg_bf_CapIM5_CH1_of_CH1_CCUCTRL5 = LAND41_Outp_s & (LAND01_Outp_s | (EQ03_Outp_s & EQ02_Outp_s) | LAND00_Outp_s);

assign Enable_Reg_bf_CCUVAL4_CH1_of_CH1_CCUVAL4 = LAND40_Outp_s & LAND00_Outp_s;

assign Enable_Reg_bf_CCM4_CH1_of_CH1_CCUCTRL4 = LAND37_Outp_s & (LAND01_Outp_s | (EQ03_Outp_s & EQ02_Outp_s) | LAND00_Outp_s);

assign Enable_Reg_bf_CapIM4_CH1_of_CH1_CCUCTRL4 = LAND37_Outp_s & (LAND01_Outp_s | (EQ03_Outp_s & EQ02_Outp_s) | LAND00_Outp_s);

assign Enable_Reg_bf_CCUVAL3_CH1_of_CH1_CCUVAL3 = LAND36_Outp_s & LAND00_Outp_s;

assign Enable_Reg_bf_CCM3_CH1_of_CH1_CCUCTRL3 = LAND33_Outp_s & (LAND01_Outp_s | (EQ03_Outp_s & EQ02_Outp_s) | LAND00_Outp_s);

assign Enable_Reg_bf_CapIM3_CH1_of_CH1_CCUCTRL3 = LAND33_Outp_s & (LAND01_Outp_s | (EQ03_Outp_s & EQ02_Outp_s) | LAND00_Outp_s);

assign Enable_Reg_bf_CCUVAL2_CH1_of_CH1_CCUVAL2 = LAND32_Outp_s & LAND00_Outp_s;

assign Enable_Reg_bf_CCM2_CH1_of_CH1_CCUCTRL2 = LAND29_Outp_s & (LAND01_Outp_s | (EQ03_Outp_s & EQ02_Outp_s) | LAND00_Outp_s);

assign Enable_Reg_bf_CapIM2_CH1_of_CH1_CCUCTRL2 = LAND29_Outp_s & (LAND01_Outp_s | (EQ03_Outp_s & EQ02_Outp_s) | LAND00_Outp_s);

assign Enable_Reg_bf_CCUVAL1_CH1_of_CH1_CCUVAL1 = LAND28_Outp_s & LAND00_Outp_s;

assign Enable_Reg_bf_CCM1_CH1_of_CH1_CCUCTRL1 = LAND25_Outp_s & (LAND01_Outp_s | (EQ03_Outp_s & EQ02_Outp_s) | LAND00_Outp_s);

assign Enable_Reg_bf_CapIM1_CH1_of_CH1_CCUCTRL1 = LAND25_Outp_s & (LAND01_Outp_s | (EQ03_Outp_s & EQ02_Outp_s) | LAND00_Outp_s);

assign Enable_Reg_bf_CCUVAL0_CH1_of_CH1_CCUVAL0 = LAND24_Outp_s & LAND00_Outp_s;

assign Enable_Reg_bf_CCM0_CH1_of_CH1_CCUCTRL0 = LAND21_Outp_s & (LAND01_Outp_s | (EQ03_Outp_s & EQ02_Outp_s) | LAND00_Outp_s);

assign Enable_Reg_bf_CapIM0_CH1_of_CH1_CCUCTRL0 = LAND21_Outp_s & (LAND01_Outp_s | (EQ03_Outp_s & EQ02_Outp_s) | LAND00_Outp_s);

assign Enable_Reg_bf_MAXVAL_CH1_of_CH1_MAXVAL = LAND20_Outp_s & LAND00_Outp_s;

assign Enable_Reg_bf_ACTVAL_CH1_of_CH1_ACTVAL = LAND19_Outp_s & LAND00_Outp_s;

assign Enable_Reg_bf_TimEn_CH1_of_CH1_CTRLSTAT = LAND14_Outp_s & (LAND01_Outp_s | (EQ03_Outp_s & EQ02_Outp_s) | LAND00_Outp_s);

assign Enable_Reg_bf_ResIM_CH1_of_CH1_CTRLSTAT = LAND14_Outp_s & (LAND01_Outp_s | (EQ03_Outp_s & EQ02_Outp_s) | LAND00_Outp_s);

assign Enable_Reg_bf_CntIM_CH1_of_CH1_CTRLSTAT = LAND14_Outp_s & (LAND01_Outp_s | (EQ03_Outp_s & EQ02_Outp_s) | LAND00_Outp_s);

assign Enable_Reg_bf_OvfIntEn_CH1_of_CH1_CTRLSTAT = LAND14_Outp_s & (LAND01_Outp_s | (EQ03_Outp_s & EQ02_Outp_s) | LAND00_Outp_s);

assign Enable_Reg_bf_CCUVAL0_CH0_of_CH0_CCUVAL0 = LAND13_Outp_s & LAND00_Outp_s;

assign Enable_Reg_bf_CCM0_CH0_of_CH0_CCUCTRL0 = LAND10_Outp_s & (LAND01_Outp_s | (EQ03_Outp_s & EQ02_Outp_s) | LAND00_Outp_s);

assign Enable_Reg_bf_CapIM0_CH0_of_CH0_CCUCTRL0 = LAND10_Outp_s & (LAND01_Outp_s | (EQ03_Outp_s & EQ02_Outp_s) | LAND00_Outp_s);

assign Enable_Reg_bf_MAXVAL_CH0_of_CH0_MAXVAL = LAND09_Outp_s & LAND00_Outp_s;

assign Enable_Reg_bf_ACTVAL_CH0_of_CH0_ACTVAL = LAND08_Outp_s & LAND00_Outp_s;

assign Enable_Reg_bf_TimEn_CH0_of_CH0_CTRLSTAT = LAND03_Outp_s & (LAND01_Outp_s | (EQ03_Outp_s & EQ02_Outp_s) | LAND00_Outp_s);

assign Enable_Reg_bf_ResIM_CH0_of_CH0_CTRLSTAT = LAND03_Outp_s & (LAND01_Outp_s | (EQ03_Outp_s & EQ02_Outp_s) | LAND00_Outp_s);

assign Enable_Reg_bf_CntIM_CH0_of_CH0_CTRLSTAT = LAND03_Outp_s & (LAND01_Outp_s | (EQ03_Outp_s & EQ02_Outp_s) | LAND00_Outp_s);

assign EQ03_Outp_s = default_interface_Slice_Down_Outp_s == 2'b0 ? 1'b1 : 1'b0;

assign LAND00_Outp_s = (default_interface_Decision_Mux_Outp_s == 2'b0 ? 1'b1 : 1'b0) & EQ03_Outp_s;

assign LAND01_Outp_s = EQ03_Outp_s & EQ01_Outp_s;

assign Enable_Reg_bf_OvfIntEn_CH0_of_CH0_CTRLSTAT = LAND03_Outp_s & (LAND01_Outp_s | (EQ03_Outp_s & EQ02_Outp_s) | LAND00_Outp_s);

assign EQ01_Outp_s = default_interface_Decision_Mux_Outp_s == 2'b1 ? 1'b1 : 1'b0;

assign EQ02_Outp_s = default_interface_Decision_Mux_Outp_s == 2'b10 ? 1'b1 : 1'b0;

assign default_interface_Slice_Up_Outp_s = default_interface_addr[31:2];

assign LAND44_Outp_s = EQ140_Outp_s & default_interface_wr_en;

assign LAND41_Outp_s = EQ133_Outp_s & default_interface_wr_en;

assign LAND40_Outp_s = EQ126_Outp_s & default_interface_wr_en;

assign LAND37_Outp_s = EQ119_Outp_s & default_interface_wr_en;

assign LAND36_Outp_s = EQ112_Outp_s & default_interface_wr_en;

assign LAND33_Outp_s = EQ105_Outp_s & default_interface_wr_en;

assign LAND32_Outp_s = EQ98_Outp_s & default_interface_wr_en;

assign LAND29_Outp_s = EQ91_Outp_s & default_interface_wr_en;

assign LAND28_Outp_s = EQ84_Outp_s & default_interface_wr_en;

assign LAND25_Outp_s = EQ77_Outp_s & default_interface_wr_en;

assign LAND24_Outp_s = EQ70_Outp_s & default_interface_wr_en;

assign LAND21_Outp_s = EQ63_Outp_s & default_interface_wr_en;

assign LAND20_Outp_s = EQ56_Outp_s & default_interface_wr_en;

assign LAND19_Outp_s = EQ49_Outp_s & default_interface_wr_en;

assign LAND14_Outp_s = EQ42_Outp_s & default_interface_wr_en;

assign LAND13_Outp_s = EQ35_Outp_s & default_interface_wr_en;

assign LAND10_Outp_s = EQ28_Outp_s & default_interface_wr_en;

assign LAND09_Outp_s = EQ21_Outp_s & default_interface_wr_en;

assign LAND08_Outp_s = EQ14_Outp_s & default_interface_wr_en;

assign LAND03_Outp_s = EQ07_Outp_s & default_interface_wr_en;

assign EQ140_Outp_s = default_interface_Slice_Up_Outp_s == 30'b10011 ? 1'b1 : 1'b0;
assign Address_EQ_Port_CH1_CCUVAL5 = EQ140_Outp_s;

assign EQ133_Outp_s = default_interface_Slice_Up_Outp_s == 30'b10010 ? 1'b1 : 1'b0;
assign Address_EQ_Port_CH1_CCUCTRL5 = EQ133_Outp_s;

assign EQ126_Outp_s = default_interface_Slice_Up_Outp_s == 30'b10001 ? 1'b1 : 1'b0;
assign Address_EQ_Port_CH1_CCUVAL4 = EQ126_Outp_s;

assign EQ119_Outp_s = default_interface_Slice_Up_Outp_s == 30'b10000 ? 1'b1 : 1'b0;
assign Address_EQ_Port_CH1_CCUCTRL4 = EQ119_Outp_s;

assign EQ112_Outp_s = default_interface_Slice_Up_Outp_s == 30'b1111 ? 1'b1 : 1'b0;
assign Address_EQ_Port_CH1_CCUVAL3 = EQ112_Outp_s;

assign EQ105_Outp_s = default_interface_Slice_Up_Outp_s == 30'b1110 ? 1'b1 : 1'b0;
assign Address_EQ_Port_CH1_CCUCTRL3 = EQ105_Outp_s;

assign EQ98_Outp_s = default_interface_Slice_Up_Outp_s == 30'b1101 ? 1'b1 : 1'b0;
assign Address_EQ_Port_CH1_CCUVAL2 = EQ98_Outp_s;

assign EQ91_Outp_s = default_interface_Slice_Up_Outp_s == 30'b1100 ? 1'b1 : 1'b0;
assign Address_EQ_Port_CH1_CCUCTRL2 = EQ91_Outp_s;

assign EQ84_Outp_s = default_interface_Slice_Up_Outp_s == 30'b1011 ? 1'b1 : 1'b0;
assign Address_EQ_Port_CH1_CCUVAL1 = EQ84_Outp_s;

assign EQ77_Outp_s = default_interface_Slice_Up_Outp_s == 30'b1010 ? 1'b1 : 1'b0;
assign Address_EQ_Port_CH1_CCUCTRL1 = EQ77_Outp_s;

assign EQ70_Outp_s = default_interface_Slice_Up_Outp_s == 30'b1001 ? 1'b1 : 1'b0;
assign Address_EQ_Port_CH1_CCUVAL0 = EQ70_Outp_s;

assign EQ63_Outp_s = default_interface_Slice_Up_Outp_s == 30'b1000 ? 1'b1 : 1'b0;
assign Address_EQ_Port_CH1_CCUCTRL0 = EQ63_Outp_s;

assign EQ56_Outp_s = default_interface_Slice_Up_Outp_s == 30'b111 ? 1'b1 : 1'b0;
assign Address_EQ_Port_CH1_MAXVAL = EQ56_Outp_s;

assign EQ49_Outp_s = default_interface_Slice_Up_Outp_s == 30'b110 ? 1'b1 : 1'b0;
assign Address_EQ_Port_CH1_ACTVAL = EQ49_Outp_s;

assign EQ42_Outp_s = default_interface_Slice_Up_Outp_s == 30'b101 ? 1'b1 : 1'b0;
assign Address_EQ_Port_CH1_CTRLSTAT = EQ42_Outp_s;

assign EQ35_Outp_s = default_interface_Slice_Up_Outp_s == 30'b100 ? 1'b1 : 1'b0;
assign Address_EQ_Port_CH0_CCUVAL0 = EQ35_Outp_s;

assign EQ28_Outp_s = default_interface_Slice_Up_Outp_s == 30'b11 ? 1'b1 : 1'b0;
assign Address_EQ_Port_CH0_CCUCTRL0 = EQ28_Outp_s;

assign EQ21_Outp_s = default_interface_Slice_Up_Outp_s == 30'b10 ? 1'b1 : 1'b0;
assign Address_EQ_Port_CH0_MAXVAL = EQ21_Outp_s;

assign EQ14_Outp_s = default_interface_Slice_Up_Outp_s == 30'b1 ? 1'b1 : 1'b0;
assign Address_EQ_Port_CH0_ACTVAL = EQ14_Outp_s;

assign EQ07_Outp_s = default_interface_Slice_Up_Outp_s == 30'b0 ? 1'b1 : 1'b0;
assign Address_EQ_Port_CH0_CTRLSTAT = EQ07_Outp_s;

assign default_interface_Address_Error_Port = (~(EQ07_Outp_s | EQ14_Outp_s | EQ21_Outp_s | EQ28_Outp_s | EQ35_Outp_s | EQ42_Outp_s | EQ49_Outp_s | EQ56_Outp_s | EQ63_Outp_s | EQ70_Outp_s | EQ77_Outp_s | EQ84_Outp_s | EQ91_Outp_s | EQ98_Outp_s | EQ105_Outp_s | EQ112_Outp_s | EQ119_Outp_s | EQ126_Outp_s | EQ133_Outp_s | EQ140_Outp_s)) | ((LAND03_Outp_s & (1'b0)) | (LAND08_Outp_s & (1'b0 | ((1'b0 | (default_interface_Slice_Down_Outp_s == 2'b0 ? 1'b1 : 1'b0) | (default_interface_Slice_Down_Outp_s == 2'b1 ? 1'b1 : 1'b0) | (default_interface_Slice_Down_Outp_s == 2'b10 ? 1'b1 : 1'b0) | (default_interface_Slice_Down_Outp_s == 2'b11 ? 1'b1 : 1'b0)) & EQ02_Outp_s) | (((default_interface_Slice_Down_Outp_s == 2'b0 ? 1'b1 : 1'b0) | (default_interface_Slice_Down_Outp_s == 2'b10 ? 1'b1 : 1'b0)) & EQ01_Outp_s))) | (LAND09_Outp_s & (1'b0 | ((1'b0 | (default_interface_Slice_Down_Outp_s == 2'b0 ? 1'b1 : 1'b0) | (default_interface_Slice_Down_Outp_s == 2'b1 ? 1'b1 : 1'b0) | (default_interface_Slice_Down_Outp_s == 2'b10 ? 1'b1 : 1'b0) | (default_interface_Slice_Down_Outp_s == 2'b11 ? 1'b1 : 1'b0)) & EQ02_Outp_s) | (((default_interface_Slice_Down_Outp_s == 2'b0 ? 1'b1 : 1'b0) | (default_interface_Slice_Down_Outp_s == 2'b10 ? 1'b1 : 1'b0)) & EQ01_Outp_s))) | (LAND10_Outp_s & (1'b0)) | (LAND13_Outp_s & (1'b0 | ((1'b0 | (default_interface_Slice_Down_Outp_s == 2'b0 ? 1'b1 : 1'b0) | (default_interface_Slice_Down_Outp_s == 2'b1 ? 1'b1 : 1'b0) | (default_interface_Slice_Down_Outp_s == 2'b10 ? 1'b1 : 1'b0) | (default_interface_Slice_Down_Outp_s == 2'b11 ? 1'b1 : 1'b0)) & EQ02_Outp_s) | (((default_interface_Slice_Down_Outp_s == 2'b0 ? 1'b1 : 1'b0) | (default_interface_Slice_Down_Outp_s == 2'b10 ? 1'b1 : 1'b0)) & EQ01_Outp_s))) | (LAND14_Outp_s & (1'b0)) | (LAND19_Outp_s & (1'b0 | ((1'b0 | (default_interface_Slice_Down_Outp_s == 2'b0 ? 1'b1 : 1'b0) | (default_interface_Slice_Down_Outp_s == 2'b1 ? 1'b1 : 1'b0) | (default_interface_Slice_Down_Outp_s == 2'b10 ? 1'b1 : 1'b0) | (default_interface_Slice_Down_Outp_s == 2'b11 ? 1'b1 : 1'b0)) & EQ02_Outp_s) | (((default_interface_Slice_Down_Outp_s == 2'b0 ? 1'b1 : 1'b0) | (default_interface_Slice_Down_Outp_s == 2'b10 ? 1'b1 : 1'b0)) & EQ01_Outp_s))) | (LAND20_Outp_s & (1'b0 | ((1'b0 | (default_interface_Slice_Down_Outp_s == 2'b0 ? 1'b1 : 1'b0) | (default_interface_Slice_Down_Outp_s == 2'b1 ? 1'b1 : 1'b0) | (default_interface_Slice_Down_Outp_s == 2'b10 ? 1'b1 : 1'b0) | (default_interface_Slice_Down_Outp_s == 2'b11 ? 1'b1 : 1'b0)) & EQ02_Outp_s) | (((default_interface_Slice_Down_Outp_s == 2'b0 ? 1'b1 : 1'b0) | (default_interface_Slice_Down_Outp_s == 2'b10 ? 1'b1 : 1'b0)) & EQ01_Outp_s))) | (LAND21_Outp_s & (1'b0)) | (LAND24_Outp_s & (1'b0 | ((1'b0 | (default_interface_Slice_Down_Outp_s == 2'b0 ? 1'b1 : 1'b0) | (default_interface_Slice_Down_Outp_s == 2'b1 ? 1'b1 : 1'b0) | (default_interface_Slice_Down_Outp_s == 2'b10 ? 1'b1 : 1'b0) | (default_interface_Slice_Down_Outp_s == 2'b11 ? 1'b1 : 1'b0)) & EQ02_Outp_s) | (((default_interface_Slice_Down_Outp_s == 2'b0 ? 1'b1 : 1'b0) | (default_interface_Slice_Down_Outp_s == 2'b10 ? 1'b1 : 1'b0)) & EQ01_Outp_s))) | (LAND25_Outp_s & (1'b0)) | (LAND28_Outp_s & (1'b0 | ((1'b0 | (default_interface_Slice_Down_Outp_s == 2'b0 ? 1'b1 : 1'b0) | (default_interface_Slice_Down_Outp_s == 2'b1 ? 1'b1 : 1'b0) | (default_interface_Slice_Down_Outp_s == 2'b10 ? 1'b1 : 1'b0) | (default_interface_Slice_Down_Outp_s == 2'b11 ? 1'b1 : 1'b0)) & EQ02_Outp_s) | (((default_interface_Slice_Down_Outp_s == 2'b0 ? 1'b1 : 1'b0) | (default_interface_Slice_Down_Outp_s == 2'b10 ? 1'b1 : 1'b0)) & EQ01_Outp_s))) | (LAND29_Outp_s & (1'b0)) | (LAND32_Outp_s & (1'b0 | ((1'b0 | (default_interface_Slice_Down_Outp_s == 2'b0 ? 1'b1 : 1'b0) | (default_interface_Slice_Down_Outp_s == 2'b1 ? 1'b1 : 1'b0) | (default_interface_Slice_Down_Outp_s == 2'b10 ? 1'b1 : 1'b0) | (default_interface_Slice_Down_Outp_s == 2'b11 ? 1'b1 : 1'b0)) & EQ02_Outp_s) | (((default_interface_Slice_Down_Outp_s == 2'b0 ? 1'b1 : 1'b0) | (default_interface_Slice_Down_Outp_s == 2'b10 ? 1'b1 : 1'b0)) & EQ01_Outp_s))) | (LAND33_Outp_s & (1'b0)) | (LAND36_Outp_s & (1'b0 | ((1'b0 | (default_interface_Slice_Down_Outp_s == 2'b0 ? 1'b1 : 1'b0) | (default_interface_Slice_Down_Outp_s == 2'b1 ? 1'b1 : 1'b0) | (default_interface_Slice_Down_Outp_s == 2'b10 ? 1'b1 : 1'b0) | (default_interface_Slice_Down_Outp_s == 2'b11 ? 1'b1 : 1'b0)) & EQ02_Outp_s) | (((default_interface_Slice_Down_Outp_s == 2'b0 ? 1'b1 : 1'b0) | (default_interface_Slice_Down_Outp_s == 2'b10 ? 1'b1 : 1'b0)) & EQ01_Outp_s))) | (LAND37_Outp_s & (1'b0)) | (LAND40_Outp_s & (1'b0 | ((1'b0 | (default_interface_Slice_Down_Outp_s == 2'b0 ? 1'b1 : 1'b0) | (default_interface_Slice_Down_Outp_s == 2'b1 ? 1'b1 : 1'b0) | (default_interface_Slice_Down_Outp_s == 2'b10 ? 1'b1 : 1'b0) | (default_interface_Slice_Down_Outp_s == 2'b11 ? 1'b1 : 1'b0)) & EQ02_Outp_s) | (((default_interface_Slice_Down_Outp_s == 2'b0 ? 1'b1 : 1'b0) | (default_interface_Slice_Down_Outp_s == 2'b10 ? 1'b1 : 1'b0)) & EQ01_Outp_s))) | (LAND41_Outp_s & (1'b0)) | (LAND44_Outp_s & (1'b0 | ((1'b0 | (default_interface_Slice_Down_Outp_s == 2'b0 ? 1'b1 : 1'b0) | (default_interface_Slice_Down_Outp_s == 2'b1 ? 1'b1 : 1'b0) | (default_interface_Slice_Down_Outp_s == 2'b10 ? 1'b1 : 1'b0) | (default_interface_Slice_Down_Outp_s == 2'b11 ? 1'b1 : 1'b0)) & EQ02_Outp_s) | (((default_interface_Slice_Down_Outp_s == 2'b0 ? 1'b1 : 1'b0) | (default_interface_Slice_Down_Outp_s == 2'b10 ? 1'b1 : 1'b0)) & EQ01_Outp_s))));

assign default_interface_Slice_Down_Outp_s = default_interface_addr[1:0];

always_comb
begin
    case (default_interface_Slice_Down_Outp_s)
        2'b0 : default_interface_AS_shift_value_mux_out = 5'b0;
        2'b1 : default_interface_AS_shift_value_mux_out = 5'b1000;
        2'b10 : default_interface_AS_shift_value_mux_out = 5'b10000;
        2'b11 : default_interface_AS_shift_value_mux_out = 5'b11000;
        default : default_interface_AS_shift_value_mux_out = 5'b0;
    endcase

end

always_comb
begin
    case (default_interface_AS_in_AS_block)
        2'b0 : default_interface_Decision_Mux_Outp_s = 2'b0;
        2'b1 : default_interface_Decision_Mux_Outp_s = 2'b1;
        2'b10 : default_interface_Decision_Mux_Outp_s = 2'b10;
        default : default_interface_Decision_Mux_Outp_s = 2'b11;
    endcase

end

always_comb
begin
    case (default_interface_Decision_Mux_Outp_s)
        2'b0 : default_interface_AS_masking_mux_out = 32'b11111111111111111111111111111111;
        2'b1 : default_interface_AS_masking_mux_out = 32'b1111111111111111;
        2'b10 : default_interface_AS_masking_mux_out = 32'b11111111;
        default : default_interface_AS_masking_mux_out = 32'b0;
    endcase

end


endmodule

