/* ===============================================================
Copyright 2026, Infineon Technologies AG or an 
affiliate of Infineon Technologies AG.  All rights reserved.
 
This software, associated documentation and materials ("Software") is owned by
Infineon Technologies AG or one of its affiliates ("Infineon") and is 
protected by and subject to worldwide patent protection (United States and 
foreign), United States copyright laws and international treaty provisions. 
Therefore, you may use this Software only as provided in the license agreement
accompanying the software package from which you obtained this 
Software ("EULA"). If no EULA applies, then any reproduction, modification, 
translation, compilation, or representation of this Software is prohibited 
without the express written permission of Infineon.
 
Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF 
ANY KIND, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, 
NONINFRINGEMENT, IMPLIED WARRANTIES OF  MERCHANTABILITY AND
FITNESS FOR A PARTICULAR PURPOSE.  Infineon reserves the right to make
changes to the Software without notice. Infineon does not assume any liability
arising out of the application or use of the Software or any product or 
circuit described in the Software. Infineon does not authorize its products 
for use in any products where a malfunction or failure of the Infineon product 
may reasonably be expected to result in significant property damage, injury or
death ("High Risk Product").  By including Infineon 's product in a High Risk 
Product, the manufacturer of such system or application assumes all risk of 
such use and in doing so agrees to indemnify Infineon against all liability.

 ===============================================================
*/ 
// File : tc_soc_timer_timer_TimerChannel_1.sv 
// Author : tahiraga 
// Date : 15:07:02    25/09/2026 
// Revision :  
// =============================================================== 
// Description : 
/*
---- Auto Generated by MetaRTL , a MetaGen application
---- Contact: ParitoshKumar.Sinha@infineon.com
---- Contact: Yash.Ranjan@infineon.com
===============================================================
tc_soc_timer_timer_TimerChannel_1: Channel 1 of the Timer. Each channel is responsible for counting and signaling a particular event independently from other channels 
 */


module tc_soc_timer_timer_TimerChannel_1 (
    input logic  MAXVAL_flipflop_en,
    input logic  [31:0] MAXVAL_flipflop_in,
    output logic  [31:0] MAXVAL_flipflop_out,
    input logic  [31:0] MAXVAL_in,
    input logic  [2:0] ResIM,
    input logic  ExtRes,
    input logic  ExtCnt,
    input logic  [2:0] CntIM,
    input logic  ExtCap0,
    input logic  [2:0] CapIM0,
    input logic  ExtCap1,
    input logic  [2:0] CapIM1,
    input logic  ExtCap2,
    input logic  [2:0] CapIM2,
    input logic  ExtCap3,
    input logic  [2:0] CapIM3,
    input logic  ExtCap4,
    input logic  [2:0] CapIM4,
    input logic  ExtCap5,
    input logic  [2:0] CapIM5,
    input logic  ACTVAL_flipflop_en,
    input logic  [31:0] ACTVAL_flipflop_in,
    output logic  [31:0] ACTVAL_flipflop_out,
    input logic  [31:0] ACTVAL_in,
    output logic  [31:0] ACTVAL_out,
    output logic  ACTVAL_wr,
    input logic  TimEn,
    output logic  OvfInt,
    input logic  OvfIntRes,
    input logic  OvfIntEn,
    input logic  [2:0] CCM0,
    input logic  CCUVAL0_flipflop_en,
    input logic  [31:0] CCUVAL0_flipflop_in,
    output logic  [31:0] CCUVAL0_flipflop_out,
    input logic  [31:0] CCUVAL0_in,
    output logic  [31:0] CCUVAL0_out,
    output logic  CCUVAL0_wr,
    output logic  ExtComp0,
    input logic  [2:0] CCM1,
    input logic  CCUVAL1_flipflop_en,
    input logic  [31:0] CCUVAL1_flipflop_in,
    output logic  [31:0] CCUVAL1_flipflop_out,
    input logic  [31:0] CCUVAL1_in,
    output logic  [31:0] CCUVAL1_out,
    output logic  CCUVAL1_wr,
    output logic  ExtComp1,
    input logic  [2:0] CCM2,
    input logic  CCUVAL2_flipflop_en,
    input logic  [31:0] CCUVAL2_flipflop_in,
    output logic  [31:0] CCUVAL2_flipflop_out,
    input logic  [31:0] CCUVAL2_in,
    output logic  [31:0] CCUVAL2_out,
    output logic  CCUVAL2_wr,
    output logic  ExtComp2,
    input logic  [2:0] CCM3,
    input logic  CCUVAL3_flipflop_en,
    input logic  [31:0] CCUVAL3_flipflop_in,
    output logic  [31:0] CCUVAL3_flipflop_out,
    input logic  [31:0] CCUVAL3_in,
    output logic  [31:0] CCUVAL3_out,
    output logic  CCUVAL3_wr,
    output logic  ExtComp3,
    input logic  [2:0] CCM4,
    input logic  CCUVAL4_flipflop_en,
    input logic  [31:0] CCUVAL4_flipflop_in,
    output logic  [31:0] CCUVAL4_flipflop_out,
    input logic  [31:0] CCUVAL4_in,
    output logic  [31:0] CCUVAL4_out,
    output logic  CCUVAL4_wr,
    output logic  ExtComp4,
    input logic  [2:0] CCM5,
    input logic  CCUVAL5_flipflop_en,
    input logic  [31:0] CCUVAL5_flipflop_in,
    output logic  [31:0] CCUVAL5_flipflop_out,
    input logic  [31:0] CCUVAL5_in,
    output logic  [31:0] CCUVAL5_out,
    output logic  CCUVAL5_wr,
    output logic  ExtComp5,
    input logic  HCLK_i,
    input logic  HRESET_n_i
);

logic   CapSync_5_Sync_s;
logic   CapSync_4_Sync_s;
logic   CapSync_3_Sync_s;
logic   CapSync_2_Sync_s;
logic   CapSync_1_Sync_s;
logic   CapSync_0_Sync_s;
logic   CntSync_Sync_s;
logic   ResSync_Sync_s;
logic   [31:0] decrementer_Outp_s;
logic   ACTVALCU_AutoResCondition_s;
logic   ACTVALCU_MuxACTVAL_sel_s;


tc_soc_timer_cBitSynchronizer comp_CapSync_5(
    .Async      ( ExtCap5          ),
    .IM         ( CapIM5           ),
    .HCLK_i     ( HCLK_i           ),
    .HRESET_n_i ( HRESET_n_i       ),
    .Sync       ( CapSync_5_Sync_s )
);

tc_soc_timer_cCCUnit comp_CCU_5(
    .CCM                 ( CCM5                 ),
    .ACTVAL_in           ( ACTVAL_in            ),
    .ExtCap_trig         ( CapSync_5_Sync_s     ),
    .CCUVAL_flipflop_en  ( CCUVAL5_flipflop_en  ),
    .CCUVAL_flipflop_in  ( CCUVAL5_flipflop_in  ),
    .CCUVAL_in           ( CCUVAL5_in           ),
    .HCLK_i              ( HCLK_i               ),
    .HRESET_n_i          ( HRESET_n_i           ),
    .CCUVAL_flipflop_out ( CCUVAL5_flipflop_out ),
    .CCUVAL_out          ( CCUVAL5_out          ),
    .CCUVAL_wr           ( CCUVAL5_wr           ),
    .ExtComp             ( ExtComp5             )
);

tc_soc_timer_cBitSynchronizer comp_CapSync_4(
    .Async      ( ExtCap4          ),
    .IM         ( CapIM4           ),
    .HCLK_i     ( HCLK_i           ),
    .HRESET_n_i ( HRESET_n_i       ),
    .Sync       ( CapSync_4_Sync_s )
);

tc_soc_timer_cCCUnit comp_CCU_4(
    .CCM                 ( CCM4                 ),
    .ACTVAL_in           ( ACTVAL_in            ),
    .ExtCap_trig         ( CapSync_4_Sync_s     ),
    .CCUVAL_flipflop_en  ( CCUVAL4_flipflop_en  ),
    .CCUVAL_flipflop_in  ( CCUVAL4_flipflop_in  ),
    .CCUVAL_in           ( CCUVAL4_in           ),
    .HCLK_i              ( HCLK_i               ),
    .HRESET_n_i          ( HRESET_n_i           ),
    .CCUVAL_flipflop_out ( CCUVAL4_flipflop_out ),
    .CCUVAL_out          ( CCUVAL4_out          ),
    .CCUVAL_wr           ( CCUVAL4_wr           ),
    .ExtComp             ( ExtComp4             )
);

tc_soc_timer_cBitSynchronizer comp_CapSync_3(
    .Async      ( ExtCap3          ),
    .IM         ( CapIM3           ),
    .HCLK_i     ( HCLK_i           ),
    .HRESET_n_i ( HRESET_n_i       ),
    .Sync       ( CapSync_3_Sync_s )
);

tc_soc_timer_cCCUnit comp_CCU_3(
    .CCM                 ( CCM3                 ),
    .ACTVAL_in           ( ACTVAL_in            ),
    .ExtCap_trig         ( CapSync_3_Sync_s     ),
    .CCUVAL_flipflop_en  ( CCUVAL3_flipflop_en  ),
    .CCUVAL_flipflop_in  ( CCUVAL3_flipflop_in  ),
    .CCUVAL_in           ( CCUVAL3_in           ),
    .HCLK_i              ( HCLK_i               ),
    .HRESET_n_i          ( HRESET_n_i           ),
    .CCUVAL_flipflop_out ( CCUVAL3_flipflop_out ),
    .CCUVAL_out          ( CCUVAL3_out          ),
    .CCUVAL_wr           ( CCUVAL3_wr           ),
    .ExtComp             ( ExtComp3             )
);

tc_soc_timer_cBitSynchronizer comp_CapSync_2(
    .Async      ( ExtCap2          ),
    .IM         ( CapIM2           ),
    .HCLK_i     ( HCLK_i           ),
    .HRESET_n_i ( HRESET_n_i       ),
    .Sync       ( CapSync_2_Sync_s )
);

tc_soc_timer_cCCUnit comp_CCU_2(
    .CCM                 ( CCM2                 ),
    .ACTVAL_in           ( ACTVAL_in            ),
    .ExtCap_trig         ( CapSync_2_Sync_s     ),
    .CCUVAL_flipflop_en  ( CCUVAL2_flipflop_en  ),
    .CCUVAL_flipflop_in  ( CCUVAL2_flipflop_in  ),
    .CCUVAL_in           ( CCUVAL2_in           ),
    .HCLK_i              ( HCLK_i               ),
    .HRESET_n_i          ( HRESET_n_i           ),
    .CCUVAL_flipflop_out ( CCUVAL2_flipflop_out ),
    .CCUVAL_out          ( CCUVAL2_out          ),
    .CCUVAL_wr           ( CCUVAL2_wr           ),
    .ExtComp             ( ExtComp2             )
);

tc_soc_timer_cBitSynchronizer comp_CapSync_1(
    .Async      ( ExtCap1          ),
    .IM         ( CapIM1           ),
    .HCLK_i     ( HCLK_i           ),
    .HRESET_n_i ( HRESET_n_i       ),
    .Sync       ( CapSync_1_Sync_s )
);

tc_soc_timer_cCCUnit comp_CCU_1(
    .CCM                 ( CCM1                 ),
    .ACTVAL_in           ( ACTVAL_in            ),
    .ExtCap_trig         ( CapSync_1_Sync_s     ),
    .CCUVAL_flipflop_en  ( CCUVAL1_flipflop_en  ),
    .CCUVAL_flipflop_in  ( CCUVAL1_flipflop_in  ),
    .CCUVAL_in           ( CCUVAL1_in           ),
    .HCLK_i              ( HCLK_i               ),
    .HRESET_n_i          ( HRESET_n_i           ),
    .CCUVAL_flipflop_out ( CCUVAL1_flipflop_out ),
    .CCUVAL_out          ( CCUVAL1_out          ),
    .CCUVAL_wr           ( CCUVAL1_wr           ),
    .ExtComp             ( ExtComp1             )
);

tc_soc_timer_cBitSynchronizer comp_CapSync_0(
    .Async      ( ExtCap0          ),
    .IM         ( CapIM0           ),
    .HCLK_i     ( HCLK_i           ),
    .HRESET_n_i ( HRESET_n_i       ),
    .Sync       ( CapSync_0_Sync_s )
);

tc_soc_timer_cCCUnit comp_CCU_0(
    .CCM                 ( CCM0                 ),
    .ACTVAL_in           ( ACTVAL_in            ),
    .ExtCap_trig         ( CapSync_0_Sync_s     ),
    .CCUVAL_flipflop_en  ( CCUVAL0_flipflop_en  ),
    .CCUVAL_flipflop_in  ( CCUVAL0_flipflop_in  ),
    .CCUVAL_in           ( CCUVAL0_in           ),
    .HCLK_i              ( HCLK_i               ),
    .HRESET_n_i          ( HRESET_n_i           ),
    .CCUVAL_flipflop_out ( CCUVAL0_flipflop_out ),
    .CCUVAL_out          ( CCUVAL0_out          ),
    .CCUVAL_wr           ( CCUVAL0_wr           ),
    .ExtComp             ( ExtComp0             )
);

tc_soc_timer_cInterruptControlUnit comp_InterruptCU(
    .OvfIntRes        ( OvfIntRes                   ),
    .OvfIntEn         ( OvfIntEn                    ),
    .AutoResCondition ( ACTVALCU_AutoResCondition_s ),
    .HCLK_i           ( HCLK_i                      ),
    .HRESET_n_i       ( HRESET_n_i                  ),
    .OvfInt           ( OvfInt                      )
);

tc_soc_timer_cBitSynchronizer comp_CntSync(
    .Async      ( ExtCnt         ),
    .IM         ( CntIM          ),
    .HCLK_i     ( HCLK_i         ),
    .HRESET_n_i ( HRESET_n_i     ),
    .Sync       ( CntSync_Sync_s )
);

tc_soc_timer_cBitSynchronizer comp_ResSync(
    .Async      ( ExtRes         ),
    .IM         ( ResIM          ),
    .HCLK_i     ( HCLK_i         ),
    .HRESET_n_i ( HRESET_n_i     ),
    .Sync       ( ResSync_Sync_s )
);

assign decrementer_Outp_s = ACTVAL_in - 32'b1;

tc_soc_timer_cACTVALControlUnit comp_ACTVALCU(
    .TimEn            ( TimEn                       ),
    .ResIM            ( ResIM                       ),
    .CntIM            ( CntIM                       ),
    .ExtRes_sync      ( ResSync_Sync_s              ),
    .ExtCnt_sync      ( CntSync_Sync_s              ),
    .ACTVAL           ( ACTVAL_in                   ),
    .AutoResCondition ( ACTVALCU_AutoResCondition_s ),
    .MuxACTVAL_sel    ( ACTVALCU_MuxACTVAL_sel_s    ),
    .ACTVAL_wr        ( ACTVAL_wr                   )
);

always_comb
begin
    ACTVAL_out = (ACTVALCU_MuxACTVAL_sel_s) ? MAXVAL_in : decrementer_Outp_s;
end

always_ff @(negedge HRESET_n_i, posedge HCLK_i)
begin
    if (HRESET_n_i == 1'b0) begin
        ACTVAL_flipflop_out <= 32'b0;
    end else begin
        if (ACTVAL_flipflop_en == 1'b1) begin
            ACTVAL_flipflop_out <= ACTVAL_flipflop_in;
        end
    end

end

always_ff @(negedge HRESET_n_i, posedge HCLK_i)
begin
    if (HRESET_n_i == 1'b0) begin
        MAXVAL_flipflop_out <= 32'b0;
    end else begin
        if (MAXVAL_flipflop_en == 1'b1) begin
            MAXVAL_flipflop_out <= MAXVAL_flipflop_in;
        end
    end

end


endmodule

